### ISSUE TITLE
set / update existing key value :

### ISSUE THREAD

**Issue by fas3r** [RedisJSON/RedisJSON#101]
Hello, 

after doing a JSON.SET myKey . myJsonData, how can I update a single value.

For example in the following : 

`JSON.SET myKey . '{  
   "name" : "myName",  
   "email" : "myName@mycorp.com",  
   "username" : "myUserName"  
}'`

To udpate one value it will be :  `JSON.SET myKey .name '"myNewName"'`

But can I update only the value email and username ? I tried the following but it's overwriting the key, not updating the value :

 `JSON.SET myKey . '{ "email" : "changed@mycorp.com", "username" : "myNewUserName"}'`

Thanks.

**Comment by fas3r** [comment]
Hello @itamarhaber , 

Ok, thanks, looking forward for the JSON.MERGE feature 😄

**Comment by fas3r** [comment]
Hello @itamarhaber ,  

Last question, can . I use filters like  `[?(@.id==1)]` or similar with json.get ?

Thanks again.

**Comment by itamarhaber** [comment]
Nope - ReJSON does not provide that functionality.

**Comment by romkazor** [comment]
> Hello @fas3r
> 
> Currently, you'd have to break the update to two separate operations, i.e.:
> 
> ```
> JSON.SET myKey .email changed@mycorp.com
> JSON.SET myKey .username myNewUserName
> ```

Thanks for answer, but could you please give a little explanation why RedisJSON can't update multiple keys or add multiple keys to existing object?! Thanks.

**Comment by oshadmi** [comment]
Duplicate issue #34

**Comment by gkorland** [comment]
Closed as Duplicate
