### ISSUE TITLE
[Q] How to build project

### ISSUE THREAD

**Issue by arthurkiller** [RedisJSON/RedisJSON#1071]
New to rust, rust version and cargo version is

> rustc 1.41.1
> cargo 1.42.1

```
arthur@arthur-dev-box:~/c/s/RedisJSON:(HEAD detached at v2.6.6)$ cargo build --release
error: failed to parse manifest at `/data00/home/arthur/codes/src/RedisJSON/json_path/Cargo.toml`

Caused by:
  invalid type: map, expected a string for key `package.edition`
```

**Comment by arthurkiller** [comment]
closed via solved by reset rust env

**Comment by KenLee12323** [comment]
> closed via solved by reset rust env

Hi, I am newer then you in rust. I am also having this problem. Could you kindly tell me how you reset the rust environment? Or should we simply add 'edition =  2023' at line7 in the Cargo.toml file?

Many thanks!
