### ISSUE TITLE
There is an exists method for redisjson?

### ISSUE THREAD

**Issue by Hocoh** [RedisJSON/RedisJSON#109]
I would appreciate if an object is present in my database, currently an exists function is missing IMHO.

Would be great to have this feature in ReJson. Meanwhile we can workaround with the other type detection and all, but would be great to have a feature specifically dedicated to that function. It is handleable   to implement this function? 

Thanks

**Comment by gkorland** [comment]
I'm not sure I understand the need, what is wrong with Redis EXISTS? https://redis.io/commands/EXISTS

**Comment by rjcortese** [comment]
The issue afaik is that Redis EXISTS only detects if the top level key exists.
The functionality that @Hocoh (and myself) are interested in is something like
`rj.exists('my_key', '.some.path.through.the.json.object')`

**Comment by gkorland** [comment]
You can use https://oss.redislabs.com/redisjson/commands/#jsontype
