### ISSUE TITLE
Reclaiming memory?

### ISSUE THREAD

**Issue by jshlbrd** [RedisJSON/RedisJSON#110]
Great addition to Redis, I have a quick question regarding the comments on reclaiming memory. The project README says this: 
`Containers are not scaled down after deleting items (i.e. free memory isn't reclaimed)`

But https://github.com/RedisLabsModules/redisjson/blob/a25dc6296655a215b1ff7ef7323b2d819fcc79e3/deps/RedisModuleSDK/TYPES.md says this:
`free is called when a key with the module native type is deleted via DEL or in any other mean, in order to let the module reclaim the memory associated with such a value.`

Are these two statements in conflict and, if so, which one is accurate?

**Comment by itamarhaber** [comment]
Hello @jshlbrd

Both statements are correct. Containers are objects/arrays inside a redisjson key. When entire redisjson keys are DELed, all memory is reclaimed (by Redis).
