### ISSUE TITLE
I`m try compile rejson in FreeBSD, and process compile filed :(

### ISSUE THREAD

**Issue by velogonshik** [RedisJSON/RedisJSON#112]
My steps:
**pkg install redis git-lite gmake bash
git clone https://github.com/RedisLabsModules/rejson.git
cd rejson/src
gmake**

error------------>

```
ld: error: unknown argument: -dylib
ld: error: unknown emulation: acosx_version_min
ld: error: cannot open _RedisModule_OnLoad: No such file or directory
ld: error: cannot open 10.6: No such file or directory
ld: error: unable to find library -lc
ld: error: unable to find library -lm
gmake: *** [Makefile:53: rejson.so] Ошибка 1
```

<------------error

**Comment by itamarhaber** [comment]
Hello @velogonshik 

Thanks for reporting this issue.

Currently, RedisJSON and the other RedisLabs modules are not tested for FreeBSD. Until this happens, you can try hacking the makefile and see if you can make it compile for you - it appears that the OS is not recognized so Darwin settings are used.

**Comment by dpate117** [comment]
@velogonshik 
Issue no.1 Fix. Please change the make file in RedisJSON-master/src folder 

# Compile flags for linux / osx
#ifeq ($(uname_S),Linux)
	SHOBJ_CFLAGS ?=  -fno-common -g -ggdb
	SHOBJ_LDFLAGS ?= -shared -Bsymbolic -Bsymbolic-functions --sysroot=/c/Linaro/gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf/bin/../arm-linux-gnueabihf/libc
#else
#	CFLAGS += -mmacosx-version-min=10.6
#	SHOBJ_CFLAGS ?= -dynamic -fno-common -g -ggdb
#	SHOBJ_LDFLAGS ?= -dylib -exported_symbol _RedisModule_OnLoad -macosx_version_min 10.6
#endif

Issue # 2 fix 
you could point all right compiler(CC), linker(LD), archiever (AR) manually 
You might want to manually define sysroot directory as well.
NOTE: I am using cross compiler here so I have to manually define everything. You might not have to do that 
just add statement to LD flags. 
--sysroot=/c/Linaro/gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf/bin/../arm-linux-gnueabihf/libc

**Comment by gkorland** [comment]
@velogonshik @dpate117 RedisJSON was rewritten in Rust build for other OSs should be easier now

**Comment by velogonshik** [comment]
> @velogonshik @dpate117 RedisJSON was rewritten in Rust build for other OSs should be easier now
Build problem
https://postq.ru/p/Jrdki

**Comment by velogonshik** [comment]
> @velogonshik @dpate117 RedisJSON was rewritten in Rust build for other OSs should be easier now
Again problems :(
https://postq.ru/p/yESaE

**Comment by osokin** [comment]
Hi there,

I've just committed databases/redisjson port into FreeBSD ports tree, https://cgit.FreeBSD.org/ports/commit/?id=e66f56f4af6a96b837853217f0d66b6f01e06381.

I believe this issue can be closed.

Thank you.
