### ISSUE TITLE
JSON.ARRINDEX usage

### ISSUE THREAD

**Issue by danielmeneses** [RedisJSON/RedisJSON#113]
Hi,

I have a general question in regards to the JSON.ARRINDEX usage, so I'd appreciate any help.

I'm doing something like:
`JSON.SET test . '{"data": [{"name":"John"}, {"name":"Jane"}]}'`

Then I'd like to get the index by name, so I tried:
`JSON.ARRINDEX test .data '{"name": "Jane"}'`
Which obviously doesn't work. Is there a way to get the index in an array containing objects?
I understand that this does work if the array is a list of primitive values, but can't get it to work with objects. 

thanks

**Comment by itamarhaber** [comment]
Hello @danielmeneses 

`JSON.ARRINDEX` can only search for scalar values. Objects and arrays are not scalars so you can't search for them.

I am interested, however, in the use that you're trying to implement so I'd appreciate more insight into the challenge at hand.

**Comment by danielmeneses** [comment]
Hi, @itamarhaber thanks,
yes, missed the scalar part.

There isn't actually a use-case for the given example. I'm just checking out the potential of the API itself.
I could definitely overcome this by setting indexes as keys and use those to query data instead of using arrays.

Now, arrays can make it easier in some cases, say you want to track the order of events of some kind. You could simply push an object (describing changes) into the array and then you could filter by any of the fields to get only what you need and it would be sorted by occurrence, i.e., no need to reorder by timestamp, so no extra work on the client.

Anyway, I think it would be a good thing to be able to filter arrays containing objects, but I understand it raises a bunch of new challenges and it's probably a lot of work because you would have endless possible operations ($eq, $neq, $gt, $gte, etc..).

**Comment by itamarhaber** [comment]
Thanks for the input.

The current plan is to complete the [JSONPath](https://goessner.net/articles/JsonPath/index.html) implementation that RedisJSON uses, which would hopefully make this (i.e. endless possible operations) possible with boolean predicates.

**Comment by gkorland** [comment]
@danielmeneses You might want to https://github.com/RedisJSON/RedisDoc
As part of this project we're rewriting RedisJSON in Rust and also adding full jsonpath support

**Comment by danielmeneses** [comment]
Sounds great @gkorland ... definitely, a got to after it's up and running.. do you have any roadmap for this project?

Appreciate all the hard work!

**Comment by gkorland** [comment]
@danielmeneses the plan is to have 1.0.0 RC in the next week with full JSONPath and probably support for secondary index and free text search

**Comment by gkorland** [comment]
@danielmeneses please see RedisJSON 2.0 and RediSearch 2.2
