### ISSUE TITLE
Revert JSONPath default path value from `$` to `.` under RESP3

### ISSUE THREAD

**Issue by LiorKogan** [RedisJSON/RedisJSON#1131]
For the following commands, the `path` argument is optional.
Currently the default `path` value is `.` under RESP2 and `$` under RESP3.

```
JSON.ARRLEN key [path]
JSON.ARRPOP key [FORMAT STRINGS|EXPAND1|EXPAND] [path [index]]
JSON.DEBUG MEMORY key [path]
JSON.DEL key [path]
JSON.GET key [INDENT indent] [NEWLINE newline] [SPACE space] [FORMAT STRINGS|EXPAND1|EXPAND] [path [path ...]]
JSON.OBJKEYS key [path…]
JSON.OBJLEN key [path]
JSON.STRAPPEND key [path] value
JSON.STRLEN key [path]
JSON.TYPE key [path…]
```

Due to many request we decided to revert the default `path` value to `.` under both RESP2 and RESP3.

One request: https://github.com/RedisJSON/RedisJSON/issues/1090

**Comment by ephraimfeldblum** [comment]
This has been attended to in #1143 . This issue can be closed.
