### ISSUE TITLE
Build error on Windows

### ISSUE THREAD

**Issue by zkteco-home** [RedisJSON/RedisJSON#1139]
before i built https://github.com/zkteco-home/RedisJson   (2.0.4),but i cant build lastest version,the followinng error message,please check it

![image](https://github.com/RedisJSON/RedisJSON/assets/66519168/3a179bbc-a545-44ea-89e1-3e8550ce6276)

**Comment by zkteco-home** [comment]
![image](https://github.com/RedisJSON/RedisJSON/assets/66519168/399f8c80-b2c9-47ef-b590-cf1324b5de61)

**Comment by vityafx** [comment]
[Redis isn't officially supported on Windows, according to the documentation](https://redis.io/docs/install/install-redis/install-redis-on-windows/). This means the modules too.

**Comment by zkteco-home** [comment]
I think this is not a reason,I compiled Redis windows and i also built RedisJson 2.4.6 https://github.com/zkteco-home/redis-windows and https://github.com/zkteco-home/RedisJson,RedisJson working fine on windows,so now just there is small issue ,

**Comment by zkteco-home** [comment]
![image](https://github.com/RedisJSON/RedisJSON/assets/66519168/f50ff1b3-8617-4c6c-b7b7-135ed08528b1)

need to remove it

**Comment by zkteco-home** [comment]
![image](https://github.com/RedisJSON/RedisJSON/assets/66519168/194a33b3-d760-4b71-aa99-790d60caa8f3)

Build successfully on Window platform.

![image](https://github.com/RedisJSON/RedisJSON/assets/66519168/64b35fde-9414-4583-afbd-0cb941aef95a)

download:https://github.com/zkteco-home/RedisJson
