### ISSUE TITLE
JSON.SET How to use NX / XX ?

### ISSUE THREAD

**Issue by nikolamakin** [RedisJSON/RedisJSON#116]
JSON.SET How to use NX / XX ?

if that this is perfect: JSON.SETNX KEY_NAME FIELD_NAME

thank

**Comment by itamarhaber** [comment]
Hello @nikolamakin 

Actually, it would be `JSON.SET KEY_NAME PATH JSONVALUE NX`

**Comment by nikolamakin** [comment]
thank u @itamarhaber
