### ISSUE TITLE
incorrect representation of numbers with floating point

### ISSUE THREAD

**Issue by glassfox** [RedisJSON/RedisJSON#117]
Hi, 
Found the issue with float representation. following the example:

`>JSON.SET json . '{"float":0.1}'`
`"OK"`
`>JSON.GET json`
`"{"float":0.10000000000000001}"`

**Comment by itamarhaber** [comment]
Hello @glassfox 

This is a known issue resulting from precision (or lack of it) when using 64bit floats. In a future version, we are considering to replace that with something more accurate that will allow storing arbitrarily long numbers (and floats)

**Comment by gkorland** [comment]
RedisJSON2 was merged to master
