### ISSUE TITLE
JSON.GET traverse nested JSON data

### ISSUE THREAD

**Issue by abhishek199-dhn** [RedisJSON/RedisJSON#118]
Hey Guys, 

I need to traverse nested JSON object and get retrieve its value using JSON path syntax.
Eg:  
```
JSON.SET acl_user_rule_1 . '{"access":{"organisations":{"orgId1":{"applications":{"appId1": true}},"orgId2":{"applications":{"appId1": true}}}}}'

```

I need to GET/DELETE appId1 in all organizations. 
Like - ```JSON.GET acl_user_rule_1 ".access.organisations.*.applications.appId1"```

Is this possible to do?

**Comment by itamarhaber** [comment]
Hello @abhishek199-dhn 

This is currently not supported but planned to be (i.e full JSONPath syntax). Currently the ETA is unknown.

**Comment by abhishek199-dhn** [comment]
@itamarhaber thanks :) looking forward to the future release

**Comment by gkorland** [comment]
@abhishek199-dhn You might want to https://github.com/RedisJSON/RedisDoc
As part of this project we're rewriting RedisJSON in Rust and also adding full jsonpath support

**Comment by gkorland** [comment]
RedisJSON2 was merged to master
