### ISSUE TITLE
Can't Load Module on Rasberry Pi 3. Is Arm64 supported?

### ISSUE THREAD

**Issue by Barto101** [RedisJSON/RedisJSON#1189]
I've been going in circles for about 20 hours of googling and trying pretty much every setting to get RedisJSON to load as a module on my redis server running on Rasberry Pi 3.
I have Ubuntu Server 22.04 and Redis Server 7.2.4 running fine using systemd without the module loading.

I've included the necessary redis.conf change to load the module including adding:

loadmodule /var/lib/redis/librejson.so

Tried various folder and file permission changes, service/config changes, too numerous to recall...

I've tried downloading the precompiled version from the official download area...no good.
Tried building it myself on the Pi, but that hung at some point...no good.
Tried building on my other machine, which worked but transferring the .so to Pi and attempting load fails also.

Has anyone successfully got the current RedisJSON module working with Redis Server 7.2.4 on a Rasberry Pi, or should I abandon this "dream machine" at the last hurdle?

Thanks for any help.

**Comment by iddm** [comment]
Hi @Barto101! First and foremost, thank you for the feedback! We greatly appreciate it!

Please don't get rid of the little Raspberry Pi; I think it can still serve you well! :-) 

Can you please share a little bit more information on the problems you have? I just want to have a little more clear understanding of what you currently have. Some Redis startup logs (if systems, then `journalctl` would help, perhaps). Do you have any errors reported anywhere? Can you please provide an output of this?

```sh
file /var/lib/redis/librejson.so
```

**Comment by Barto101** [comment]
Hi iddm

When I output
 file /var/lib/redis/librejson.so

I get the following:
/var/lib/redis/librejson.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=5c79d8a4cc53eb6142a27aa545e006f80a9a87e2, with debug_info, not stripped

When I try to start or restart the service like so:
sudo systemctl restart redis-server

Looking using journalctl -u redis-server.service -n 100 -f
I get the following, which is not very helpful:

Feb 29 09:54:01 ubuntu-ras-server systemd[1]: Starting Advanced key-value store...
Feb 29 09:54:01 ubuntu-ras-server systemd[1]: redis-server.service: Main process exited, code=exited, status=1/FAILURE
Feb 29 09:54:01 ubuntu-ras-server systemd[1]: redis-server.service: Failed with result 'exit-code'.
Feb 29 09:54:01 ubuntu-ras-server systemd[1]: Failed to start Advanced key-value store.
Feb 29 09:54:01 ubuntu-ras-server systemd[1]: redis-server.service: Scheduled restart job, restart counter is at 1.
Feb 29 09:54:01 ubuntu-ras-server systemd[1]: Stopped Advanced key-value store.
Feb 29 09:54:01 ubuntu-ras-server systemd[1]: Starting Advanced key-value store...
Feb 29 09:54:02 ubuntu-ras-server systemd[1]: redis-server.service: Main process exited, code=exited, status=1/FAILURE
Feb 29 09:54:02 ubuntu-ras-server systemd[1]: redis-server.service: Failed with result 'exit-code'.
Feb 29 09:54:02 ubuntu-ras-server systemd[1]: Failed to start Advanced key-value store.
Feb 29 09:54:02 ubuntu-ras-server systemd[1]: redis-server.service: Scheduled restart job, restart counter is at 2.
Feb 29 09:54:02 ubuntu-ras-server systemd[1]: Stopped Advanced key-value store.
Feb 29 09:54:02 ubuntu-ras-server systemd[1]: Starting Advanced key-value store...
Feb 29 09:54:02 ubuntu-ras-server systemd[1]: redis-server.service: Main process exited, code=exited, status=1/FAILURE
Feb 29 09:54:02 ubuntu-ras-server systemd[1]: redis-server.service: Failed with result 'exit-code'.
Feb 29 09:54:02 ubuntu-ras-server systemd[1]: Failed to start Advanced key-value store.
Feb 29 09:54:02 ubuntu-ras-server systemd[1]: redis-server.service: Scheduled restart job, restart counter is at 3.
Feb 29 09:54:02 ubuntu-ras-server systemd[1]: Stopped Advanced key-value store.
Feb 29 09:54:02 ubuntu-ras-server systemd[1]: Starting Advanced key-value store...
Feb 29 09:54:03 ubuntu-ras-server systemd[1]: redis-server.service: Main process exited, code=exited, status=1/FAILURE
Feb 29 09:54:03 ubuntu-ras-server systemd[1]: redis-server.service: Failed with result 'exit-code'.
Feb 29 09:54:03 ubuntu-ras-server systemd[1]: Failed to start Advanced key-value store.
Feb 29 09:54:03 ubuntu-ras-server systemd[1]: redis-server.service: Scheduled restart job, restart counter is at 4.
Feb 29 09:54:03 ubuntu-ras-server systemd[1]: Stopped Advanced key-value store.
Feb 29 09:54:03 ubuntu-ras-server systemd[1]: Starting Advanced key-value store...
Feb 29 09:54:03 ubuntu-ras-server systemd[1]: redis-server.service: Main process exited, code=exited, status=1/FAILURE
Feb 29 09:54:03 ubuntu-ras-server systemd[1]: redis-server.service: Failed with result 'exit-code'.
Feb 29 09:54:03 ubuntu-ras-server systemd[1]: Failed to start Advanced key-value store.
Feb 29 09:54:04 ubuntu-ras-server systemd[1]: redis-server.service: Scheduled restart job, restart counter is at 5.
Feb 29 09:54:04 ubuntu-ras-server systemd[1]: Stopped Advanced key-value store.
Feb 29 09:54:04 ubuntu-ras-server systemd[1]: redis-server.service: Start request repeated too quickly.
Feb 29 09:54:04 ubuntu-ras-server systemd[1]: redis-server.service: Failed with result 'exit-code'.
Feb 29 09:54:04 ubuntu-ras-server systemd[1]: Failed to start Advanced key-value store.

I have also attempted to load the module from the precompiled build ( the one I originally downloaded from redis official site)
Using this location and had similar problems:
/etc/redis/modules/rejson.so

I also attempted to load that one manually without systemd using:
$ redis-server --loadmodule /etc/redis/modules/rejson.so

and got this:
3593:M 29 Feb 2024 10:00:29.423 # Module /etc/redis/modules/rejson.so failed to load: /etc/redis/modules/rejson.so: cannot open shared object file: Permission denied
3593:M 29 Feb 2024 10:00:29.423 # Can't load module from /etc/redis/modules/rejson.so: server aborting

This is somewhat frustrating, as I have opened folder permissions according to some other posts...such as this one:
https://github.com/RedisJSON/RedisJSON/issues/252#issuecomment-748465581

Thanks for your help

**Comment by Barto101** [comment]
I've also just found that I can't load the redis time series module using the same method either. Thus this is not exclusively related to RedisJSON on my setup. Any further suggestions would be appreciated though.

**Comment by iddm** [comment]
> Hi iddm
> 
> When I output file /var/lib/redis/librejson.so
> 
> I get the following: /var/lib/redis/librejson.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=5c79d8a4cc53eb6142a27aa545e006f80a9a87e2, with debug_info, not stripped
> 
> When I try to start or restart the service like so: sudo systemctl restart redis-server
> 
> Looking using journalctl -u redis-server.service -n 100 -f I get the following, which is not very helpful:
> 
> Feb 29 09:54:01 ubuntu-ras-server systemd[1]: Starting Advanced key-value store... Feb 29 09:54:01 ubuntu-ras-server systemd[1]: redis-server.service: Main process exited, code=exited, status=1/FAILURE Feb 29 09:54:01 ubuntu-ras-server systemd[1]: redis-server.service: Failed with result 'exit-code'. Feb 29 09:54:01 ubuntu-ras-server systemd[1]: Failed to start Advanced key-value store. Feb 29 09:54:01 ubuntu-ras-server systemd[1]: redis-server.service: Scheduled restart job, restart counter is at 1. Feb 29 09:54:01 ubuntu-ras-server systemd[1]: Stopped Advanced key-value store. Feb 29 09:54:01 ubuntu-ras-server systemd[1]: Starting Advanced key-value store... Feb 29 09:54:02 ubuntu-ras-server systemd[1]: redis-server.service: Main process exited, code=exited, status=1/FAILURE Feb 29 09:54:02 ubuntu-ras-server systemd[1]: redis-server.service: Failed with result 'exit-code'. Feb 29 09:54:02 ubuntu-ras-server systemd[1]: Failed to start Advanced key-value store. Feb 29 09:54:02 ubuntu-ras-server systemd[1]: redis-server.service: Scheduled restart job, restart counter is at 2. Feb 29 09:54:02 ubuntu-ras-server systemd[1]: Stopped Advanced key-value store. Feb 29 09:54:02 ubuntu-ras-server systemd[1]: Starting Advanced key-value store... Feb 29 09:54:02 ubuntu-ras-server systemd[1]: redis-server.service: Main process exited, code=exited, status=1/FAILURE Feb 29 09:54:02 ubuntu-ras-server systemd[1]: redis-server.service: Failed with result 'exit-code'. Feb 29 09:54:02 ubuntu-ras-server systemd[1]: Failed to start Advanced key-value store. Feb 29 09:54:02 ubuntu-ras-server systemd[1]: redis-server.service: Scheduled restart job, restart counter is at 3. Feb 29 09:54:02 ubuntu-ras-server systemd[1]: Stopped Advanced key-value store. Feb 29 09:54:02 ubuntu-ras-server systemd[1]: Starting Advanced key-value store... Feb 29 09:54:03 ubuntu-ras-server systemd[1]: redis-server.service: Main process exited, code=exited, status=1/FAILURE Feb 29 09:54:03 ubuntu-ras-server systemd[1]: redis-server.service: Failed with result 'exit-code'. Feb 29 09:54:03 ubuntu-ras-server systemd[1]: Failed to start Advanced key-value store. Feb 29 09:54:03 ubuntu-ras-server systemd[1]: redis-server.service: Scheduled restart job, restart counter is at 4. Feb 29 09:54:03 ubuntu-ras-server systemd[1]: Stopped Advanced key-value store. Feb 29 09:54:03 ubuntu-ras-server systemd[1]: Starting Advanced key-value store... Feb 29 09:54:03 ubuntu-ras-server systemd[1]: redis-server.service: Main process exited, code=exited, status=1/FAILURE Feb 29 09:54:03 ubuntu-ras-server systemd[1]: redis-server.service: Failed with result 'exit-code'. Feb 29 09:54:03 ubuntu-ras-server systemd[1]: Failed to start Advanced key-value store. Feb 29 09:54:04 ubuntu-ras-server systemd[1]: redis-server.service: Scheduled restart job, restart counter is at 5. Feb 29 09:54:04 ubuntu-ras-server systemd[1]: Stopped Advanced key-value store. Feb 29 09:54:04 ubuntu-ras-server systemd[1]: redis-server.service: Start request repeated too quickly. Feb 29 09:54:04 ubuntu-ras-server systemd[1]: redis-server.service: Failed with result 'exit-code'. Feb 29 09:54:04 ubuntu-ras-server systemd[1]: Failed to start Advanced key-value store.
> 
> I have also attempted to load the module from the precompiled build ( the one I originally downloaded from redis official site) Using this location and had similar problems: /etc/redis/modules/rejson.so
> 
> I also attempted to load that one manually without systemd using: $ redis-server --loadmodule /etc/redis/modules/rejson.so
> 
> and got this: 3593:M 29 Feb 2024 10:00:29.423 # Module /etc/redis/modules/rejson.so failed to load: /etc/redis/modules/rejson.so: cannot open shared object file: Permission denied 3593:M 29 Feb 2024 10:00:29.423 # Can't load module from /etc/redis/modules/rejson.so: server aborting
> 
> This is somewhat frustrating, as I have opened folder permissions according to some other posts...such as this one: [#252 (comment)](https://github.com/RedisJSON/RedisJSON/issues/252#issuecomment-748465581)
> 
> Thanks for your help

As far as I can see and judge from your output, you do seem to have the `redis-server` built for `arm64` architecture just fine, but the library (`rejson.so` here in your case) is built for the `x86_64` architecture. It is not possible to mix CPU architectures as the CPU expects different instructions, only the ones it supports and is designed for. The Raspberry Pi processors are all of ARM architecture; thus, it is required to have only the binaries built for this architecture.

Now, you said you went to download the official pre-built binaries. If one looks carefully, it can be observed that there is a little piece of text saying that the binaries available for download are only of two architectures: `x86` and `x86_64`. There are no ARM downloads available on the official downloads page.

We do not ship the binaries in a stand-alone way anymore. What we do now is shipping something called ["Redis Stack"](https://redis.io/download/). On [this page](https://redis.io/download/), you may find the "Ubuntu focal arm64" binaries of the Redis stack. The file you may download from this link should contain the `rejson.so` library built for the `arm64` architecture, which you should be able to use on Raspberry Pi 3.

I apologise for the confusion; we will do our best to reflect the changes in our documentation.

**Comment by Barto101** [comment]
Hi iddm
Thank you very much for your help. This clarifies things a lot. I'll look into these downloads to solve the problem.
I would've been going in circles forever without this.
Cheers :)

**Comment by Barto101** [comment]
The modules inside the Ubuntu Focal arm64 file on that download page https://redis.io/download/
did the trick for me. Problem solved. 
Thanks again.
