### ISSUE TITLE
Getting mangled data back with JSON.set / JSON.get

### ISSUE THREAD

**Issue by mschipperheyn** [RedisJSON/RedisJSON#119]
I just updated a ReJSON docker container to the latest version, but I still have problems with UTF-8 encoding. I store JSON objects, they go in as
```
JSON.SET foo . '{"label":"Gestão de Categoria"}'
```

When I return it with `JSON.GET foo`, I get 
```
"{\"label\":\"Gest\\u00c3\\u00a3o de Categoria\"}"
```

Which is interpreted as `GestÃ£o de Categoria`.

What am I doing wrong here?

**Comment by mnunberg** [comment]
I'd recommend using the `NOESCAPE` option with `JSON.GET`, e.g.

```
127.0.0.1:6379> JSON.GET foo NOESCAPE
"{\"label\":\"Gest\xc3\xa3o de Categoria\"}"
```

**Comment by mschipperheyn** [comment]
Ah thanks! Didn;t know about that option. I will see if that is supported through the node lib.
