### ISSUE TITLE
NOESCAPE in JSON.MGET

### ISSUE THREAD

**Issue by mfidemraizer** [RedisJSON/RedisJSON#120]
Hi, related to #35 

I've found that #35 was solved for JSON.GET, but in my case I require the same thing on JSON.MGET. Any chance to get the same feature in this command?

Thank you in advance

**Comment by josemanuelbadia** [comment]
+1

**Comment by nhapq** [comment]
+1

**Comment by gkorland** [comment]
Please see https://github.com/RedisJSON/RedisJSON2

**Comment by christopherhwood** [comment]
@gkorland just checking if there's an update on this. I didn't understand the please see comment.

**Comment by gkorland** [comment]
As you might noticed the module was re-written from scratch in Rust, the new version was already merged to master, this version doesn't have this issue

**Comment by mfidemraizer** [comment]
> As you might noticed the module was re-written from scratch in Rust, the new version was already merged to master, this version doesn't have this issue

Hi! I've checked out the newest version and I see that source code has no NOESCAPE option in JSON.MGET. Are you sure about this?

**Comment by gkorland** [comment]
Yes we kept it just for backward capability (has no real effect)

**Comment by mfidemraizer** [comment]
@gkorland The issue is this makes JSON.MGET unusable for latin languages (accents, tildes...):

https://stackoverflow.com/questions/62722188/parse-escaped-unicode-sequence-and-decode-it

**Comment by mfidemraizer** [comment]
@gkorland I've updated the Docker container to `edge` and still has the issue..

```
JSON.SET x . '{ "x": "Fernández" }'
JSON.GET x .
"{\"x\":\"Fern\xc3\xa1ndez\"}"
```

**Comment by gkorland** [comment]
It's how redis-cli print results by default.
```bash
$ redis-cli --raw
127.0.0.1:6379> JSON.SET x . '{ "x": "Fernández" }'
OK
127.0.0.1:6379> JSON.GET x .
{"x":"Fernández"}
```
