### ISSUE TITLE
can i run redis with redisjson on QNX platform?

### ISSUE THREAD

**Issue by xuyumm** [RedisJSON/RedisJSON#1209]
such as title, when i compile redisjson, its got error? its possible run redisjson on qnx?

**Comment by iddm** [comment]
Hi @xuyumm, thank you for asking this question.

Redis and the Redis projects do not do anything specific to prevent the work on any platform outside of Linux. However, only Linux support is claimed. QNX is quite different from Linux and doesn't really pretend to be different. It has the POSIX common ground, but its implementation is different from the Linux implementation. A thorough inspection is required to confirm whether Redisjson can be compiled and work on QNX. We do not guarantee that this will happen, and certainly cannot guarantee that we will do something about it unless it is a really easy fix. Perhaps there is already a package for QNX somewhere out there, made by someone else?

**Comment by xuyumm** [comment]
thank you very much, I will also continue to try. If there is a RedisJSON library that can work normally or cannot work on the QNX platform, I hope to receive your message. Alternatively, if there is a redisjson library that I can load, please let me try it

**Comment by iddm** [comment]
> thank you very much, I will also continue to try. If there is a RedisJSON library that can work normally or cannot work on the QNX platform, I hope to receive your message. Alternatively, if there is a redisjson library that I can load, please let me try it

Unfortunately, I am not aware of any QNX builds out there, as well as I have to say we don't build `redisjson` for QNX too, so that I cannot share with you a working library.
