### ISSUE TITLE
Get range of values?

### ISSUE THREAD

**Issue by cemremengu** [RedisJSON/RedisJSON#121]
Is it possible to use slicing operator or similar to get a range of values like

`json.get keys .rows[:10]`

If not, whats the most efficient way to get a slice of values?

**Comment by gkorland** [comment]
You might want to https://github.com/RedisJSON/RedisDoc
As part of this project we're rewriting RedisJSON in Rust and also adding full jsonpath support

**Comment by Sumit-ignistec** [comment]
after using JSONPath, the results getting first index value, is there any plan to fix this?

https://stackoverflow.com/questions/60209167/get-range-of-elements-from-redis-using-rejson

**Comment by gkorland** [comment]
@Sumit-ignistec can you please add a specific example, of what is not working?

**Comment by Sumit-ignistec** [comment]
below is the example which is pulling first index of the result, expected should be list of results

$.productList[1:7] - it should result of 7 items from array

"$.productList[?(@.brandName == 'Samsung')]" - this is also matching multiple result but its returning first index of results

**Comment by gkorland** [comment]
@Sumit-ignistec you're right we are still returning only the first result and not all of the results to maintain backward compatibility with RedisJSON 1.0.x (supported only static paths).
I just opened an issue for it https://github.com/RedisJSON/RedisJSON/issues/187

**Comment by gkorland** [comment]
@Sumit-ignistec a work around might be using the `JSON.GET`
e.g. 
```
JSON.QGET carts '@cart_id:abc' '$.productList[1:7]'
```

**Comment by Sumit-ignistec** [comment]
as i gone through the readme,  QGET  works only when you index the data, can you please help to add multiple documents in index
