### ISSUE TITLE
Why does RedisJSON not use BSON?

### ISSUE THREAD

**Issue by yangbodong22011** [RedisJSON/RedisJSON#122]
[BSON](http://bsonspec.org/) , short for Bin­ary JSON. Whether it can be used as a representation of RedisJSON on the server side, so the server only needs to store String->byte[], the client converts the data into BSON and passes it to the server, and the server returns the BSON format.

**Comment by gkorland** [comment]
Our plan is to add BSON protocol format support in our next major version (https://github.com/RedisJSON/RedisDoc).
I'm not sure we're going to change the internal representation of the data, but we'll probably going to let clients send BSON if it's easier for them

**Comment by yangbodong22011** [comment]
Thanks for your reply and such amazing rust language, the project code is much less than RedisJSON. I still have a few questions.

> Our plan is to add BSON protocol format support in our next major version (https://github.com/RedisJSON/RedisDoc).

1. I read some of the code in RedisDoc, will bson support using [bson-rs](https://github.com/zonyitoo/bson-rs)?
2. I noticed that the project is currently named RedisDoc, which means that more Doc formats (eg. yaml) will be supported later?
3. If yaml is supported, the API will be unified(eg. DOC.SET DOC.GET) or a new API will be created (eg. YAML.SET, YAML.GET etc.)

**Comment by gkorland** [comment]
>1. I read some of the code in RedisDoc, will bson support using bson-rs?

Probably

>2. I noticed that the project is currently named RedisDoc, which means that more Doc formats (eg. >yaml) will be supported later?

Most likely

>3. If yaml is supported, the API will be unified(eg. DOC.SET DOC.GET) or a new API will be created > (eg. YAML.SET, YAML.GET etc.)

My original plan was to be able to consume different docs, but consume them all in a single API like JSONPath and perhaps let the user control the returned format e.g. `json.get mykey a.b.c FORMAT BSON`

**Comment by yangbodong22011** [comment]
Thank you for your reply.
