### ISSUE TITLE
`tokio::sync::broadcast` support in async connection push senders

### ISSUE THREAD

**Issue by tanguyMichardiere** [RedisJSON/RedisJSON#1228]
Hello,

I would like to be able to use tokio's broadcast channel in a redis async connection.
For example:

```rust
let client = redis::Client::open("redis://127.0.0.1:6379?protocol=resp3").unwrap();
let (sender, receiver) = tokio::sync::broadcast::channel(16);
let config = redis::aio::connection_manager::ConnectionManagerConfig::new()
    .set_push_sender(sender);
                     ^^^^^^ expected `UnboundedSender<PushInfo>`, found `Sender<_>`
let mut connection_manager = client
    .get_connection_manager_with_config(config)
    .await
    .unwrap();
```

**Comment by iddm** [comment]
Hi @tanguyMichardiere and thank you for reporting an issue!

Could you please share how this is relevant to `RedisJSON`?

**Comment by tanguyMichardiere** [comment]
Sorry, I created this issue in the wrong repository, my mistake

**Comment by iddm** [comment]
Thanks! I think you might have wanted to create it in https://github.com/RedisLabsModules/redismodule-rs ?
