### ISSUE TITLE
storing complete json file with reJson

### ISSUE THREAD

**Issue by bsriramprasad** [RedisJSON/RedisJSON#123]
I was wondering if there is a way that I can store an entire Json file (that I am receiving from another application) against a key value?

Could not get much information from Ref: https://redislabs.com/blog/redis-as-a-json-store/

Known info:
redis-cli -x set key  </home/test.txt --> this was possible

query:
1) redis-cli -x json.set key  </home/test.json possible?
2) Is there any other way I can achieve such objective from existing reJson command set?

Kindly redirect to appropriate documentation if I missed to find such information.

**Comment by gkorland** [comment]
Isn't JSON.SET what you're looking for?
https://oss.redislabs.com/redisjson/commands/#jsonset

**Comment by bsriramprasad** [comment]
Thanks for your response.

I have tried (as mentioned in original query) like this
--> redis-cli -x json.set key </home/test.json which gave me "ERR wrong number of arguments for 'JSON.SET' command" and quoted analogous command that works for a simple file storage.

Alternatively, I tried below code with hiredis client interface called from within my program, but I am getting similar error "ERR new objects must be created at the root"

Read the file content 
--> fread (json_file_buf, 1, st.st_size, fp) ; // file size read with fstat

Pass the file read string buffer to json set command
--> redisResp = redisCommand(redisCtx,"JSON.SET redis_jsonin object %s", json_file_buf);

So I am sure there is some gap in my understanding of json.set and hence this query.

**Comment by bsriramprasad** [comment]
Ref: https://redislabs.com/blog/redis-as-a-json-store/ json.set says "Redis keys the path must be the root"

1) redis-cli -x json.set key **.** </home/test.json worked. (see the highlighted period in command)
2) Pass the file read string buffer to json set command
    --> redisResp = redisCommand(redisCtx,"JSON.SET redis_jsonin . %s", json_file_buf); worked.

So can I assume that "." is the default "root" object for new key <--> json mapping?

**Comment by gkorland** [comment]
> Thanks for your response.
> 
> I have tried (as mentioned in original query) like this
> --> redis-cli -x json.set key </home/test.json which gave me "ERR wrong number of arguments for 'JSON.SET' command" and quoted analogous command that works for a simple file storage.

The following should work (don't forget the `.` path)
```
redis-cli JSON.SET a . </home/test.json
```

**Comment by gkorland** [comment]
@bsriramprasad can I close the issue?

**Comment by bsriramprasad** [comment]
Yes, thank you. I have another question regarding json.get command and I will ask in a separate thread.
