### ISSUE TITLE
How to use json.get on json fields with "@" included in the field

### ISSUE THREAD

**Issue by bsriramprasad** [RedisJSON/RedisJSON#124]
E.g. JSON file which hold some kind of an attribute field I guess (another application generates this kind of json for my usage)

JSON schema that generates the object
{
  "@test": {
    "type": "string"
  }
}

JSON object that gets validated against schema
{
	"@test": "test123"
}

Note:
1) This is a valid JSON as validated from https://jsonlint.com/
2) Schema and objects validated at https://www.jsonschemavalidator.net/

I tried the below commands but did not seem to go through

127.0.0.1:6379> JSON.set test_json . '{"@test": "test123"}'
OK
127.0.0.1:6379> JSON.get test_json
"{\"@test\":\"test123\"}"
127.0.0.1:6379> JSON.get test_json .test
(error) ERR key 'test' does not exist at level 0 in path
127.0.0.1:6379> JSON.get test_json .@test
(error) ERR Search path error at offset 2: an identifier can only begin with a letter, a dollar sign or an underscore - use bracket notation for anything else

Can you please let me know what am I missing here?

**Comment by gkorland** [comment]
It seems like according to jsonpath `@` is used for other things

`@` :  The current node being processed by a filter predicate.

**Comment by bsriramprasad** [comment]
So whats the way to read such elements starting with "@" - I am not sure if this is a remnant from older json schema versions that allowed element to have such characters, but for me reading that element was important and hence this query. 

If not possible, need to find an alternative - check with app developer if schema can be modified to generate object without "@". Thanks in advance.

**Comment by bsriramprasad** [comment]
from whatever code I can see, it is getting created as a string object only 

#include <json-glib/json-glib.h>
json_object_set_string_member (rootObj, "@test", "test123");

Ref for API : https://developer.gnome.org/json-glib/stable/json-glib-JSON-Object.html

**Comment by gkorland** [comment]
I'm not sure I understand the last comment, is it something you can workaround?

**Comment by bsriramprasad** [comment]
No, I cannot work around unless I fiddle with the schema that generates that object - which at this point I am not sure if I am allowed to do so, as its an external module is generating such "special" json object :-)

**Comment by gkorland** [comment]
@bsriramprasad RedisJSON2 was merged to master and now support 
`json.get test_json '["@test"]'`
