### ISSUE TITLE
Will ReJSONBenchmark be open source?

### ISSUE THREAD

**Issue by yangbodong22011** [RedisJSON/RedisJSON#126]
I noticed that ReJSONBenchmark will be open source (https://oss.redislabs.com/redisjson/performance/) , is there a plan?

I want to use it to test the performance of RedisJSON under large data sets.

**Comment by itamarhaber** [comment]
Hello @yangbodong22011 

Regrettably, I never got to finish the work on that project and I'm afraid that it is forever lost in the digital afterworld. The good news is that we are reimplementing it so hopefully it will be ready soon.

**Comment by yangbodong22011** [comment]
@itamarhaber Thank you very much for your reply, I am looking forward to the day it was opened source.
