### ISSUE TITLE
Starting Redis from 33MB RDB file takes more than 2 minutes

### ISSUE THREAD

**Issue by andybets** [RedisJSON/RedisJSON#127]
I'm receiving the redis.exceptions.BusyLoadingError for around 2 minutes after startup from a 33MB RDB file. Most of the data is in a single large JSON key (maybe relevant?).

It seems to shutdown and save the RDB pretty much instantly.  I tried disabling compression and checksum, but it made no discernable difference.

**Comment by gkorland** [comment]
Can you share the RDB? Or try with https://github.com/RedisJSON/RedisJSON2

**Comment by andybets** [comment]
Sure... here it is:
[dump.rdb.tar.gz](https://github.com/RedisJSON/RedisJSON/files/3811200/dump.rdb.tar.gz)

Thanks.

I'm using docker, and couldn't seem to pull the RedisJSON2 image earlier.

**Comment by andybets** [comment]
I tried RedisJSON2, but the Python client is giving me `redis.exceptions.ResponseError: Err: wrong static path` when setting to a non-root path. So I can't load up the data to check whether the problem is present.

**Comment by andybets** [comment]
It does seem to work as expected in RedisJSON2 without this loading issue, which is good. But as above, the bracket notation isn't working properly, see https://github.com/RedisJSON/RedisJSON2/issues/72

**Comment by gkorland** [comment]
RedisJSON2 was merged to Master
