### ISSUE TITLE
Prebuilt option for supported OS/Versions in github releases?

### ISSUE THREAD

**Issue by The-Lord-of-Owls** [RedisJSON/RedisJSON#1275]
It would be extremely convenient having an option for a prebuilt module release per supported OS in the releases page.

It would make it rather quick not having to deal with installing build tools and compiling it(not just for those who don't know how but for those working with tight disk space already without an option for increasing it)

**Comment by LiorKogan** [comment]
With the GA release of Redis CE 8.0, all Redis CE binary distributions will be available with RediSearch, RedisJSON, RedisTimeSeries, and RedisBloom available as an integral part of Redis, so you won't need to download and build modules individually anymore.

**Comment by The-Lord-of-Owls** [comment]
Is there a location to se when that will be released? I checked after your response but I couldn't find anything on the redis website and only saw 7.4 was available atm

**Comment by LiorKogan** [comment]
See [GitHub release notes for Redis 8.0-M01](https://github.com/redis/redis/releases/tag/8.0-m01)

> Redis 8.0 introduces new data structures: JSON, time series, and 5 probabilistic data structures (previously available as separate Redis modules) and incorporates Redis scalable query engine (including vector search).

> 8.0-M01 is available as a Docker image and can be downloaded from [Docker Hub](https://hub.docker.com/_/redis). Additional distributions will be introduced in upcoming pre-releases.

**Comment by The-Lord-of-Owls** [comment]
I guess I'll have to wait till they move 8.0 to full release then since all they have is a docker image for a pre-release. I also didn't see a notice on when thats planned so I guess till then JSON.parse and JSON.stringify will have to do to get around it
