### ISSUE TITLE
Why are there extra double quotes?

### ISSUE THREAD

**Issue by xiaopingfeng** [RedisJSON/RedisJSON#129]
![image](https://user-images.githubusercontent.com/19268342/68758766-63810300-0649-11ea-9541-e2352137c3d2.png)

redis 4.0.14  and  redis 5.0.6
RedisJSON 1.0.4

**Comment by xiaopingfeng** [comment]
JSON.GET d .foo
"\"bar\""
![image](https://user-images.githubusercontent.com/19268342/68759647-0a19d380-064b-11ea-8ce8-5e56f3c34d46.png)

**Comment by itamarhaber** [comment]
The "extra" quotes are redis-cli's way of saying that the reply is a string. You can use `redis-cli --raw` to disable this and the escaping.

**Comment by xiaopingfeng** [comment]
Thanks
