### ISSUE TITLE
Why doesn't JSON.GET * work in a cluster? 

### ISSUE THREAD

**Issue by xtianus79** [RedisJSON/RedisJSON#133]
sorry maybe this is a redis cluster notation thing but I am getting (nil) when using JSON.GET * in my cli via a cluster configuration?

**Comment by itamarhaber** [comment]
Hello @xtianus79 

`JSON.GET` should work in a cluster configuration like any other command. You do, however, need to provide it with a key name, not a pattern. Unless you have a JSON key called "*", it will return (nil) for not found.

**Comment by xtianus79** [comment]
I figured out I need to use scan instead
