### ISSUE TITLE
Mocking ReJSON in a mock redis server

### ISSUE THREAD

**Issue by kpiyush17** [RedisJSON/RedisJSON#134]
Is there any way to mock rejson in a mocked Redis server in golang?

I am able to mock a Redis server using something like this using [miniredis](https://github.com/alicebob/miniredis) and [redismock](https://github.com/elliotchance/redismock)
```
func newTestRedis() (*redismock.ClientMock, *redis.Client) {
	mr, err := miniredis.Run()
	if err != nil {
		panic(err)
	}
	client := redis.NewClient(&redis.Options{
		Addr: mr.Addr(),
	})
	return redismock.NewNiceMock(client.Client), client
}
```

It is able to do normal Redis operations like Get, Set but since I am using ReJSON module, I am not able to run any ReJSON commands on that. Using [this](https://github.com/nitishm/go-rejson) golang library for ReJSON.

Thanks

**Comment by itamarhaber** [comment]
Hello @kpiyush17 

I really don't know, but I think it depends on https://github.com/nitishm/go-rejson supporting being mocked. I recommend you ask this question [there](https://github.com/nitishm/go-rejson).
