### ISSUE TITLE
Details on the RedisJSON binary format

### ISSUE THREAD

**Issue by davidglavas** [RedisJSON/RedisJSON#136]
Is there a description of how exactly RedisJSON stores the plain-text JSON files? Postgres has a desctiption of their binary json format in the [comments](https://github.com/postgres/postgres/blob/fe233366f2e3ca44609c805ce0604c1e2122c3f9/src/include/utils/jsonb.h#L82), same for [MySQL ](https://github.com/mysql/mysql-server/blob/ea7d2e2d16ac03afdd9cb72a972a95981107bf51/sql/json_binary.h#L33). 

Is there something similar for RedisJSON? For example, why exactly is "Searching for object keys O(N)"?

**Comment by itamarhaber** [comment]
Hello @davidglavas 

AFAIR no, there isn't. The following is what happens in this module (RedisJSON2 is a different story) - this is basically what's going on in https://github.com/RedisJSON/RedisJSON/blob/master/src/object.h:
1. Every doc is made up of one or more nodes, forming a tree-like data structure.
2. Nodes can be of different types, i.e. string, integer, array, object...
3. The object type is is implemented using a vector, so to search for a key in an object is O(N).

In this version, the memory representation and the serialized persistence form are almost the same.  Future versions may replace this implementation.

**Comment by davidglavas** [comment]
So a plain text JSON document becomes an object, which is a sequence (vector) of nodes, nodes can be of type: null, string, number, integer, boolean, dict, array, keyval.  

So an object can't contain an object, you use the term object to describe only the entire serialized plain text JSON document? Sub-documents are then represented as dict and not object?

**Comment by itamarhaber** [comment]
> So an object can't contain an object, you use the term object to describe only the entire serialized plain text JSON document?

I've used the term object instead of dict, sorry.

>  Sub-documents are then represented as dict and not object?

Yep.

Disk storage of the RedisJSON object (i.e. the deserialized, non-textual, tree-like data structure) is implemented in https://github.com/RedisJSON/RedisJSON/blob/master/src/object_type.c. Note that the code delegates the actual writing to Redis, so how the data looks like from that point onwards is outside the scope and control of the module. You could dig into Redis' internals to learn how it manages persistence, but the real question is why would you want to read the data from there.

Also note that the way data is stored on disk is an implementation detail, not a contract, and could change between versions.

**Comment by davidglavas** [comment]
@itamarhaber I see, thank you for the clarifications.

> ...(RedisJSON2 is a different story)

Why? Are the following things true for both RedisJSON1 and 2:

- Given a key (always a string), accessing an element in a dict that contains n elements (key-value pairs) takes O(n) time? 
- Given an index (integer), accessing an element in an array that contains n elements takes O(1) time? 
- During serialization (converting a plain-text JSON string to a RedisJSON object) no sorting or anything else fancy happens?

**Comment by itamarhaber** [comment]
> Why?

Because it uses a different internal storage scheme that is implemented by an external crate iiuc - @gkorland please correct me if I'm wrong here.

As for the truths, they hold for RedisJSON1.

**Comment by gkorland** [comment]
RedisJSON 2.0.6+ is using the [ijson](https://docs.rs/ijson/latest/ijson/) crate.
