### ISSUE TITLE
How to: Serialize, Deserialize, Access values

### ISSUE THREAD

**Issue by davidglavas** [RedisJSON/RedisJSON#137]
I'm trying to perform the following 3 operations:

 - serialize a plaintext json document (plaintext json -> redisjson)
 - access values in the redisjson document
 - deserialize a redisjson document (redisjson -> plaintext json)

For example:

    #include <iostream>
    #include <string>    
    
    int main(int, char**) {

       // valid plaintext JSON document
       std::string testJSON = "{ \"id\" : { \"numID\" : 12345, \"strID\" : \"onetwothreefourfive\", \"doubleID\" : 1.2345}, \"hello\" : \"world\", \"age\" : 42, \"cats\" : [ \"first cat\", \"second cat\", \"third cat\" ] }";

       // TODO somehow use redisjson functions to perform the 3 operations:

       // 1. Serialize
       redisjsonObject serializedDoc = redisjson.serialize(testJSON);

       // 2. Access values
       // access the top-level value associated with key "age" (42 in this case)
       int age = serializedDoc.accessValue("age");

       // 3. Deserialize
       std::string originalJSON = redisjson.deserialize(serializedDoc);

       std::cout << originalJson << std::endl;
    }

Is there a straightforward way to do these 3 operations for any given plaintext JSON document?

**Comment by itamarhaber** [comment]
Hello @davidglavas 

To use this module's functionality, you need to have it loaded to a Redis server and access it via a CPP client. AFAIK, there are no specialized CPP clients for RedisJSON, but you can use any of the ones that allow invoking generic/custom commands (I would recommend https://github.com/sewenew/redis-plus-plus#generic-command-interface if only for its extremely responsive and knowledgable author /cc @sewenew).

If you're looking to use the module outside of Redis, perhaps as a library in your code, I'm positive that it can be done but I wouldn't call it straightforward.

**Comment by sewenew** [comment]
Hi @itamarhaber 

Thanks for your recommendation!

@davidglavas If you have any problem on [redis-plus-plus](https://github.com/sewenew/redis-plus-plus), feel free to [let me know](https://github.com/sewenew/redis-plus-plus/issues) :)

Regards
