### ISSUE TITLE
JSON.ARRINDEX is not working even with scalar values

### ISSUE THREAD

**Issue by pavelsr** [RedisJSON/RedisJSON#138]
[JSON.ARRINDEX](https://oss.redislabs.com/redisjson/commands/#jsonarrindex) must return `10` but returns `(integer) -1` :

```
127.0.0.1:6379> JSON.GET d [10]
"{\"code\":\"AAL\",\"coordinates\":{\"lat\":57.028811,\"lon\":9.917771},\"country_code\":\"DK\",\"name\":\"\xe3\x82\xaa\xe3\x83\xbc\xe3\x83\xab\xe3\x83\x9c\xe3\x83\xbc\",\"name_translations\":{\"en\":\"Aalborg\"},\"time_zone\":\"Europe/Copenhagen\"}"
127.0.0.1:6379> JSON.ARRINDEX d .[*].code AAL
(integer) -1
```

Or [path syntax](https://oss.redislabs.com/redisjson/path/) like `.[*].code` is not supported ?

I tried this with RedisJSON and RedisJSON2 both.

**Comment by itamarhaber** [comment]
Hello @pavelsr 

RedisJSON does not support searching and filtering, so this won't work in it. RedisJSON2 does provide such features via the commands:

```
JSON.INDEX ADD <index> <field> <path>
JSON.QGET <index> <query> <path>
```

**Comment by gkorland** [comment]
@pavelsr JSON.ARRINDEX is currently only supporting using json-scalar.
Will a similar extension work for you?

```
127.0.0.1:6379> json.set user1 . '{"last":"Joe", "first":[{"code":1}, {"code":2}]}' 
OK
127.0.0.1:6379> json.arrindex user1 $.first "{\"code\":2}"
(integer) 1
```

**Comment by pavelsr** [comment]
@gkorland no, this not working for me 

[redislabs/rejson](https://hub.docker.com/r/redislabs/rejson) image:

```
127.0.0.1:6379> json.set user1 . '{"last":"Joe", "first":[{"code":1}, {"code":2}]}'
OK
127.0.0.1:6379> json.arrindex user1 $.first "{\"code\":2}"
(error) ERR key '$' does not exist at level 0 in path
127.0.0.1:6379> json.arrindex user1 .first "{\"code\":2}"
(integer) -1
```

[redislabs/redisjson2](https://hub.docker.com/r/redislabs/redisjson2) image:

```
127.0.0.1:6379> json.set user1 . '{"last":"Joe", "first":[{"code":1}, {"code":2}]}'
OK
127.0.0.1:6379> json.arrindex user1 $.first "{\"code\":2}"
(integer) -1
```

**Comment by pavelsr** [comment]
@itamarhaber can you provide an example or correct mine?

I tried:

```
127.0.0.1:6379> json.set user1 . '{"last":"Joe", "first":[{"code":1}, {"code":2}]}' 
OK
127.0.0.1:6379> JSON.INDEX ADD code_index code .first
OK
127.0.0.1:6379> JSON.QGET code_index 1
"{}"
127.0.0.1:6379> JSON.QGET code_index 1 .first
"{}"
```

**Comment by gkorland** [comment]
>@gkorland no, this not working for me
I know, I asked will such extension will fit your needs?

**Comment by pavelsr** [comment]
@gkorland yes, if it was working it fits :)

**Comment by gkorland** [comment]
https://github.com/RedisJSON/RedisJSON2/pull/81

**Comment by gkorland** [comment]
https://github.com/RedisJSON/RedisJSON/pull/178
https://github.com/RedisJSON/RedisJSON/pull/182
