### ISSUE TITLE
Filter expression gets error 'an identifier can only begin with a letter'

### ISSUE THREAD

**Issue by FredericSavard** [RedisJSON/RedisJSON#140]
Given:
redis-cli json.set "ABC-YZ-A12B34C5" "." "[{\"id\":\"ABC-YZ-A12B34C5\",\"version\":1},{\"id\":\"ABC-YZ-A12B34C5\",\"version\":2},{\"id\":\"ABC-YZ-A12B34C5\",\"version\":3}]" "NX"

This is successful:
redis-cli json.get ABC-YZ-A12B34C5

This is NOT:
redis-cli json.get ABC-YZ-A12B34C5 $.[?(@.version==2)]

It gets this error:
(error) ERR Search path error at offset 3: an identifier can only begin with a letter, a dollar sign or an underscore - use bracket notation for anything else

Monitor shows:
[0 127.0.0.1:59638] "json.get" "ABC-YZ-A12B34C5" "$.[?(@.version==2)]"

Please help.

**Comment by gkorland** [comment]
Are you using https://github.com/RedisJSON/RedisJSON or  https://github.com/RedisJSON/RedisJSON2?

**Comment by FredericSavard** [comment]
I am using  https://github.com/RedisJSON/RedisJSON

**Comment by gkorland** [comment]
So that is the issue, RedisJSON (1) doesn't support this syntax. RedisJSON2 supports full JSONPath.

**Comment by FredericSavard** [comment]
I see. Until RedisJSON2 is launched, would you see a quick way to redesign my model so that I can search by identifier (returns the array), and also search by version (no need for jsonpath, use the same model as above)?

**Comment by gkorland** [comment]
@FredericSavard please notice the master is already supporting full JSONPath
```
