### ISSUE TITLE
Inconsistent TTL reset with JSON.SET

### ISSUE THREAD

**Issue by nishantgeorge** [RedisJSON/RedisJSON#141]
The Redis [SET](https://redis.io/commands/set) command always resets the TTL of the key on a successful write.

The [JSON.SET](https://oss.redislabs.com/redisjson/commands/#jsonset) command only seems to do this when setting the root path of the JSON (`.`). 

```redis-cli
127.0.0.1:6379> JSON.SET json . '{"aaa": "aaa"}'
OK
127.0.0.1:6379> EXPIRE json 3600
(integer) 1
127.0.0.1:6379> JSON.SET json .aaa '"bbb"'
OK
127.0.0.1:6379> TTL json
(integer) 3581
127.0.0.1:6379> JSON.SET json . '"ccc"'
OK
127.0.0.1:6379> TTL json
(integer) -1
127.0.0.1:6379> 
```

I think that the correct behaviour should be to either always reset the TTL (like the SET command) or to never do it.

**Comment by itamarhaber** [comment]
Hi @nishantgeorge 

I understand the argument but would like to present another view: nested Redis data types (i.e. anything but strings) do not reset the TTL when working on their elements/members. IIRC that was my reasoning for the current behavior - nested operations do not touch TTL but an entire replace (i.e. root operation) is equivalent to deleting/creating the entire thing so the TTL is also gone.

In any case, this can be changed in the upcoming v2 if the devs/users want to.

**Comment by gkorland** [comment]
@nishantgeorge please notice the new redisjson code was merged to master.
```
127.0.0.1:6379> JSON.SET json . '{"aaa": "aaa"}'
OK
127.0.0.1:6379> EXPIRE json 3600
(integer) 1
127.0.0.1:6379> JSON.SET json .aaa '"bbb"'
OK
127.0.0.1:6379> TTL json
(integer) 3594
127.0.0.1:6379> JSON.SET json . '"ccc"'
OK
127.0.0.1:6379> TTL json
(integer) 3586
127.0.0.1:6379> 
```
