### ISSUE TITLE
Bracket notation no longer supported?

### ISSUE THREAD

**Issue by andybets** [RedisJSON/RedisJSON#149]
When I try the following is Redis Commander:
`JSON.SET "DATA" '["ID7"]' "{}"`

...I get:
`"Err: wrong static path"`

Has bracket notation support been dropped in 2?

**Comment by yoav-steinberg** [comment]
Note we should also return the correct error when trying to `JSON.SET` an invalid index in an array:
```
127.0.0.1:6379> JSON.set x $ [{},{}]
OK
127.0.0.1:6379> JSON.set x $[3] {}
(error) Err: wrong static path
```
In v1.0 would have returned the following, more accurate, error:
`ERR index '[2]' out of range at level 0 in path` or similar

**Comment by yoav-steinberg** [comment]
The basic problem is here:
https://github.com/RedisJSON/RedisJSON/blob/abc41453bede4ddc1ceb51585e3f98ff3c2e2540/src/nodevisitor.rs#L31-L48
where we don't regard bracket notation as a `Valid` explicit path.
And also here:
https://github.com/RedisJSON/RedisJSON/blob/abc41453bede4ddc1ceb51585e3f98ff3c2e2540/src/redisjson.rs#L112-L115
Where we don't expect bracket notation and use simple string manipulation to get the object's key.

**Comment by gkorland** [comment]
The error was fixed:

```bash
127.0.0.1:6379> JSON.set x $ [{},{}]
OK
127.0.0.1:6379> JSON.set x $[1] {}
OK
127.0.0.1:6379> JSON.set x $[3] {}
(error) ERR array index out of range
```
