### ISSUE TITLE
Add `JSON.QSET <index> <query> <path> <json> [NX | XX]`

### ISSUE THREAD

**Issue by gkorland** [RedisJSON/RedisJSON#154]

**Comment by yoav-steinberg** [comment]
Regarding `<path>` option here there are two ways to go:
1. Support only static paths like in `JSON.SET`, this makes it compatible with `JSON.SET` and supports simple code reuse.
1. Support any jsonpath, this means more complex updates are possible and we can't reuse code.
Does this make sense? Which should we aim for?

**Comment by gkorland** [comment]
I think for the first stage we should go with 1, and when we define the semantic for json.set also extend here

**Comment by yoav-steinberg** [comment]
> I think for the first stage we should go with 1, and when we define the semantic for json.set also extend here

Very well. This makes things simpler.

Another question: `JSON.SET` returns `OK` in case we set a value and _null_ in case no value was set. When implementing `JSON.QSET` we can have either the same logic or return an integer indicating the number of keys which were affected. If we go for the integer then what should we return if no keys are affected null or 0?
My thought is that keeping in line with other redis commands and also the most practical response is an integer with the number of affected keys and 0 representing no keys affected.

**Comment by gkorland** [comment]
> My thought is that keeping in line with other redis commands and also the most practical response is an integer with the number of affected keys and 0 representing no keys affected.

Agree
