### ISSUE TITLE
Replication

### ISSUE THREAD

**Issue by bonald** [RedisJSON/RedisJSON#166]
Hello,
I'm using this module with a simple master slave replication.
Initial sync is working but updates are not replicated to slave instance. I tried the NOCACHE option without success.
Any idea?

**Comment by bonald** [comment]
Actually, I'm using redisjson2, the nocache does nothing

**Comment by gkorland** [comment]
@bonald thanks for reporting, you're right NOCACHE was not implemented in master and I'm not sure it CACHE will be implemented on master, we didn't see a major performance improvement that will convince us to re-add it.  Do you have a use case for it?
Anyway, it should be related to replication, we'll check the replication.

**Comment by gkorland** [comment]
@bonald I just submitted a PR for the fix, can you please try this branch https://github.com/RedisJSON/RedisJSON/tree/replicate?

**Comment by bonald** [comment]
Hi, I just tried it and now I get (nil) when doing a json.get
It looks like no data is being replicated. Previously initial sync was ok

**Comment by bonald** [comment]
Info from master side

# Replication
role:master
connected_slaves:1
slave0:ip=10.0.0.3,port=6381,state=online,offset=1820,lag=0
master_replid:4a3dbe00ceed85db85c4743afc40f86687182110
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:1820
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:1
repl_backlog_histlen:1820

**Comment by bonald** [comment]
My bad , git cloned master . brb

**Comment by bonald** [comment]
OK! It's replicating fine now. Thanks!
