### ISSUE TITLE
JSONSet is not working with path

### ISSUE THREAD

**Issue by esker** [RedisJSON/RedisJSON#172]
I'm trying to call an object which is in my json as I can call it using the JSON path in the redis cli
.object'["id"]'. But when I try to JSONSet or JSONGet in my code using the same path I receive the following error: "ERR Search path error at offset 14: an identifier can only contain letters, digits, dollar signs or underscores - use bracket notation for anything else"

Any tips to how I can fix this?

**Comment by gkorland** [comment]
@esker what was the issue, perhaps it's something we need to better document?

**Comment by esker** [comment]
So sorry, I wanted to post this question on a different Library not issue with RedisJSON. Thanks for the quick response.
