### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by Blastwaive** [RedisJSON/RedisJSON#173]
I have pulled down the module, and when I run "make" I get the following error:

root@Rodimus:~/RedisJSON# make
make -C ./src all

make[1]: Entering directory '/root/RedisJSON/src'
make[1]: *** No rule to make target 'all'.  Stop.
make[1]: Leaving directory '/root/RedisJSON/src'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2
root@Rodimus:~/RedisJSON#

I've tried this in Ubuntu (Through WSL) as well as Fedora 32 and I get the same error.  Can somoene please assist?

**Comment by gkorland** [comment]
@Blastwaive sorry to confusion, we're working on fixing the documentation.
Notice, these build instruction are referring to the GA version [1.0.4](https://github.com/RedisJSON/RedisJSON/releases/tag/v1.0.4). 
You should checkout the 1.0 branch `git checkout 1.0` before calling `make`.
To build the master branch you need to call `cargo build --release`

**Comment by gkorland** [comment]
@Blastwaive did you manage? Can I close this issue?

**Comment by readingtype** [comment]
Please do update the docs asap. It took me a while to find this ticket and to discover that I needed to check out a branch. I cannot build from master on Ubuntu 18.04 which is fine if that's something I shouldn't expect to be able to do, but that I can do if I use a branch :-) Thanks.

**Comment by gkorland** [comment]
not relevant since version 2.0
