### ISSUE TITLE
V2 bracket notation support

### ISSUE THREAD

**Issue by kdojeteri** [RedisJSON/RedisJSON#176]
Hello, I'm trying to migrate to redis json v2, but it seems that one feature is missing or purposefully left out. In v1 (currently avaliable in docker `redislabs/rejson:latest`) I can set any key using square brackets like so:
```
127.0.0.1:6379> JSON.SET root . "{}"
OK
127.0.0.1:6379> JSON.SET root "['Frederick']" "{}"
OK
127.0.0.1:6379> JSON.GET root "Frederick"
"{}"
```
Using what's currently in `master` I can't replicate that same thing (with or without using `$`):
```
>> JSON.SET root $ "{}"
"OK"
>> JSON.SET root "$['Frederick']" "{}"
(error) Err: wrong static path
>> JSON.GET root "$.Frederick"
(error) path does not exist
```
```
>> JSON.SET root . "{}"
"OK"
>> JSON.SET root "['Frederick']" "{}"
(error) Err: wrong static path
>> JSON.GET root "Frederick"
(error) path does not exist
```
Backstory: My keys are dynamic and I can't rule out the option that one of them will contain a `.` or a space. Therefore, in v1, i transformed all keys into bracket notation (using JS's JSON.stringify) so that `whatev"er key.I like` becomes `["whatev\"er key.I like"]`.

Is this backward compatibility break intentional? Is there currently a way to achieve the same effect?

**Comment by gkorland** [comment]
duplicate #149

**Comment by whoisteri** [comment]
Just to re-iterate on my last question: Is there currently a way to have a key contain a `.`? If not, that breaks compatibility not with just v1, but with JSON as a whole.
