### ISSUE TITLE
standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by xxalfa** [RedisJSON/RedisJSON#191]
standard_init_linux.go:211: exec user process caused "exec format error"

- Hardware: Raspberry Pi 4 with 4 GB
- Operating system: Ubuntu Server 20.04 (5.4.0-1011-raspi)

When I try to start rejson, I get the error above. The normal redis works as expected.

```bash
docker run --rm --interactive --tty \
--name rejson \
--env REDIS_PASSWORD=SecretString \
--publish 0.0.0.0:6379:6379/tcp \
--volume redis-data:/data \
--detach redislabs/rejson:latest \
/bin/sh -c 'redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}'
```
```php
<?php
extension_loaded( 'redis' ) or trigger_error( 'The redis extension is required.', E_USER_ERROR );
$redis = new Redis();
$redis->connect( 'sv3', 6379 );
$redis->auth( 'SecretString' );
$redis->ping() or trigger_error( 'The redis service not available.', E_USER_ERROR );
?>
```

**Comment by gkorland** [comment]
notice it seems like you're running two redis server on the same port, the second should fail.

**Comment by xxalfa** [comment]
> 
> 
> notice it seems like you're running two redis server on the same port, the second should fail.

You get me wrong I only want to start the rejson, I get an error. But it works to start the normal redis.

**Comment by gkorland** [comment]
Did you try to build the module on arm64?

**Comment by xxalfa** [comment]
[build](https://xalpha.lima-city.de/5ecbf699ca6c8.png)

**Comment by xxalfa** [comment]
Are the error messages helpful?

**Comment by gkorland** [comment]
@xxalfa is seems like an issue with Rust type mapping see https://github.com/rust-lang/rust/issues/60226

**Comment by gkorland** [comment]
I think that should fix it https://github.com/RedisLabsModules/redismodule-rs/pull/84

**Comment by xxalfa** [comment]
There was another error when creating the build, which did not abort the process.

[build](https://xalpha.lima-city.de/5ecdeaca81354.png)

**Comment by xxalfa** [comment]
I was able to do the build successfully. Case closed.
