### ISSUE TITLE
ReJSON + Streams = ReJSON Streams

### ISSUE THREAD

**Issue by shaqarava** [RedisJSON/RedisJSON#196]
Streams are awesome. ReJSON is awesome. I find myself wishing I could store rejson objects in streams. Of course there are ways to use streams alongside rejson but think of how great it would be to do `JSON.XADD mystream * '{"foo": "bar", "ans": 42, "parent": {"foo2": "bar2"}}'`. This is a feature request for that.

Of course all rejson features wouldn't need to be implemented in it since a stream item is only set once and not modified. Searching around I see there are some radix tree libs for Rust. Idk Rust or I'd contribute.

**Comment by itamarhaber** [comment]
Hello @shaqarava 

That's an interesting feature. My immediate question is, well, why? The reasoning is that streams are immutable in terms of message data and are poised as an ingress/intermediate/egress log, whereas RedisJSON is aimed at efficiently accessing the document's elements for read and **write**.

**Comment by shaqarava** [comment]
> Hello @shaqarava
> 
> That's an interesting feature. My immediate question is, well, why? The reasoning is that streams are immutable in terms of message data and are poised as an ingress/intermediate/egress log, whereas RedisJSON is aimed at efficiently accessing the document's elements for read and **write**.

You're right as long as there's no max field length. It only came to mind because I was having trouble flattening and passing around some data in streams. I wound up getting it working though by packing it all into 1 field rather than try flattening across them. Barring any further gotchas, there's no need.

**Comment by jamesarosen** [comment]
> I was having trouble flattening and passing around some data in streams

To me, this is the most important reason. Stream payloads must be `{string: string, string: string, …}`. That imposes a few limitations for event-based systems:

1. explicit nulls, arrays, nested objects, numbers, and Booleans must all be string-encoded, possibly as JSON
2. it's difficult to enforce a schema for events
3. a client that cares only about a small portion of an event payload must deserialize the entire payload

The more of this we can move into the stream, the more reliable our event-based systems will be.
