### ISSUE TITLE
Compile warnings and failure to load module in arm7l environment

### ISSUE THREAD

**Issue by jroberts235** [RedisJSON/RedisJSON#20]
Build phase:

/home/pi/docker/armh-redis_server/lib/rejson/src/object.c: In function ‘Node_Print’:
/home/pi/docker/armh-redis_server/lib/rejson/src/object.c:507:13: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘int64_t’ [-Wformat=]
             printf("%ld", n->value.intval);
             ^
/home/pi/docker/armh-redis_server/lib/rejson/src/object.c: In function ‘Node_Serializer’:
/home/pi/docker/armh-redis_server/lib/rejson/src/object.c:598:57: warning: ‘curr_entries’ may be used uninitialized in this function [-Wmaybe-uninitialized]
                     _serializerPush(&stack, curr_entries[curr_index]);
                                                         ^
cc -I"/home/pi/docker/armh-redis_server/lib/rejson/src" -I""/home/pi/docker/armh-redis_server/lib/rejson/src/../deps"/jsonsl"  -I""/home/pi/docker/armh-redis_server/lib/rejson/src/../deps"/RedisModuleSDK/rmutil" -Wall -g -ggdb -O2 -fPIC -std=gnu99  -D_GNU_SOURCE   -c -o /home/pi/docker/armh-redis_server/lib/rejson/src/object_type.o /home/pi/docker/armh-redis_server/lib/rejson/src/object_type.c

Runtime:
Redis version=3.9.103, bits=32

1:M 13 May 00:07:06.920 # Module /usr/local/lib/rejson.so failed to load: /usr/local/lib/rejson.so: undefined symbol: __aeabi_uldivmod
1:M 13 May 00:07:06.920 # Can't load module from /usr/local/lib/rejson.so: server aborting

Is this related to Integer Sizes and typing differences between i386 64 and arm7l ?
Can you offer a fix?

**Comment by itamarhaber** [comment]
Thank you for reporting, very exciting to see this module being run on exotic platforms.

@jroberts235 the warnings are ok to ignore for now, but the missing symbol is indeed a problem. Do you know of a way to reproduce this w/o having an pi/ARM device?

**Comment by gkorland** [comment]
@jroberts235 did you manage to overcome the issue?

**Comment by simonprickett** [comment]
I just tried this on a Raspberry Pi 3 with the current Raspbian Stretch Lite image.  I was able to build both redis and redisjson from source without modification, and add the redisjson module to `redis.conf` and start the server successfully and interact with the module:

```
$ /usr/bin/redis-cli --raw
127.0.0.1:6379> JSON.SET doc . '{ "foo": "bar", "baz": 42 }'
OK
127.0.0.1:6379> JSON.GET doc .foo
"bar"
127.0.0.1:6379>
```

I'm on armv7l:

```
$ uname -a
Linux protocoltest 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux
```

**Comment by dpate117** [comment]
> Build phase:
> 
> /home/pi/docker/armh-redis_server/lib/rejson/src/object.c: In function ‘Node_Print’:
> /home/pi/docker/armh-redis_server/lib/rejson/src/object.c:507:13: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘int64_t’ [-Wformat=]
> printf("%ld", n->value.intval);
> ^
> /home/pi/docker/armh-redis_server/lib/rejson/src/object.c: In function ‘Node_Serializer’:
> /home/pi/docker/armh-redis_server/lib/rejson/src/object.c:598:57: warning: ‘curr_entries’ may be used uninitialized in this function [-Wmaybe-uninitialized]
> _serializerPush(&stack, curr_entries[curr_index]);
> ^
> cc -I"/home/pi/docker/armh-redis_server/lib/rejson/src" -I""/home/pi/docker/armh-redis_server/lib/rejson/src/../deps"/jsonsl" -I""/home/pi/docker/armh-redis_server/lib/rejson/src/../deps"/RedisModuleSDK/rmutil" -Wall -g -ggdb -O2 -fPIC -std=gnu99 -D_GNU_SOURCE -c -o /home/pi/docker/armh-redis_server/lib/rejson/src/object_type.o /home/pi/docker/armh-redis_server/lib/rejson/src/object_type.c
> 
> Runtime:
> Redis version=3.9.103, bits=32
> 
> 1:M 13 May 00:07:06.920 # Module /usr/local/lib/rejson.so failed to load: /usr/local/lib/rejson.so: undefined symbol: __aeabi_uldivmod
> 1:M 13 May 00:07:06.920 # Can't load module from /usr/local/lib/rejson.so: server aborting
> 
> Is this related to Integer Sizes and typing differences between i386 64 and arm7l ?
> Can you offer a fix?

@jroberts235 . Please check this issue. I think you are facing similar issue as me

#125 
https://github.com/RedisJSON/RedisJSON/issues/125

**Comment by gkorland** [comment]
Not relevant anymore in version 2.0.x
