### ISSUE TITLE
QGET with LIMIT

### ISSUE THREAD

**Issue by htkm** [RedisJSON/RedisJSON#208]
[Original discussion](https://forum.redislabs.com/t/limit-when-doing-a-qget/279/2)

Would it be possible to support `LIMIT` for `QGET` like Redisearch? Thanks!

**Comment by gkorland** [comment]
QGET was part of the beta and was not included in the GA. 
Please see RediSearch 2.2 support for indexing JSON with RedisJSON 2.0: https://oss.redis.com/redisearch/Indexing_JSON/
