### ISSUE TITLE
json.set returns unknown command

### ISSUE THREAD

**Issue by C0D1NGD0J0** [RedisJSON/RedisJSON#214]
Hi,

I recently followed the instructions in the README on building the package and am using the node_redis-rejson client library. However I have been getting this error:

- ReplyError: ERR unknown command `json.set`, with args beginning with: `1234`, `.`, `{"name": "JOHNSON"}`,
    at parseError (.../node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (.../node_modules/redis-parser/lib/parser.js:302:14) {
  command: 'JSON.SET',
  args: [ '1234', '.', '{"name": "JOHNSON"}' ],
  code: 'ERR'
}

====CODE SNIPPET===
....import statement....

rejson(redis);
const client = redis.createClient('6379', process.env.REDIS_HOST_URL);
bluebird.promisifyAll(client);

let k = '1234'
client.json_set(k, '.', '{"name": "JOHNSON"}', (err) => {
  console.log(err);
});

(Returns the error showed above, please what am I doing wrong)

**Comment by gkorland** [comment]
How did you run the redis-server? it seems like the JSON module was not loaded.

**Comment by C0D1NGD0J0** [comment]
Using the command 'redis-server --loadmodule ./target/release/librejson.dylib'.

 ====SERVER OUTPUT===
977:M 18 Aug 2020 # Server initialized
977:M 18 Aug 2020 * <ReJSON> Initializing RediSearch...
977:M 18 Aug 2020 * <ReJSON> RediSearch initialized successfully.
977:M 18 Aug 2020 * <ReJSON> Created new data type 'ReJSON-RL'
977:M 18 Aug 2020 * Module 'ReJSON' loaded from ./target/release/librejson.dylib
977:M 18 Aug 2020 * Ready to accept connections

**Comment by gkorland** [comment]
It seems like you're doing it all good. 
1. Can you please attach a full example? Or point to the repository/gist?
2. Can you try run it in `redis-cli`? 
```
$ redis-cli
127.0.0.1:6379> json.set '1234' '.'  '{"name": "JOHNSON"}'
OK
```
3. Can you try the following?
```
 client.json_set(k, '$', '{"name": "JOHNSON"}', (err) => {
```

**Comment by namti** [comment]
> Hello,
> I got the same error :
> $ redis-cli
> 
> 127.0.0.1:6379> JSON.SET foo . "bar"
> (error) ERR unknown command `JSON.SET`, with args beginning with: `foo`, `.`, `bar`,
> 
> 127.0.0.1:6379> JSON.SET foo . "bar"
> (error) ERR unknown command `JSON.SET`, with args beginning with: `foo`, `.`, `bar`,
> 
> 127.0.0.1:6379> ERR unknown command `JSON.SET`, with args beginning with: `foo`, `.`, `bar`,
> (error) ERR unknown command `ERR`, with args beginning with: `unknown`, `command`, `` JSON.SET`,`, `with`, `args`, `beginning`, `with:`, ``foo`,`, `` .`,`, ``bar`,`,
> 
> 127.0.0.1:6379> JSON.SET object . '{"foo": "bar", "ans": 42}'
> (error) ERR unknown command `JSON.SET`, with args beginning with: `object`, `.`, `{"foo": "bar", "ans": 42}`,
> 
> 127.0.0.1:6379> json.set '1234' '.' '{"name": "JOHNSON"}'
> (error) ERR unknown command `json.set`, with args beginning with: `1234`, `.`, `{"name": "JOHNSON"}`,
> 
> 127.0.0.1:6379> client.json_set(k, '$', '{"name": "JOHNSON"}', (err) => {
> Invalid argument(s)

```
brew services stop redis
redis-server --loadmodule ./your_release_directory/librejson.dylib
```
Then re-enter ```redis-cli```

This works for me

**Comment by madhavdutta** [comment]
Thanks @namti I am adding something more.

Step 1 : brew services stop redis
Step 2 : Go to https://github.com/RedisJSON/RedisJSON
Step 3 : Choose a folder to download the following code
Step 4 : git clone https://github.com/RedisJSON/RedisJSON.git
Step 4 : redis-server --loadmodule ./your_release_directory_from_Step_3/librejson.dylib
Done.

Thanks
MD

**Comment by ducnpdev** [comment]
thanks [madhavdutta](https://github.com/madhavdutta)

**Comment by adil-mo** [comment]
Command/solution for windows pls

**Comment by IlmirSharifullin** [comment]
[madhavdutta](https://github.com/madhavdutta), how need i make my docker-compose.yml file to run redis with json module, i tried add this module to containers data, but that dir is closed and can not be changed..

**Comment by LuisAngelMejiaPoot** [comment]
If it helps someone .  I was faced this problem.

i was used docker-compose with image `redis:latest`. 
You just  have to change the image `redis:latest`  to ` redis/redis-stack`
