### ISSUE TITLE
ReJSON built from master does not take path as the optional argument for JSON.DEBUG MEMORY command.

### ISSUE THREAD

**Issue by Arushi201296** [RedisJSON/RedisJSON#217]
### Steps to reproduce : 
1. Run `rejson:edge` image of the module by executing  :  `docker run -it --net host redislabs/rejson:edge`
2. Connect to the CLI on port 6379 .
3. Execute the following commands : 
  `JSON.SET test . '{"test":"master"}'`
   `JSON.DEBUG MEMORY test`

This version of the module raises an exception stating `wrong number of arguments for JSON.DEBUG command`.

![json-edge](https://user-images.githubusercontent.com/48902477/92108587-451d0b80-ee05-11ea-8a56-00aafb07695d.png)

**However**, the latest released version ( 1.0.4 ) and also 1.0.5 does not raise any exception for the above-mentioned commands. These versions accept root path `.` as the default path argument: 

![json-latest](https://user-images.githubusercontent.com/48902477/92108705-70075f80-ee05-11ea-917b-dd3ffd0ccd6a.png)

**Comment by gkorland** [comment]
ref https://github.com/RedisJSON/RedisJSON/issues/555
