### ISSUE TITLE
REJSON module 1.0.5 in Docker image do not have latest commands

### ISSUE THREAD

**Issue by glassfox** [RedisJSON/RedisJSON#220]
Hi all,
After execution of latest docker with REJSON module 1.0.5, has been found that  latest commands like: JSON.QGET and JSON.INDEX are not exist. 

In other hand, manual compilation and loadmodule in local redis works as expected.

**Comment by gkorland** [comment]
The latest command are not part of RedisJSON 1.0 but are part of the upcoming RedisJSON 2.0.
The relevant docker tag is `redislabs/rejson:edge`

**Comment by glassfox** [comment]
Thanks @gkorland ,
How to compile version 1.0.5 ?

**Comment by gkorland** [comment]
To compile 1.0.5 you need to pull the code from the 1.0 branch.
