### ISSUE TITLE
Works on cluster mode?

### ISSUE THREAD

**Issue by QuickWorkDeveloper** [RedisJSON/RedisJSON#221]
I apologise in advance if this is a rookie question, however, the library, such as JreJSON for Java is unable to connect to a cluster. It simply connects to a standalone instance. Is there a way around this or RedisJSON works only on standalone instances of Redis?

**Comment by gkorland** [comment]
@QuickWorkDeveloper you're right the current version of JRedisJSON doesn't support cluster.
Please open a feature request on https://github.com/RedisJSON/JRedisJSON

**Comment by gkorland** [comment]
Reopened here: https://github.com/RedisJSON/JRedisJSON/issues/26
