### ISSUE TITLE
JSON.MGET - wrong logic behaviour

### ISSUE THREAD

**Issue by asisrae3** [RedisJSON/RedisJSON#223]
ive pulled latest commit(8959470a24ce83e778c4e6b82448fb1e18006997)
and build on Mac OS Catalina:

ive found that the behaviour of MGET is a bit weird.

A try to get missing path from existing keys raises an error , but on the other hand- if no keys at all - MGET return null’s result

Missing path when at least 1 key exists:

JSON.SET akey1 . '{"obj1":{"obj2":{"val":1}}}'
JSON.SET akey2 . '{"obj1":{"obj3":{"val":1}}}'
JSON.MGET akey1 akey2 no_such_key

Result:
"ERR path does not exist"

Missing path when no keys exists:

JSON.MGET akey1 akey2 no_such_key

Result:
 1) null
 2)  null

Thats doesn’t match the documentation at all:

Description ¶

Returns the values at path from multiple key s. Non-existing keys and non-existing paths are reported as null.

**Comment by gkorland** [comment]
I'm not sure how you got `ERR path does not exist`.

```
127.0.0.1:6379> FLUSHALL
OK
127.0.0.1:6379> JSON.MGET akey1 akey2 no_such_key
1) (nil)
2) (nil)
```

```
127.0.0.1:6379> JSON.SET akey1 . '{"obj1":{"obj2":{"val":1}}}'
OK
127.0.0.1:6379> JSON.SET akey2 . '{"obj1":{"obj3":{"val":1}}}'
OK
127.0.0.1:6379> JSON.MGET akey1 akey2 no_such_key
1) (nil)
2) (nil)
```

```
127.0.0.1:6379>  JSON.SET akey2 . '{"obj2":{"obj3":{"val":1}}}'
OK
127.0.0.1:6379> JSON.MGET akey1 akey2 .obj2
1) (nil)
2) "{\"obj3\":{\"val\":1}}"
```

**Comment by asisrae3** [comment]
Hey Guy,
as i said, ive pulled latest and built it on my Macbook pro.

are we working on the same version?
same OS?

thanks,

**Comment by asisrae3** [comment]
hey Guy,
ive followed the instruction in Github:

cargo build --release

Mac OS
redis-server --loadmodule ./target/release/librejson.dylib

?

**Comment by gkorland** [comment]
@asisrae3 sorry I thought you're using the latest official release 1.0.5.
I only got now that you're using the source from master.

**Comment by gkorland** [comment]
@asisrae3 can you please test with the PR #230
