### ISSUE TITLE
JSON.GET behaves differently for v1.0.5 and v1.0.6

### ISSUE THREAD

**Issue by Arushi201296** [RedisJSON/RedisJSON#227]
**Description** : `JSON.GET` command behaves differently for versions <= 1.0.5 and v1.0.6

**v1.0.5** 
![ReJSON-1 0 5](https://user-images.githubusercontent.com/48902477/93984131-0d203d00-fda1-11ea-8937-4aa2691d4d7d.png)
 
In the second command - Empty string as path ( `''` ) is being considered as root path ( `.` ) and no exception is raised.

**v1.0.6**
![ReJSON-1 0 6](https://user-images.githubusercontent.com/48902477/93984279-3771fa80-fda1-11ea-8b5b-b1ae2d24122c.png)

In the fourth command - Empty string as path ( `''` ) raises an exception unlike lower versions.

( Docker is used in both the cases)

**Comment by gkorland** [comment]
@Arushi201296 this is a result of https://github.com/RedisJSON/RedisJSON/pull/222
