### ISSUE TITLE
QUESTION : How to change the redis.conf when using RedisJSON

### ISSUE THREAD

**Issue by arnoldfranz** [RedisJSON/RedisJSON#237]
Hi,
I would like to change the redis.conf to enable AOF.
I adapted the parameters and did this Dockerfile
`
FROM redislabs/rejson:latest

COPY redis.conf /usr/local/etc/redis/redis.conf

CMD ["redis-server", "--loadmodule", "/usr/lib/redis/modules/rejson.so"]
`
I run it, Redis works but the conf file seems not loaded, the new parameters are not loaded.
Any clue is welcome
AF

**Comment by itamarhaber** [comment]
Hello @arnoldfranz 

Clue: you'll need to load the module in the conf file and provide the conf file as an argument to redis-server. The following works for me ;)

redis.conf:
```
# First load the module
loadmodule /usr/lib/redis/modules/rejson.so

# Next, put in any additional non-default configuration directives, e.g.:
databases 1
```

Dockerfile:
```
FROM redislabs/rejson:latest

COPY redis.conf /usr/local/etc/redis/redis.conf

CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]
```

**Comment by RomanSteinberg** [comment]
I've noticed that redis.conf and libredisjson.so should be located at /etc/redis . Otherwise systemctl fails to start service on my Ubuntu 20.04.
