### ISSUE TITLE
Can't load module on Debian 9

### ISSUE THREAD

**Issue by Vowan** [RedisJSON/RedisJSON#241]
Hello
I am running Debian 9 and trying to install your modules but have 
RedisJSON/RedisJSON$ cargo build --release
    Finished release [optimized] target(s) in 0.15s
RedisJSON/RedisJSON$ redis-server --loadmodule ./target/release/librejson.so

*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 2
>>> 'loadmodule "./target/release/librejson.so"'
Bad directive or wrong number of arguments
RedisJSON/RedisJSON$ 
What am I doing wrong?
Thank you

**Comment by gkorland** [comment]
It seems like a general Redis configuration error.
1. Can you try run the server without the module?
2. Please add the all error message.

**Comment by Vowan** [comment]
I have redis server running as service. I installed it just through apt and configured nothing myself
 redis-server.service - Advanced key-value store
  ```
 Loaded: loaded (/lib/systemd/system/redis-server.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-11-16 10:09:29 EET; 23min ago
     Docs: http://redis.io/documentation,
           man:redis-server(1)
  Process: 740 ExecStartPost=/bin/run-parts --verbose /etc/redis/redis-server.post-up.d (code=exited, status=0/SUCCESS)
  Process: 715 ExecStart=/usr/bin/redis-server /etc/redis/redis.conf (code=exited, status=0/SUCCESS)
  Process: 682 ExecStartPre=/bin/run-parts --verbose /etc/redis/redis-server.pre-up.d (code=exited, status=0/SUCCESS)
 Main PID: 739 (redis-server)
    Tasks: 3 (limit: 4915)
   Memory: 1.8M
      CPU: 1.519s
   CGroup: /system.slice/redis-server.service
           └─739 /usr/bin/redis-server 127.0.0.1:6379

Nov 16 10:09:25 debian systemd[1]: Starting Advanced key-value store...
Nov 16 10:09:27 debian run-parts[740]: run-parts: executing /etc/redis/redis-server.post-up.d/00_example
Nov 16 10:09:28 debian systemd[1]: redis-server.service: PID file /var/run/redis/redis-server.pid not readable (yet?) after start-post: No such file or directory
Nov 16 10:09:29 debian systemd[1]: Started Advanced key-value store. 
```
then I compiled your module without any error. When I try to do adding module from the root of module folder by 
redis-server --loadmodule ./target/release/librejson.so
 I get 
```
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 2
>>> 'loadmodule "./target/release/librejson.so"'
Bad directive or wrong number of arguments 
```

**Comment by Vowan** [comment]
but your docker image is working well for me as the alternative approach

**Comment by gkorland** [comment]
Can you please check with redis-server are you running?

**Comment by Vowan** [comment]
yes redis-server is running and I am able to communicate with it
