### ISSUE TITLE
 localhost JSON.SET works, external ip redis-cli does not load RedisJSON

### ISSUE THREAD

**Issue by metait** [RedisJSON/RedisJSON#242]
Hi,

I have ran ./redis-server --loadmodule, and it loads RedisJSON without any issues.
if i do redis-cli without -h specified, defaulting to localhost on ec2/centos, i am able to run JSON.SET command 
However, if i do redis-cli -h pointing to ec2 external ip address, i am not able to run JSON.set command
same goes for load module command, in local host, it pulls RedisJSON but in external ip, it does not.

Another interesting pointer is I use RDM/redsamin client, it does not pull any key/value from data that was set using localhost in ec2.  It only pulls data that is stored using redis-cli -h (external ip addr)

I am lost why it differs with local host and external ip,  I have commented out bind in redis.conf.

Thanks,

**Comment by itamarhaber** [comment]
Hi - can you please clarify what you mean by external IP address? Also, where are you running RDM on?
