### ISSUE TITLE
Index on UUID

### ISSUE THREAD

**Issue by suityou01** [RedisJSON/RedisJSON#245]
I have the following search that is partially working, using the following Index and Record format.

`JSON.INDEX ADD bookingid id $.booking.id`
`JSON.SET FORMSUBMISSION1 . '{ "booking": { "id": "8238427d-495b-4f51-836f-c4e3530ca45d", "forms": { "form1": { "name": "", "surname": "", "address1": "", "address2": "", "town": "", "postcode": "", "bookingdate": "", "bookingtime": "" }, "form2": { "starter": "" }, "form3": { "maincourse": {} }, "form4": { "pudding": {} } } } }' INDEX bookingid`

The want here is to uniquely identify the record using the ID value. For the sake of argument let's assume I have guaranteed this value is unique within this context.

This query works 
`JSON.QGET bookingid 8238427d*`

This query does not work
`JSON.QGET bookingid 8238427d-495b*`

Nor indeed does a search on the full value.

I suspect this is to do with escape characters but if there is a way to make this work please let me know. I would figure this is quite a popular use case.

**Comment by gkorland** [comment]
You are right the issue here is with the escape characters, escaping the `-` this way `\\-` should do:

```bash
127.0.0.1:6379> JSON.SET FORMSUBMISSION1 . '{ "booking": { "id": "8238427d\\-495b\\-4f51\\-836f\\-c4e3530ca45d", "forms": { "form1": { "name": "", "surname": "", "address1": "", "address2": "", "town": "", "postcode": "", "bookingdate": "", "bookingtime": "" }, "form2": { "starter": "" }, "form3": { "maincourse": {} }, "form4": { "pudding": {} } } } }' INDEX bookingid
OK

127.0.0.1:6379>  JSON.QGET bookingid '8238427d\-495b*'
"{\"FORMSUBMISSION1\":[{\"booking\":{\"id\":\"8238427d\\\\-495b\\\\-4f51\\\\-836f\\\\-c4e3530ca45d\",\"forms\":{\"form1\":{\"name\":\"\",\"surname\":\"\",\"address1\":\"\",\"address2\":\"\",\"town\":\"\",\"postcode\":\"\",\"bookingdate\":\"\",\"bookingtime\":\"\"},\"form2\":{\"starter\":\"\"},\"form3\":{\"maincourse\":{}},\"form4\":{\"pudding\":{}}}}}]}"
```

**Comment by gkorland** [comment]
Please notice RedisJSON 2.0 final version dropped the support for JSON.INDEX and JSON.QGET.
To read more about how to index JSONs using RediSearch see: https://oss.redis.com/redisearch/Indexing_JSON/
