### ISSUE TITLE
MacOS cannot load module (image not found)

### ISSUE THREAD

**Issue by mrwonderfulness** [RedisJSON/RedisJSON#259]
I followed the instructions to use rust and tried to load the module as shown from the RedisJSON-master folder:

`redis-server --loadmodule ./target/release/librejson.dylib`

and get the following error:

_**Module ./target/release/librejson.dylib failed to load: dlopen(./target/release/librejson.dylib, 6): image not found**_

_**Can't load module from ./target/release/librejson.dylib: server aborting**_

Indeed, the file is not in **target/release**. 
Am I doing something wrong?

**Comment by gavrie** [comment]
@mrwonderfulness did you run the `cargo build --release` command as mentioned in the "Build" section? Did it complete successfully? If not, please paste its output here.

**Comment by mrwonderfulness** [comment]
@gavrie 
I did it yesterday and there didn't seem to be an error, but I just tried again and it didn't seem to work.
Are these the right steps: 
1. download this code and go to folder
2. run `cargo build --release`
3. there should be an .so file that I can load with redis-cli ?

Anyway, this is the error message I get this time:
$ `cargo build --release`

**dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/bin/cargo
  Reason: image not found
[1]    18678 abort      cargo build --release**

I'm not familiar with this process and I looked for the MacOS module to just download and install but there is only a Linux version on the Redis site.

Thanks.

**Comment by mrwonderfulness** [comment]
There is no module for MacOS on the site:

![image](https://user-images.githubusercontent.com/73687088/106109116-7ddec800-618c-11eb-83c0-7286b4886899.png)

**Comment by gavrie** [comment]
> @gavrie
> I did it yesterday and there didn't seem to be an error, but I just tried again and it didn't seem to work.
> Are these the right steps:
> 
> 1. download this code and go to folder
> 2. run `cargo build --release`

@mrwonderfulness so far so good.

> 3. there should be an .so file that I can load with redis-cli ?

On macOS the extension is `.dylib` instead of `.so` but all the rest is the same.
 
> Anyway, this is the error message I get this time:
> $ `cargo build --release`
> 
> **dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib Referenced from: /usr/local/bin/cargo Reason: image not found [1] 18678 abort cargo build --release**

It seems like you haven't installed Rust in the standard way, via `rustup` (if you had, `cargo` would have been in `~/.cargo/bin/cargo`). I suggest removing it, and reinstalling via the instructions (https://www.rust-lang.org/tools/install).

There might also be a problem with your OpenSSL installation -- was it installed via Homebrew or in some other way?
 
> I'm not familiar with this process and I looked for the MacOS module to just download and install but there is only a Linux version on the Redis site.

We officially support only Linux, though it works fine on macOS (which is what I use to work on the code).

If you don't get it to work, you may want to try using Docker for Mac with a Linux container insisde.

**Comment by dextersjab** [comment]
I faced the same issue and just got this working today.

I did
```
cargo clean
cargo build --release
```

Then added the line
`loadmodule /path/to/RedisJSON/target/release/librejson.dylib`
to
`/usr/local/etc/redis.conf` (installed with Homebrew)

Maybe the documentation at https://oss.redislabs.com/redisjson/#macosx should state a requirement for `xcode-select --install` and the location of the compiled file as `/target/release/librejson.dylib`?

**Comment by gavrie** [comment]
@dextersjab sounds good. If you'd like to submit a PR to fix the docs that would be great.

**Comment by dextersjab** [comment]
Should I submit a PR for the **1.0** or the **master** branch? I just noticed that https://oss.redislabs.com/redisjson/ defaults to **v1.0 (latest)**, which has quite different wording to the **master** branch.

**Comment by emmanuelkeller** [comment]
@dextersjab Please do it for the master branch (as 1.0 has been developed in C)
