### ISSUE TITLE
Update Package list for Ubuntu 20.04

### ISSUE THREAD

**Issue by mostueve** [RedisJSON/RedisJSON#262]
When trying to build on Ubuntu 20.04, having `build-essential` is not sufficient. In addition to that, I had to install 

- llvm 
- cmake 
- libclang1 
- libclang-dev 
- cargo

Would be great to update the docs with that info (can I do this via pull request??).

**Comment by gkorland** [comment]
@mostueve thanks for pointing out, a PR is more than welcomed

**Comment by mostueve** [comment]
I have created a pull request: https://github.com/RedisJSON/RedisJSON/pull/264

**Comment by alpintrekker** [comment]
I'd suggest including `clang` into the list. Without it, I was unable to build the module.

**Comment by rafie** [comment]
Please look on branch `feature-search-json`. We're building for Ubuntu Focal: https://app.circleci.com/pipelines/github/RedisJSON/RedisJSON/409/workflows/0db463d5-8ef3-44ca-a5ae-8449f3d20f0e/jobs/1005
Will be merged to master soon.
