### ISSUE TITLE
Compilation Error on Ubuntu 20.04 focal

### ISSUE THREAD

**Issue by chivasblue** [RedisJSON/RedisJSON#272]
Hitting the below error after issuing cargo build --release command.
********************
   Compiling jsonpath_lib v0.2.5 (https://github.com/RedisJSON/jsonpath.git?branch=public-parser#8cd86ae9)
   Compiling redisjson v1.9.0 (/opt/redis-stable/RedisJSON)
error[E0603]: module `export` is private
   --> src/nodevisitor.rs:3:12
    |
3   | use serde::export::Formatter;
    |            ^^^^^^ private module
    |
note: the module `export` is defined here
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.123/src/lib.rs:275:5
    |
275 | use self::__private as export;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0603`.
error: could not compile `redisjson`
********************

Any resolution?

**Comment by oshadmi** [comment]
@chayim
Instead of 
`use serde::export::Formatter;`
Try using
`use std::fmt::Formatter;`

**Comment by chivasblue** [comment]
Thanks it worked!
