### ISSUE TITLE
JSON.GET on non existent path should return (nil)

### ISSUE THREAD

**Issue by emmanuelkeller** [RedisJSON/RedisJSON#273]
This seems unlike normal Redis behaviour, we would expect no error but an empty response / null:

```
redis-cli >> json.get somekey whatever
(nil)
redis-cli >> json.get ncc:locationdetails:133 whatever
(error) ERR path does not exist
```

**Comment by gkorland** [comment]
@emmanuelkeller notice JSON has a native 'null' support, if this query will return a null there will be no way to differentiate between real null and missing path.
