### ISSUE TITLE
json.index and json.QGET not working

### ISSUE THREAD

**Issue by gsudhanshu** [RedisJSON/RedisJSON#278]
I have successfully loaded RedisJSON module and I am able to use json.set command in redis-cli 

but getting Err unknown command `json.index` 

and Err unknown command `json.qget`

**Comment by gkorland** [comment]
Which version of RedisJSON do you run?

**Comment by gsudhanshu** [comment]
I had downloaded the module from redislabs website

**Comment by gsudhanshu** [comment]
its working after building rejson from git source and loading the module

**Comment by gkorland** [comment]
These commands are only available on the "master" branch and are still not part of the official version.
