### ISSUE TITLE
error: failed to run custom build command for `redisearch_api v0.5.0`

### ISSUE THREAD

**Issue by RomanSteinberg** [RedisJSON/RedisJSON#280]
I have tried to build redisjson on Ubuntu 18.04 (two instances, both failed to build) using [guide](https://oss.redislabs.com/redisjson/#building-and-loading-the-module). Also I successfully built redisjson on two computers with Ubuntu 20.04 but I installed additional apt-packages as written [here](https://github.com/RedisJSON/RedisJSON/blob/master/docs/index.md).

The end of make command output.
```shell
...
   Compiling jsonpath_lib v0.2.5 (https://github.com/RedisJSON/jsonpath.git?branch=public-parser#8cd86ae9)
error: failed to run custom build command for `redisearch_api v0.5.0`

Caused by:
  process didn't exit successfully: `/home/rnwind/dev/rejson/target/release/build/redisearch_api-439e04c5ccd076bf/build-script-build` (exit code: 101)
  --- stderr
  /usr/include/x86_64-linux-gnu/sys/types.h:145:10: fatal error: 'stddef.h' file not found
  /usr/include/x86_64-linux-gnu/sys/types.h:145:10: fatal error: 'stddef.h' file not found, err: true
  thread 'main' panicked at 'error generating RediSearch bindings: ()', /home/rnwind/.cargo/registry/src/github.com-1ecc6299db9ec823/redisearch_api-0.5.0/build.rs:20:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
Makefile:55: recipe for target 'build' failed
make: *** [build] Error 101
```

The complete output [redis_log.txt](https://github.com/RedisJSON/RedisJSON/files/6116035/redis_log.txt)

What should I do to fix?

**Comment by gkorland** [comment]
Do you have clang installed?

**Comment by andreshat** [comment]
Have you installed Rust?

**Comment by alpintrekker** [comment]
@RomanSteinberg for me, installing clang with command

`apt install libclang1`

 resolved this issue on Debian Buster IoT Image 2020-04-06 for BeagleBone Black.

**Comment by Jerry-Ma** [comment]
Hi, I happen to have gcc 10.2.0 on ubuntu 20.04, and I am getting the same error. Do I really have to install clang to be able to compile the module?

**Comment by alpintrekker** [comment]
Up to my understanding, yes.

**Comment by Jerry-Ma** [comment]
I ended up installing clang and compiled the module with clang:

```
$ CC=/path/to/clang/prefix/bin/clang make
```

**Comment by gkorland** [comment]
not relevant since RedisJSON 2.0, redisearch_api is not being used anymore
