### ISSUE TITLE
JSON.ARRINSERT regression?

### ISSUE THREAD

**Issue by j-me** [RedisJSON/RedisJSON#286]
Greetings - I've been playing around with this module abit this week. Thanks, and props to those working on it.  
However, I have a bug/observation that would like to raise.  

Context:
I'm attempting to insert into an array at index 0, but JSON.ARRINSERT throws an `ERR index out of bounds` .  

Example via redis-cli
```
>JSON.SET test . "{\"a\": []}"
OK

>JSON.GET test
"{\"a\":[]}"

>JSON.ARRINSERT test a 0 "\"val\""
(error) ERR index out of bounds
```

However if i compile your older C version of this on your 1.0 branch, works fine.
```
>JSON.SET test . "{\"a\": []}"
OK

>JSON.GET test
"{\"a\":[]}"

>JSON.ARRINSERT test a 0 "\"val\""
(integer) 1

> JSON.GET test
"{\"a\":[\"val\"]}"
```

**Comment by gkorland** [comment]
@j-me thanks for reporting it!
