### ISSUE TITLE
Index object in array

### ISSUE THREAD

**Issue by InsaniManES** [RedisJSON/RedisJSON#287]
How can I index for query in array of objects?

For example: 
{
   "Users": [{"id": 1}, {"id": 2}]
}

**Comment by gkorland** [comment]
Which value are you trying to index?

**Comment by InsaniManES** [comment]
I'd in this case, I need to search a value in array of objects

Let's say I have 

{
   "users": [{"id": 1, "name": "david"}, {"id": 2, "name": "Jennifer"}
}

I want to so something like QGET .users [].name = "david" or something like that.

I can do that in other databases but I prefer to work with redis and I don't know what to do the query (if it's possible)

**Comment by InsaniManES** [comment]
Just checked on https://goessner.net/articles/JsonPath/
And I found that asterisk doesn't work, for exmaple:

127.0.0.1:6379> JSON.GET test
"{\"calls\":[{\"ivrid\":1},{\"ivrid\":2}]}"

127.0.0.1:6379> JSON.GET test .calls.*
"{\"ivrid\":1}"
127.0.0.1:6379> JSON.GET test .calls.[0,1]
"{\"ivrid\":1}"

it should return more than one result.

**Comment by emmanuelkeller** [comment]
@InsaniManES 

The current version (v1.0) has a limited support of JSON Path.
https://oss.redislabs.com/redisjson/path/

The full support of JSONPath is planned with the next version (v1.2). It is currently available from the master branch, or on docker with the tag "edge".

You can try it there:

    docker pull redislabs/rejson:edge

**Comment by InsaniManES** [comment]
@emmanuelkeller How can I get version 1.2?

**Comment by Stephane-Br** [comment]
Nice, I was looking for this feature. (The wildcard for the arrays) Are you guys planning releasing a docker edge container with the v1.2 tag soon ?
Thanks

**Comment by yangbodong22011** [comment]
> @InsaniManES
> 
> The current version (v1.0) has a limited support of JSON Path.
> https://oss.redislabs.com/redisjson/path/
> 
> The full support of JSONPath is planned with the next version (v1.2). It is currently available from the master branch

@emmanuelkeller I tried the `master` and `1.2` branches, but it still doesn’t seem to support the full `JSONPath`. What am I missing?

```
127.0.0.1:6379> JSON.SET users . '{"users":[{"id":1,"name":"david"},{"id":2,"name":"Jennifer"}]}'
OK
127.0.0.1:6379> JSON.GET users "$.users[*]"
"{\"id\":1,\"name\":\"david\"}"
127.0.0.1:6379> JSON.GET users "$.users[*].name"
"\"david\""
127.0.0.1:6379>
```

**Comment by gkorland** [comment]
RedisJOSN 2.0+ now support this query:

```bash
127.0.0.1:6379> JSON.SET users . '{"users":[{"id":1,"name":"david"},{"id":2,"name":"Jennifer"}]}'
OK
127.0.0.1:6379> JSON.GET users "$.users[*]"
[{"id":1,"name":"david"},{"id":2,"name":"Jennifer"}]
127.0.0.1:6379> JSON.GET users "$.users[*].name"
["david","Jennifer"]
```
