### ISSUE TITLE
cargo build --release fails on Apple M1 OSX 11.2.3

### ISSUE THREAD

**Issue by chrisAtRedisLabs** [RedisJSON/RedisJSON#293]
LLVM is latest homebrew version (11), rustc is 1.51

Error report is: 

 Compiling redis-module v0.11.0
 Compiling redisearch_api v0.5.0
error: failed to run custom build command for `redisearch_api v0.5.0`

Caused by:
  process didn't exit successfully: `/Users/xxx/Downloads/RedisJSON/target/release/build/redisearch_api-92575334ca7f8799/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'libclang error; possible causes include:
  - Invalid flag syntax
  - Unrecognized flags
  - Invalid flag arguments
  - File I/O errors
  - Host vs. target architecture mismatch
  If you encounter an error missing from this list, please file an issue or a PR!', /Users/christoph/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.54.0/src/ir/context.rs:573:15
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
     1: core::panicking::panic_fmt
               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
     2: core::option::expect_failed
               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1292:5
     3: core::option::Option<T>::expect
     4: bindgen::ir::context::BindgenContext::new
     5: bindgen::Bindings::generate
     6: bindgen::Builder::generate
     7: build_script_build::main
     8: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: build failed

Please let me know if you need more details.

**Comment by Johny-Ch** [comment]
Any update on this issue?

**Comment by chrisAtRedisLabs** [comment]
Initial RCA indicates an ancient bindgen version as the potential culprit. The bad news is that this has side effects on other required crates such as redismodule-rs as well so the fix may be complex. Stay tuned.

**Comment by tl3821** [comment]
any update? plz

**Comment by tl3821** [comment]
> Has been fixed in 2.0.

thank you! success to cargo build, but where run "redis-server --loadmodule ./target/release/librejson.dylib", it said :

> 12829:C 14 Sep 2021 00:16:51.037 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
12829:C 14 Sep 2021 00:16:51.037 # Redis version=6.2.4, bits=64, commit=00000000, modified=0, pid=12829, just started
12829:C 14 Sep 2021 00:16:51.037 # Configuration loaded
12829:M 14 Sep 2021 00:16:51.039 * Increased maximum number of open files to 10032 (it was originally set to 2560).
12829:M 14 Sep 2021 00:16:51.039 * monotonic clock: POSIX clock_gettime
                _._                                                  
           _.-``__ ''-._                                             
      _.-``    `.  `_.  ''-._           Redis 6.2.4 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._                                  
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 12829
  `-._    `-._  `-./  _.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |           https://redis.io       
  `-._    `-._`-.__.-'_.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |                                  
  `-._    `-._`-.__.-'_.-'    _.-'                                   
      `-._    `-.__.-'    _.-'                                       
          `-._        _.-'                                           
              `-.__.-'                                               

12829:M 14 Sep 2021 00:16:51.041 # Server initialized
12829:M 14 Sep 2021 00:16:51.045 # Module ./target/release/librejson.dylib failed to load: dlopen(./target/release/librejson.dylib, 6): no suitable image found.  Did find:
	./target/release/librejson.dylib: mach-o, but wrong architecture
	/Users/.../Downloads/rd2/rd2/target/release/librejson.dylib: mach-o, but wrong architecture
12829:M 14 Sep 2021 00:16:51.045 # Can't load module from ./target/release/librejson.dylib: server aborting

the OS is Big Sur 11.5.2
any suggesting? thank you very much!

**Comment by chrisAtRedisLabs** [comment]
Looks like the architecture for the compiled server and module binaries differ.

What do `file <path to server binary>` and `file <path to module shared object>` report?
