### ISSUE TITLE
How to filter an item in JSON.array

### ISSUE THREAD

**Issue by ashifa454** [RedisJSON/RedisJSON#304]
Hi Team,
I would like to filter an item via "uid" from key "D" which is a JSON.array

```json
{
  "MTYxNTkwMTY5Mzk2Nw-meet": {
    "A": [],
    "B": "discussion",
    "C": "created",
    "D": [
      {
        "uid": "5c0bd0471849cbf4ac34df49"
      }
    ]
  }
}
```

**Comment by gkorland** [comment]
what is expected result in this case?

**Comment by ashifa454** [comment]
{ uid:"5c0bd0471849cbf4ac34df49"}

**Comment by gkorland** [comment]
`JSON.GET doc:1 $.MTYxNTkwMTY5Mzk2Nw-meet.D[0]`

**Comment by ashifa454** [comment]
I think this will give me the first item from the array, what if I want to find the index on runtime?

**Comment by gkorland** [comment]
```
JSON.GET doc:1 '$..D[?(@.uid=="5c0bd0471849cbf4ac34df49")]'
```

**Comment by gkorland** [comment]
@ashifa454 regarding QGET, you're right it was never officially released and we decided the right place for this functionality is RediSearch. 
In the upcoming version you will be able to create RediSearch index that follows RedisJSON.

**Comment by ashifa454** [comment]
> ```
> JSON.GET doc:1 '$..D[?(@.uid=="5c0bd0471849cbf4ac34df49")]'
> ```

can you please explain this one or if there is any detailed documentation?

**Comment by gkorland** [comment]
You can read more about JSONPath here - https://github.com/json-path/JsonPath

**Comment by ashifa454** [comment]
thankyou so much for quick response it worked
