### ISSUE TITLE
Request for Additional Helper

### ISSUE THREAD

**Issue by ashifa454** [RedisJSON/RedisJSON#308]
Hi Team,
I wanted to understand why there are limited helpers on numbers, meaning why can't have 
- NUMDCRBY -> to decrement by number 
helpers for boolean
- Toggle -> to toggle a Boolean value.

**Comment by gkorland** [comment]
Numdcrby == numincrby with negative number.
Toggle seems like a simple and nice addition thanks!

**Comment by ashifa454** [comment]
should I raise PR then 😉

**Comment by gkorland** [comment]
That will be great, thanks!

**Comment by ashifa454** [comment]
where should a target my PR?

**Comment by ashifa454** [comment]
Merged in #314
