### ISSUE TITLE
JSON.INDEX returns command not found in edge tag of docker image

### ISSUE THREAD

**Issue by GnaneshKunal** [RedisJSON/RedisJSON#321]
The `edge` tag of the docker image was recently updated and it no longer has `JSON.INDEX` command.

**Comment by oshadmi** [comment]
This new RedisJSON has no more search capabilities on its own. You can try the following docker image
where RediSearch is able to index and search JSON content similarly to how it is done with Hashes:
redislabs/redisearch:feature-search-json

For example:
`module list `  ==> would show both `ReJSON` and `search` modules are loaded
To create an index on JSON
`FT.CREATE idx1 ON JSON SCHEMA $.name TEXT SORTABLE $.desc TEXT`
To add JSON content:
```
JSON.SET key:1 $ '{"name":"htop", "description":"perf and process monitor"}'
JSON.SET key:2 $ '{"name":"uname", "description":"system information"}'

```

And to search it
 ```
FT.SEARCH idx1 ht*
1) (integer) 1
2) "key:1"
3) 1) "$"
   2) "{\"name\":\"htop\",\"description\":\"perf and process monitor\"}"
```

**Comment by GnaneshKunal** [comment]
> You can try the following docker image where RediSearch is able to index and search JSON content similarly to how it is done with Hashes: `redislabs/redisearch:feature-search-json`

Understood.

But the `redislabs/rejson:edge` one doesn't have RediSearch in it. So will the RediSearch module will be added to `edge` tag soon? 

Actually, we are using `JSON.INDEX` to distinguish rejson v1 and v2 in RedisInsight. Since `JSON.INDEX` used to be available only on rejson v2. Due to the unavailability of `JSON.INDEX` command, we have to find a different way to know the version.

**Comment by gkorland** [comment]
Why do you need to diff between the version?

**Comment by GnaneshKunal** [comment]
@gkorland 
To properly display the version in the configuration tool. So even if a user uses a `master` version of rejson (for which `MODULE LIST` will return `999999` as rejson version), we still try to display the exact version if possible or else predict the version range (like `>=1.0.6 and <2`)
