### ISSUE TITLE
"It seems build prerequisites have not been installed: please run 'sudo make setup'"

### ISSUE THREAD

**Issue by jack3898** [RedisJSON/RedisJSON#335]
When I try to run `make` in the project folder, I get the following output:

`deps/readies/mk/main:34: *** It seems build prerequisites have not been installed: please run 'sudo make setup'..  Stop.`

Then, when I try to run `sudo make setup` I get:

`make: *** No rule to make target 'setup'.  Stop.`

I have build-essential installed, I even installed Rust as well thinking that is why this is happening. Apparently not.

I am running in Windows Ubuntu 20.04, in WSL.

Is it a simple fix? Am I simply missing something the docs did not tell me to install?

Many thanks!

**Comment by gkorland** [comment]
Did you init the sub modules `git submodule update --init` ?
Can you please try to run `cargo build`?

**Comment by jack3898** [comment]
Hey gkorland thanks for the response. :)

I decided to upload a video of the process. You may find the answer to your question at 0:48. Tl:dw, it fails and the build is unsuccessful.

https://www.youtube.com/watch?v=mWehz1s378o

Console output below if the video ever goes missing:

>error: failed to run custom build command for `redis-module v0.15.0`

>Caused by:
  >process didn't exit successfully: `/home/jack/redisjsonissue/RedisJSON/target/debug/build/redis-module-794c6594618b3cc9/build-script-build` (exit code: 101)
  >--- stdout
  >TARGET = Some("x86_64-unknown-linux-gnu")
  >OPT_LEVEL = Some("0")
  >HOST = Some("x86_64-unknown-linux-gnu")
  >CC_x86_64-unknown-linux-gnu = None
  >CC_x86_64_unknown_linux_gnu = None
  >HOST_CC = None
  >CC = None
  >CFLAGS_x86_64-unknown-linux-gnu = None
  >CFLAGS_x86_64_unknown_linux_gnu = None
  >HOST_CFLAGS = None
  >CFLAGS = None
  >CRATE_CC_NO_DEFAULTS = None
  >DEBUG = Some("true")
  >CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  >running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "src/include/" "-Wall" "-Wextra" "-DREDISMODULE_EXPERIMENTAL_API" "-o" "/home/jack/redisjsonissue/RedisJSON/target/debug/build/redis-module-a324a4759af36348/out/src/redismodule.o" "-c" "src/redismodule.c"
  >exit code: 0
  >AR_x86_64-unknown-linux-gnu = None
  >AR_x86_64_unknown_linux_gnu = None
  >HOST_AR = None
  >AR = None
  >running: "ar" "cq" "/home/jack/redisjsonissue/RedisJSON/target/debug/build/redis-module-a324a4759af36348/out/libredismodule.a" "/home/jack/redisjsonissue/RedisJSON/target/debug/build/redis-module-a324a4759af36348/out/src/redismodule.o"
  >exit code: 0
  >running: "ar" "s" "/home/jack/redisjsonissue/RedisJSON/target/debug/build/redis-module-a324a4759af36348/out/libredismodule.a"
  >exit code: 0
  >cargo:rustc-link-lib=static=redismodule
  >cargo:rustc-link-search=native=/home/jack/redisjsonissue/RedisJSON/target/debug/build/redis-module-a324a4759af36348/out

  >--- stderr
  >thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'libclang.so\', \'libclang-*.so\', \'libclang.so.*\', \'libclang-*.so.*\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.58.1/src/lib.rs:2057:31
  >note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
>warning: build failed, waiting for other jobs to finish...
>error: build failed

**Comment by oshadmi** [comment]
The Makefile was updated and you can pull changes and run (on Linux):
`sudo make setup`

Alternatively, to get `clang` and other dependencies, on Linux, please do the following
```
sudo ./deps/readies/bin/getpy3
sudo ./system-setup.py
```

In the meantime, you can see more details in the documentation in other modules, e.g., in [RedisTimeSeries](https://github.com/RedisTimeSeries/RedisTimeSeries)
Following the line:
    `If make is not yet available, the following commands are equivalent:`

(Please notice the above commands will install various packages on your system using the native package manager and pip. This requires root permissions (i.e. sudo) on Linux.)

**Comment by jack3898** [comment]
Thank you so much for your support. It is all fixed, and I have ran this installation on a fresh Ubuntu 20.04 instance with success.

Again, thanks a bunch!
