### ISSUE TITLE
[FR] Merge nested types

### ISSUE THREAD

**Issue by itamarhaber** [RedisJSON/RedisJSON#34]
Consider

```
> JSON.SET j . '{"foo":"bar"}
OK
> JSON.SET j . '{"ans":42}'
OK
> JSON.GET j
"{\"ans\":42}"
```

That is `SET`s expected behavior, so the value at the path is replaced. However. When it comes to objects (and perhaps arrays too), it makes sense to support a merge operation, for example:

```
> JSON.SET j . '{"foo":"bar"}
OK
> JSON.MERGE j . '{"ans":42}'
OK
> JSON.GET j
"{\"foo\":\"bar\",\"ans\":42}"

Furthermore, this could be augmented with NX, XX for keys-level resolution and possibly other modifiers. Lastly, an MX modifier should be added to `JSON.SET` to expose the same merge functionality.

**Comment by dvirsky** [comment]
with a single element this equivalent to doing `JSON/SET j .ans 42`, no? but anyway, nice idea and wouldn't be hard to implement.

**Comment by fas3r** [comment]
Hello, @itamarhaber, 

is that feature will be added ? 

Thanks by advance.

**Comment by itamarhaber** [comment]
Hello @fas3r 

This feature is definitely something to consider adding.

**Comment by fas3r** [comment]
Hello @itamarhaber , 

Thanks for your reply and looking forward to have it 👍  I created a new issue, I'm not sure to understand how to set/update values in existing keys.  Maybe I misunderstand and it's not possible to do so. 

Thanks again for your quick answer.

**Comment by fas3r** [comment]
Hello @itamarhaber , 

Do you know if we could expect it in a close futur by any chance ? 

thanks again.

**Comment by itamarhaber** [comment]
I'm afraid that isn't a priority right now, but it could change. I'll update here if and when it does.

**Comment by fas3r** [comment]
Hello @itamarhaber , 

Any update on that feature :) .

Thanks

**Comment by mrsufgi** [comment]
2021 Here, any roadmapping planned for this? any direction for where to start, maybe we can find the time to contribute such functionality into the module?

**Comment by matth-c3** [comment]
Hello @itamarhaber , 

any update by any chance :) ?

Thanks

**Comment by emmanuelkeller** [comment]
@matth-c3 @mrsufgi  Does it make sense to be inspired by this RFC ? https://datatracker.ietf.org/doc/html/rfc7386

**Comment by matth-c3** [comment]
Hello @emmanuel-keller , seems nice but Im not sure to understand, is that a request for a PR :) ?

**Comment by mrsufgi** [comment]
> Hello @emmanuel-keller , seems nice but Im not sure to understand, is that a request for a PR :) ?

It's general algorithm for merging JSONs that we may use for reference when implementing such funtionallity into RedisJSON (json path/merge).

For simplicity one might want to just use json_patch from Rust standard library: 
https://docs.rs/json-patch/0.2.6/json_patch/fn.merge.html

**Comment by dvirsky** [comment]
I would have loved to implement this if it wasn't for the license /sigh

**Comment by matth-c3** [comment]
Hello @itamarhaber , @emmanuelkeller , 

5 years later, no news on that feature 🚀  😄 ?

**Comment by Thiti-Dev** [comment]
@matth-c3 yeah so sad

**Comment by matth-c3** [comment]
@gkorland  You made my day, thank you
