### ISSUE TITLE
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value',

### ISSUE THREAD

**Issue by VinterCapital** [RedisJSON/RedisJSON#346]
I do the following
git clone https://github.com/RedisLabsModules/rejson.git
cd rejson/
cargo build --release
cargo test --features test
redis-server --loadmodule ./target/release/librejson.so

After a couple of seconds this is what is printed in the terminal
22367:M 05 May 13:49:11.406 # Server initialized
22367:M 05 May 13:49:11.406 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
22367:M 05 May 13:49:11.407 * <ReJSON> Created new data type 'ReJSON-RL'
22367:M 05 May 13:49:11.407 * Module 'ReJSON' loaded from ./target/release/librejson.so
22367:M 05 May 13:49:11.407 * Ready to accept connections

thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/hakan/.cargo/registry/src/github.com-1ecc6299db9ec823/redis-module-0.15.0/src/raw.rs:507:41
stack backtrace:
   0:     0x7f88e258d6ec - std::backtrace_rs::backtrace::libunwind::trace::h87bbdc8ae314e5a4
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x7f88e258d6ec - std::backtrace_rs::backtrace::trace_unsynchronized::h779de2081f0fe77d
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x7f88e258d6ec - std::sys_common::backtrace::_print_fmt::h7f9f27f2b4d4cdf1
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:79
   3:     0x7f88e258d6ec - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf95d19d7937b7307
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:58
   4:     0x7f88e25b430f - core::fmt::write::h31ddd5324183dd8d
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/core/src/fmt/mod.rs:1082
   5:     0x7f88e2587fb7 - std::io::Write::write_fmt::h6553ae225ae21934
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/io/mod.rs:1514
   6:     0x7f88e259d6f0 - std::sys_common::backtrace::_print::h6d7cde6fb59a3272
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:61
   7:     0x7f88e259d6f0 - std::sys_common::backtrace::print::h024fb5a1f254b027
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:48
   8:     0x7f88e259d6f0 - std::panicking::default_hook::{{closure}}::h008654930ff7c19c
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:200
   9:     0x7f88e259d44e - std::panicking::default_hook::h611ef89f1ca4afb7
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:219
  10:     0x7f88e259dc13 - std::panicking::rust_panic_with_hook::h4dfeaf97568ec250
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:569
  11:     0x7f88e258db29 - std::panicking::begin_panic_handler::{{closure}}::hf55586f621f9c415
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:476
  12:     0x7f88e258d83c - std::sys_common::backtrace::__rust_end_short_backtrace::hbddda20e4c1f6fd7
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:153
  13:     0x7f88e259d822 - rust_begin_unwind
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:475
  14:     0x7f88e25b3e91 - core::panicking::panic_fmt::he4c3f055751e8cea
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/core/src/panicking.rs:85
  15:     0x7f88e25b3ddd - core::panicking::panic::hdb4ebd5c0dcce155
                               at /build/rustc-UHkz09/rustc-1.47.0+dfsg1+llvm/library/core/src/panicking.rs:50
  16:     0x7f88e257f491 - redis_module::raw::notify_keyspace_event::he7e015896ec94835
  17:     0x7f88e2503324 - rejson::RedisModule_OnLoad::__do_command::h996c3402bcd27c54
  18:     0x5567c791fe32 - RedisModuleCommandDispatcher
  19:     0x5567c78b33ab - call
  20:     0x5567c78b3b6f - processCommand
  21:     0x5567c78c3b75 - processInputBuffer
  22:     0x5567c78ad128 - aeProcessEvents
  23:     0x5567c78ad50b - aeMain
  24:     0x5567c78aa0fc - main
  25:     0x7f88e4bf4bf7 - __libc_start_main
  26:     0x5567c78aa32a - _start
  27:                0x0 - <unknown>
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)

I am using ubuntu 18.04

**Comment by gkorland** [comment]
thanks for reporting, do you have a way to recreate it?

**Comment by VinterCapital** [comment]
Could you clarify what you mean? I can recreate it on my machine. I can send you the specs of my machine and the steps I took for arrive at the error (mostly explained above) otherwise just let me know what I need to do and I will help out as much as I can.

**Comment by gkorland** [comment]
On which redis version are you running?

**Comment by VinterCapital** [comment]
I am running 4.0.9

Den ons 5 maj 2021 23:35Guy Korland ***@***.***> skrev:

**Comment by gkorland** [comment]
Please upgrade your Redis to Redis 6+

**Comment by VinterCapital** [comment]
thanks, with Redis server v=6.2.3 it works perfectly.

**Comment by shawnlauzon** [comment]
Worked for me too! I suggest updating the install document https://oss.redislabs.com/redisjson/#building-and-loading-the-module

![image](https://user-images.githubusercontent.com/611529/126202815-5c9985b1-dcf7-44af-892f-7a1f18293bc2.png)
