### ISSUE TITLE
RedisSearch on JSON data not working

### ISSUE THREAD

**Issue by MR4online** [RedisJSON/RedisJSON#381]
I like to use RedisJson with RedisSearch, but I cant make it work. 
First of all: **Is there any documentation for this combination?**
I tried to adapt the RedisSearch [docs](https://oss.redislabs.com/redisearch/Tags/) with this https://github.com/RedisJSON/RedisJSON/issues/321#issuecomment-824844063 , the following way:

```
FT.CREATE myIndexTest ON JSON PREFIX 1 test: SCHEMA $.name TEXT $.cities TAG
JSON.SET test:33 $ '{"name":"htop", "cities":"Berlin, New York"}'

```

this workes:

```
FT.SEARCH myIndexTest ht*

1) (integer) 1
2) "test:33"
3) 1) "$"
   2) "{\"name\":\"htop\",\"cities\":\"Berlin, New York\"}"

```

but searching text by field does not work:

```
FT.SEARCH myIndexTest "@name:ht*"

1) (integer) 0
```

and searching tags does not work at all:

```
FT.SEARCH myIndexTest "@cities:{ New York | Los Angeles | Barcelona }"

1) (integer) 0
```

**How do I get these 2 queries working?**

Thanks a lot!

----

I'm using _redislabs/redisearch:feature-search-json_ Docker container

**Comment by MR4online** [comment]
I think I found the solution here: https://youtu.be/6viyQCcdrU0?t=424
There is a need for naming the fields, like:

`FT.CREATE myIndexTest ON JSON PREFIX 1 test: SCHEMA $.name AS name TEXT $.cities AS cities TAG`

So, if that's the trick, I would be thrilled, if we could have any docs for Search-Json :)

**Comment by gkorland** [comment]
Notice you can easily run Redis with both modules using the redismod container:

```
docker run -p 6379:6379 -it --rm redislabs/redismod:edge
```

**Comment by Desnoo** [comment]
If someone else comes across this issue. You should use the edge versions of redisearch and rejson.

**Comment by gkorland** [comment]
You can now use the official RedisJSON/Search latest docker.

**Comment by yiuked** [comment]
tag search is not work
