### ISSUE TITLE
How to filter for key value with dash in it?

### ISSUE THREAD

**Issue by zsoltkrenak** [RedisJSON/RedisJSON#384]
Hi All,

I'm trying to do filtering on a json data based on this schema: [rfc8345](https://datatracker.ietf.org/doc/html/rfc8345) 
Naturally this rfc has dashes in almost all keys which makes things a little bit harder. 

I have a simplified dataset:
`127.0.0.1:6379> JSON.GET topologyDb .
"{\"ietf-network:networks\":{\"network\":[{\"network-id\":\"network-2\",\"node\":[{\"node-id\":\"host-20\"},{\"node-id\":\"switch-20\"},{\"node-id\":\"host-21\",\"supporting-node\":[{\"network-ref\":\"network-2\",\"node-ref\":\"host-21\"}]}]},{\"network-id\":\"network-1\",\"node\":[{\"node-id\":\"switch-1\"},{\"node-id\":\"switch-2\"},{\"node-id\":\"switch-3\"},{\"node-id\":\"host-4\"},{\"node-id\":\"host-3\"},{\"node-id\":\"host-2\"},{\"node-id\":\"host-1\"},{\"node-id\":\"node-1\"}]}]}}"`

I would like to do a filter in RedisJson that does the following:
`$.ietf-network:networks.network[?(@["network-id"]=='network-1')]`
This works here: [jsonpath.com](https://jsonpath.com/)

In Redis I tried to do it in the following way but I cannot get it to work:
`127.0.0.1:6379> JSON.GET topologyDb '["ietf-network:networks"].network[?(@["network-id"]=="network-1")]'
(error) ERR Search path error at offset 35: square brackets can only contain integers, single- or double-quoted strings`
It seems like an issue with having square brackets inside square brackets but without the square brackets I cannot use key value with dashes in them.

Is there any way to filter on keys with dashes in them? 

Thanks for the help!

**Comment by gkorland** [comment]
which version of RedisJSON are you using? I just tried with version on `master` branch and it worked:
```
not connected> JSON.SET topologyDb . "{\"ietf-network:networks\":{\"network\":[{\"network-id\":\"network-2\",\"node\":[{\"node-id\":\"host-20\"},{\"node-id\":\"switch-20\"},{\"node-id\":\"host-21\",\"supporting-node\":[{\"network-ref\":\"network-2\",\"node-ref\":\"host-21\"}]}]},{\"network-id\":\"network-1\",\"node\":[{\"node-id\":\"switch-1\"},{\"node-id\":\"switch-2\"},{\"node-id\":\"switch-3\"},{\"node-id\":\"host-4\"},{\"node-id\":\"host-3\"},{\"node-id\":\"host-2\"},{\"node-id\":\"host-1\"},{\"node-id\":\"node-1\"}]}]}}"
OK
127.0.0.1:6379> JSON.GET topologyDb '["ietf-network:networks"].network[?(@["network-id"]=="network-1")]'
"{\"network-id\":\"network-1\",\"node\":[{\"node-id\":\"switch-1\"},{\"node-id\":\"switch-2\"},{\"node-id\":\"switch-3\"},{\"node-id\":\"host-4\"},{\"node-id\":\"host-3\"},{\"node-id\":\"host-2\"},{\"node-id\":\"host-1\"},{\"node-id\":\"node-1\"}]}"
```

**Comment by zsoltkrenak** [comment]
I started testing with the latest docker image as the readme suggested:
`docker run -p 6379:6379 --name redis-redisjson redislabs/rejson:latest`

How can I check the exact version of the module?

**Comment by gkorland** [comment]
`latest` is 1.0.7 which is the latest official version.

`edge` is the from master:
```
 docker run -p 6379:6379 --name redis-redisjson redislabs/rejson:edge
```

**Comment by zsoltkrenak** [comment]
Thanks!

With master it seems to work for me as well.
