### ISSUE TITLE
JSONPath Union of several JSONPath

### ISSUE THREAD

**Issue by moulinfr** [RedisJSON/RedisJSON#387]
I have the following JSON Object:
{
  "name": "a name",
  "value": 1234,
  "timestamp": 1623408432,
  "valid": true
}

I am interested in having only a few properties, let's say "name" and "value". Refering to Goessner syntax, I should write a Path as a union of paths this way: $.['name','value'],

However:
  - Trying with redisjson-py, only the "name" property is returned.
  - Trying with redis-cli, the syntax is invalid:
  `JSON.GET foo $.['name','value'] or even  JSON.GET foo $.[name,value]`

**Comment by gkorland** [comment]
Which RedisJSON version are you using?

**Comment by moulinfr** [comment]
RedisJSON is git commit fd4a76a225910cf7489d079c3045c951a278df4d and the ReJSON python client version is 0.5.4

**Comment by gkorland** [comment]
You should call it like that:
```
JSON.GET foo '$.["name","value"]'
```

**Comment by moulinfr** [comment]
Thank you for your reply. Trying your proposal with redis-cli, I have the following response (matching the one I have with redisjson-py):
127.0.0.1:6379> JSON.GET foo '$.["name","value"]'
"\"a name\""

Am I missing something?

**Comment by gkorland** [comment]
Fixed:

```
127.0.0.1:6379> JSON.GET foo "$.['name','value']"
["a name",1234]
```
