### ISSUE TITLE
Loading Rejson module while running Redis is causing panic

### ISSUE THREAD

**Issue by naveenkak** [RedisJSON/RedisJSON#431]
I am trying to load rejson module while running redis server and its causing panic.
redis-server --loadmodule ./rejson.so

Enabled full backtrace, this is the o/p below.

12396:M 26 Jul 07:55:26.965 * <ReJSON> Exported RedisJSON_V1 API
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/redis-module-0.21.0/src/raw.rs:558:42
stack backtrace:
   0:     0x7f6570ebcc70 - std::backtrace_rs::backtrace::libunwind::trace::ha5edb8ba5c6b7a6c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7f6570ebcc70 - std::backtrace_rs::backtrace::trace_unsynchronized::h0de86d320a827db2
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f6570ebcc70 - std::sys_common::backtrace::_print_fmt::h97b9ad6f0a1380ff
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f6570ebcc70 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h14be7eb08f97fe80
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7f6570edc0ef - core::fmt::write::h2ca8877d3e0e52de
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/fmt/mod.rs:1094:17
   5:     0x7f6570ebba45 - std::io::Write::write_fmt::h64f5987220b618f4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/io/mod.rs:1584:15
   6:     0x7f6570ebe3cb - std::sys_common::backtrace::_print::h7f1a4097308f2e0a
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7f6570ebe3cb - std::sys_common::backtrace::print::h1f799fc2ca7f5035
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7f6570ebe3cb - std::panicking::default_hook::{{closure}}::hf38436e8a3ce1071
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:208:50
   9:     0x7f6570ebde9d - std::panicking::default_hook::he2f8f3fae11ed1dd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:225:9
  10:     0x7f6570ebe9dd - std::panicking::rust_panic_with_hook::h79a18548bd90c7d4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:591:17
  11:     0x7f6570ebe547 - std::panicking::begin_panic_handler::{{closure}}::h212a72cc08e25126
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:495:13
  12:     0x7f6570ebd10c - std::sys_common::backtrace::__rust_end_short_backtrace::hbd6897dd42bc0fcd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x7f6570ebe4d9 - rust_begin_unwind
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
  14:     0x7f6570e37f01 - core::panicking::panic_fmt::h77ecd04e9b1dd84d
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
  15:     0x7f6570e37e4d - core::panicking::panic::h60569d8a39169222
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:50:5
  16:     0x7f6570ead728 - redis_module::context::Context::export_shared_api::h777f200680060840
  17:     0x7f6570e8b7a2 - RedisModule_OnLoad
  18:     0x564f14ab974c - moduleLoad
  19:     0x564f14ab9883 - moduleLoadFromQueue
  20:     0x564f14a42078 - main
  21:     0x7f657367bbf7 - __libc_start_main
  22:     0x564f14a4232a - _start
  23:                0x0 - <unknown>
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)

**Comment by gkorland** [comment]
Can you please share the command you sent? or better a recreation?

**Comment by gkorland** [comment]
Which Redis Version are you using? 
Please notice RedisJSON master branch doesn't support Redis 5 you should use a newer version 6.0+

**Comment by naveenkak** [comment]
@gkorland Thanks for the response.
I generate a rejson.so by building rejson package.
Then start the redis server using this command.

redis-server --loadmodule ./rejson.so


My redis version is:

redis-server --version
Redis server v=4.0.9 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=9435c3c2879311f3

**Comment by gkorland** [comment]
You should run with Redis 6+

**Comment by naveenkak** [comment]
Thanks with Redis 6+ i worked.

Now facing another issue, i am trying to start redis service without a load module option.

/etc/init.d/redis-server start

I am getting this error.
Loading RDB produced by version 6.2.5
1462 6963:M 11 Aug 2021 12:01:50.843 * RDB age 3673 seconds
1463 6963:M 11 Aug 2021 12:01:50.843 * RDB memory usage when created 1.32 Mb
1464 6963:M 11 Aug 2021 12:01:50.843 # Internal error in RDB reading offset 0, function at rdb.c:2188 -> The RDB file contain     s module data I can't load: no matching module type 'ReJSON-RL'

Looks like some old RDB file is not cleaned, same error i am getting while trying to start redis through a program.

Can you please help how to resolve this one?
Also is redis storing it on disk, i thought redis was in memory db and once you kill redis all data is all gone?

**Comment by naveenkak** [comment]
ok i removed the db dump from /var/lib/redis and it solved the issue.
So redis creates a database dump on disk as well ? So in case redis process restarts when it comes back again it will be able to restore all the data, is that right?

**Comment by gkorland** [comment]
yes it's right
