### ISSUE TITLE
[Feature Request] Set if doesn't exist

### ISSUE THREAD

**Issue by VytskaLT** [RedisJSON/RedisJSON#463]
An atomic command to set a value if the key doesn't already exist would be nice.
Basically [SETNX](https://redis.io/commands/setnx) but with JSON.GET

**Comment by oshadmi** [comment]
@VytskaLT Please see the optional argument `NX` of [JSON.SET](https://oss.redis.com/redisjson/commands/#syntax_3)
`JSON.SET <key> <path> <json> [NX | XX]`

**Comment by VytskaLT** [comment]
> @VytskaLT Please see the optional argument `NX` of [JSON.SET](https://oss.redis.com/redisjson/commands/#syntax_3) `JSON.SET <key> <path> <json> [NX | XX]`

Thank you
