### ISSUE TITLE
Crosscompile RedisJSON

### ISSUE THREAD

**Issue by TopperBG** [RedisJSON/RedisJSON#471]
Crosscompile RedisJSON
Using: https://github.com/rust-embedded/meta-rust-bin for cross compile majority about cargo.bbclas [1]
Target MACHINE is var-som-mx6 (NXP i.MX6Q)
Target OS: Yocto 2.6 Thud
[1] https://github.com/rust-embedded/meta-rust-bin/blob/master/classes/cargo.bbclass#L112

**_Bitbake recipe:_**
```
SUMMARY = "Redis JSON"
DESCRIPTION = "Redis JSON plugin."
HOMEPAGE = "http://redis.io"
SECTION = "libs"
LICENSE = "BSD-3-Clause"
LIC_FILES_CHKSUM = "file://${WORKDIR}/git/LICENSE;md5=e75c8f72bbc9c3744174aaf54faf3bd4"

SRC_URI="git://github.com/RedisJSON/RedisJSON.git"
BB_STRICT_CHECKSUM = "0"
SRCREV="28c3f32d2045b0fb265a1e7adddbe791eb322ddf"
SRC_URI[md5sum] = "d7900b982b43a4f83be49f846aeaae5c"
SRC_URI[sha256sum] = "10547805d0443f85fa577e0305415375f26af70534a6e96b7918cb0ea6126bff"

PREMIRRORS=""
MIRRORS=""

inherit cargo

S = "${WORKDIR}/git"

BINDGEN_EXTRA_CLANG_ARGS = "--sysroot=${WORKDIR}/recipe-sysroot-native -I${WORKDIR}/recipe-sysroot/usr/include"
RUST_BACKTRACE="full"
LIBCLANG_PATH = "/usr/lib/llvm-6.0/lib/libclang.so"
export LIBCLANG_PATH
export BINDGEN_EXTRA_CLANG_ARGS
export RUST_BACKTRACE

#do_compile_prepend () {
#    CARGO_BUILD_TYPE = "test"
#    cargo_do_compile
#}

#do_compile () {
#  export RUST_TEST_THREADS=1
#  export VERSION=${SRCREV}
#  cargo fetch --manifest-path ${S}/Cargo.toml
#  cargo_do_compile
#}

#do_compile () {
#    cd ${S}
#    export CC=arm-linux-gnueabihf-gcc CC_arm_unknown_linux_gnu=arm-linux-gnueabihf-gcc-with-link-search
#    cargo build --release
#}
```

**_Error without Rust backlog:_**

> | Log data follows:
> | DEBUG: Executing shell function do_compile
> | NOTE: which rustc: /home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redisjson/1.0.8-r0/recipe-sysroot-native/usr/bin/rustc
> | NOTE: rustc --version rustc 1.54.0 (a178d0322 2021-07-26)
> | NOTE: which cargo: /home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redisjson/1.0.8-r0/recipe-sysroot-native/usr/bin/cargo
> | NOTE: cargo --version cargo 1.54.0 (5ae8d74b3 2021-06-22)
> | NOTE: cargo build --verbose --manifest-path /home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redisjson/1.0.8-r0/git/Cargo.toml --target=armv7-unknown-linux-gnueabihf --release
> | Fresh autocfg v1.0.1
> | Fresh unicode-xid v0.2.2
> | Fresh version_check v0.9.3
> | Fresh glob v0.3.0
> | Fresh cfg-if v1.0.0
> | Fresh funty v1.1.0
> | Fresh wyz v0.2.0
> | Fresh tap v1.0.1
> | Fresh regex-syntax v0.6.25
> | Fresh unicode-width v0.1.8
> | Fresh strsim v0.8.0
> | Fresh vec_map v0.8.2
> | Fresh ansi_term v0.11.0
> | Fresh humantime v2.1.0
> | Fresh termcolor v1.1.2
> | Fresh lazycell v1.3.0
> | Fresh hashbrown v0.11.2
> | Fresh peeking_take_while v0.1.2
> | Fresh lazy_static v1.4.0
> | Fresh shlex v1.0.0
> | Fresh rustc-hash v1.1.0
> | Fresh unicode-xid v0.0.4
> | Fresh unicode-segmentation v1.8.0
> | Fresh itoa v0.4.8
> | Fresh cc v1.0.69
> | Fresh ppv-lite86 v0.2.10
> | Fresh quote v0.3.15
> | Fresh linked-hash-map v0.5.4
> | Fresh hex v0.3.2
> | Fresh bitflags v1.3.2
> | Fresh md5 v0.6.1
> | Fresh array_tool v1.0.3
> | Fresh byteorder v1.4.3
> | Fresh libloading v0.7.0
> | Fresh textwrap v0.11.0
> | Fresh libc v0.2.100
> | Fresh synom v0.11.3
> | Fresh heck v0.3.3
> | Fresh proc-macro2 v1.0.28
> | Fresh memchr v2.3.4
> | Fresh radium v0.5.3
> | Fresh ryu v1.0.5
> | Fresh log v0.4.14
> | Fresh quote v1.0.9
> | Fresh aho-corasick v0.7.15
> | Fresh bitvec v0.19.5
> | Fresh atty v0.2.14
> | Fresh which v3.1.1
> | Fresh clang-sys v1.2.0
> | Fresh getrandom v0.1.16
> | Fresh indexmap v1.7.0
> | Fresh num-traits v0.2.14
> | Fresh syn v0.11.11
> | Fresh time v0.1.44
> | Fresh syn v1.0.75
> | Fresh nom v6.2.1
> | Fresh regex v1.4.6
> | Fresh clap v2.33.3
> | Fresh rand_core v0.5.1
> | Fresh num-integer v0.1.44
> | Fresh num-traits v0.1.43
> | Fresh env_logger v0.8.4
> | Fresh cexpr v0.5.0
> | Fresh serde_derive v1.0.128
> | Fresh rand_chacha v0.2.2
> | Fresh enum-primitive-derive v0.1.2
> | Fresh strum_macros v0.21.1
> | Fresh chrono v0.4.19
> | Fresh bindgen v0.59.1
> | Fresh serde v1.0.128
> | Fresh rand v0.7.3
> | Fresh serde_json v1.0.66
> | Compiling redis-module v0.23.0
> | Fresh jsonpath_lib v0.2.6 (https://github.com/RedisJSON/jsonpath.git?branch=generic_json_path#14af7aa5)
> | Fresh bson v0.14.1
> | Running /home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redisjson/1.0.8-r0/target/release/build/redis-module-96a8b1c787effaba/build-script-build
> | error: failed to run custom build command for redis-module v0.23.0
> |
> | Caused by:
> | process didn't exit successfully: /home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redisjson/1.0.8-r0/target/release/build/redis-module-96a8b1c787effaba/build-script-build (exit status: 101)
> | --- stdout
> | TARGET = Some("armv7-unknown-linux-gnueabihf")
> | OPT_LEVEL = Some("3")
> | HOST = Some("x86_64-unknown-linux-gnu")
> | CC_armv7-unknown-linux-gnueabihf = None
> | CC_armv7_unknown_linux_gnueabihf = None
> | TARGET_CC = Some("/home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redisjson/1.0.8-r0/wrappers/cc-wrapper.sh")
> | CFLAGS_armv7-unknown-linux-gnueabihf = None
> | CFLAGS_armv7_unknown_linux_gnueabihf = None
> | TARGET_CFLAGS = Some(" -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redisjson/1.0.8-r0=/usr/src/debug/redisjson/1.0.8-r0 -fdebug-prefix-map=/home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redisjson/1.0.8-r0/recipe-sysroot= -fdebug-prefix-map=/home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redisjson/1.0.8-r0/recipe-sysroot-native= ")
> | CRATE_CC_NO_DEFAULTS = None
> | DEBUG = Some("true")
> | CARGO_CFG_TARGET_FEATURE = None
> | running: "/home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redisjson/1.0.8-r0/wrappers/cc-wrapper.sh" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-march=armv7-a" "-O2" "-pipe" "-g" "-feliminate-unused-debug-types" "-fdebug-prefix-map=/home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redisjson/1.0.8-r0=/usr/src/debug/redisjson/1.0.8-r0" "-fdebug-prefix-map=/home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redisjson/1.0.8-r0/recipe-sysroot=" "-fdebug-prefix-map=/home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redisjson/1.0.8-r0/recipe-sysroot-native=" "-I" "src/include/" "-DREDISMODULE_EXPERIMENTAL_API" "-o" "/home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redisjson/1.0.8-r0/target/armv7-unknown-linux-gnueabihf/release/build/redis-module-ee71a5412677483f/out/src/redismodule.o" "-c" "src/redismodule.c"
> | exit status: 0
> | AR_armv7-unknown-linux-gnueabihf = None
> | AR_armv7_unknown_linux_gnueabihf = None
> | TARGET_AR = None
> | AR = Some("arm-fslc-linux-gnueabi-ar")
> | running: "arm-fslc-linux-gnueabi-ar" "cq" "/home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redisjson/1.0.8-r0/target/armv7-unknown-linux-gnueabihf/release/build/redis-module-ee71a5412677483f/out/libredismodule.a" "/home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redisjson/1.0.8-r0/target/armv7-unknown-linux-gnueabihf/release/build/redis-module-ee71a5412677483f/out/src/redismodule.o"
> | exit status: 0
> | running: "arm-fslc-linux-gnueabi-ar" "s" "/home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redisjson/1.0.8-r0/target/armv7-unknown-linux-gnueabihf/release/build/redis-module-ee71a5412677483f/out/libredismodule.a"
> | exit status: 0
> | cargo:rustc-link-lib=static=redismodule
> | cargo:rustc-link-search=native=/home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redisjson/1.0.8-r0/target/armv7-unknown-linux-gnueabihf/release/build/redis-module-ee71a5412677483f/out
> |
> | --- stderr
> | /usr/include/sys/types.h:145:10: fatal error: 'stddef.h' file not found
> | /usr/include/sys/types.h:145:10: fatal error: 'stddef.h' file not found, err: true
> | thread 'main' panicked at 'error generating bindings: ()', /home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redisjson/1.0.8-r0/cargo_home/registry/src/github.com-1ecc6299db9ec823/redis-module-0.23.0/build.rs:76:10
> | stack backtrace:
> | 0: rust_begin_unwind
> | at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
> | 1: core::panicking::panic_fmt
> | at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
> | 2: core::result::unwrap_failed
> | at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/result.rs:1355:5
> | 3: core::result::Result<T,E>::expect
> | at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/result.rs:997:23
> | 4: build_script_build::main
> | at ./build.rs:68:20
> | 5: core::ops::function::FnOnce::call_once
> | at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
> | note: Some details are omitted, run with RUST_BACKTRACE=full for a verbose backtrace.
> | WARNING: exit code 101 from a shell command.

**_Error with `RUST_BACKTRACE=full` :_**
> | cargo:rustc-link-lib=static=redismodule
> |   cargo:rustc-link-search=native=/home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redisjson/1.0.8-r0/target/armv7-unknown-linux-gnueabihf/release/build/redis-module-ee71a5412677483f/out
> | 
> |   --- stderr
> |   /home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redisjson/1.0.8-r0/recipe-sysroot/usr/include/sys/types.h:144:10: fatal error: 'stddef.h' file not found
> |   /home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redisjson/1.0.8-r0/recipe-sysroot/usr/include/sys/types.h:144:10: fatal error: 'stddef.h' file not found, err: true
> |   thread 'main' panicked at 'error generating bindings: ()', /home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redisjson/1.0.8-r0/cargo_home/registry/src/github.com-1ecc6299db9ec823/redis-module-0.23.0/build.rs:76:10
> |   stack backtrace:
> |      0:     0x563b58a3ea10 - std::backtrace_rs::backtrace::libunwind::trace::h34055254b57d8e79
> |                                  at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
> |      1:     0x563b58a3ea10 - std::backtrace_rs::backtrace::trace_unsynchronized::h8f1e3fbd9afff6ec
> |                                  at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
> |      2:     0x563b58a3ea10 - std::sys_common::backtrace::_print_fmt::h3a99a796b770c360
> |                                  at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:67:5
> |      3:     0x563b58a3ea10 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h32d1f94a80615d18
> |                                  at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:46:22
> |      4:     0x563b58a647fc - core::fmt::write::h306731c068f7162c
> |                                  at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/fmt/mod.rs:1110:17
> |      5:     0x563b58a3b105 - std::io::Write::write_fmt::hd2fa90334eee2a21
> |                                  at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/io/mod.rs:1588:15
> |      6:     0x563b58a40f7b - std::sys_common::backtrace::_print::h5abaa2601a852287
> |                                  at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:49:5
> |      7:     0x563b58a40f7b - std::sys_common::backtrace::print::h8d81445442bb638f
> |                                  at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:36:9
> |      8:     0x563b58a40f7b - std::panicking::default_hook::{{closure}}::hcfe804496a9fa747
> |                                  at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:208:50
> |      9:     0x563b58a40a51 - std::panicking::default_hook::hbea8e3ccf2ba8901
> |                                  at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:225:9
> |     10:     0x563b58a41644 - std::panicking::rust_panic_with_hook::h7ee9e1a2d0f8975a
> |                                  at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:622:17
> |     11:     0x563b58a41127 - std::panicking::begin_panic_handler::{{closure}}::h8ab3b4491718b2c7
> |                                  at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:519:13
> |     12:     0x563b58a3ef0c - std::sys_common::backtrace::__rust_end_short_backtrace::hd489062ffa586a9f
> |                                  at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:141:18
> |     13:     0x563b58a41089 - rust_begin_unwind
> |                                  at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
> |     14:     0x563b584acab1 - core::panicking::panic_fmt::hca6330e3e14086b4
> |                                  at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
> |     15:     0x563b584acba3 - core::result::unwrap_failed::h6160d2b4bfbb0e87
> |                                  at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/result.rs:1355:5
> |     16:     0x563b584ae6d6 - core::result::Result<T,E>::expect::hba0d06d39ab88821
> |                                  at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/result.rs:997:23
> |     17:     0x563b584b092e - build_script_build::main::h6d08fe056edc795c
> |                                  at /home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redisjson/1.0.8-r0/cargo_home/registry/src/github.com-1ecc6299db9ec823/redis-module-0.23.0/build.rs:68:20
> |     18:     0x563b584ae56b - core::ops::function::FnOnce::call_once::hd20fa7710ff654e8
> |                                  at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
> |     19:     0x563b584af58e - std::sys_common::backtrace::__rust_begin_short_backtrace::he0a083547ebf2c39
> |                                  at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:125:18
> |     20:     0x563b584aeb61 - std::rt::lang_start::{{closure}}::h544719abb25225d1
> |                                  at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/rt.rs:49:18
> |     21:     0x563b58a41c49 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2aabc384aab89b7b
> |                                  at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:259:13
> |     22:     0x563b58a41c49 - std::panicking::try::do_call::hc5fcacb7a85fc7b1
> |                                  at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
> |     23:     0x563b58a41c49 - std::panicking::try::hb5d9603af3abbe3a
> |                                  at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
> |     24:     0x563b58a41c49 - std::panic::catch_unwind::h98fe6ac3925e64b4
> |                                  at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
> |     25:     0x563b58a41c49 - std::rt::lang_start_internal::h22ac7383c516f93e
> |                                  at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/rt.rs:34:21
> |     26:     0x563b584aeb40 - std::rt::lang_start::h791a5102de170812
> |                                  at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/rt.rs:48:5
> |     27:     0x563b584b0bfc - main
> |     28:     0x7f9b00654b5b - __libc_start_main
> |     29:     0x563b584ad2aa - _start
> |     30:                0x0 - <unknown>
> | warning: build failed, waiting for other jobs to finish...
> | error: build failed
> | WARNING: exit code 101 from a shell command.

It seems error comes from bindgen stuff for `redis-modules`
Could be connected with https://github.com/RedisJSON/RedisJSON/blob/2d9ac841a3e6365016c68fe1b1b1f7762277bf6c/Cargo.toml#L22
But I can't understand clearly how to do test within Bitbake recipe even tried (look commented lines in recipe)

Any advices how to crosscompile it ?

**Comment by gkorland** [comment]
Did you try to build https://github.com/RedisLabsModules/redismodule-rs ?

**Comment by TopperBG** [comment]
Made quick recipe, again in use `cargo class` but error is prety the same:

```
|      Running `/home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redismodules/0.23.0-r0/target/release/build/redis-module-7cf401e5da6f6f3a/build-script-build`
| error: failed to run custom build command for `redis-module v99.99.99 (/home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redismodules/0.23.0-r0/git)`
| 
| Caused by:
|   process didn't exit successfully: `/home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redismodules/0.23.0-r0/target/release/build/redis-module-7cf401e5da6f6f3a/build-script-build` (exit status: 101)
|   --- stdout
|   TARGET = Some("armv7-unknown-linux-gnueabihf")
|   OPT_LEVEL = Some("3")
|   HOST = Some("x86_64-unknown-linux-gnu")
|   CC_armv7-unknown-linux-gnueabihf = None
|   CC_armv7_unknown_linux_gnueabihf = None
|   TARGET_CC = Some("/home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redismodules/0.23.0-r0/wrappers/cc-wrapper.sh")
|   CFLAGS_armv7-unknown-linux-gnueabihf = None
|   CFLAGS_armv7_unknown_linux_gnueabihf = None
|   TARGET_CFLAGS = Some(" -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redismodules/0.23.0-r0=/usr/src/debug/redismodules/0.23.0-r0 -fdebug-prefix-map=/home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redismodules/0.23.0-r0/recipe-sysroot= -fdebug-prefix-map=/home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redismodules/0.23.0-r0/recipe-sysroot-native= ")
|   CRATE_CC_NO_DEFAULTS = None
|   DEBUG = Some("true")
|   CARGO_CFG_TARGET_FEATURE = None
|   running: "/home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redismodules/0.23.0-r0/wrappers/cc-wrapper.sh" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-march=armv7-a" "-O2" "-pipe" "-g" "-feliminate-unused-debug-types" "-fdebug-prefix-map=/home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redismodules/0.23.0-r0=/usr/src/debug/redismodules/0.23.0-r0" "-fdebug-prefix-map=/home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redismodules/0.23.0-r0/recipe-sysroot=" "-fdebug-prefix-map=/home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redismodules/0.23.0-r0/recipe-sysroot-native=" "-I" "src/include/" "-o" "/home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redismodules/0.23.0-r0/target/armv7-unknown-linux-gnueabihf/release/build/redis-module-64472857c4797081/out/src/redismodule.o" "-c" "src/redismodule.c"
|   exit status: 0
|   AR_armv7-unknown-linux-gnueabihf = None
|   AR_armv7_unknown_linux_gnueabihf = None
|   TARGET_AR = None
|   AR = Some("arm-fslc-linux-gnueabi-ar")
|   running: "arm-fslc-linux-gnueabi-ar" "cq" "/home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redismodules/0.23.0-r0/target/armv7-unknown-linux-gnueabihf/release/build/redis-module-64472857c4797081/out/libredismodule.a" "/home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redismodules/0.23.0-r0/target/armv7-unknown-linux-gnueabihf/release/build/redis-module-64472857c4797081/out/src/redismodule.o"
|   exit status: 0
|   running: "arm-fslc-linux-gnueabi-ar" "s" "/home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redismodules/0.23.0-r0/target/armv7-unknown-linux-gnueabihf/release/build/redis-module-64472857c4797081/out/libredismodule.a"
|   exit status: 0
|   cargo:rustc-link-lib=static=redismodule
|   cargo:rustc-link-search=native=/home/optix/thud/build_fb/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/redismodules/0.23.0-r0/target/armv7-unknown-linux-gnueabihf/release/build/redis-module-64472857c4797081/out
| 
|   --- stderr
|   /usr/include/sys/types.h:145:10: fatal error: 'stddef.h' file not found
|   /usr/include/sys/types.h:145:10: fatal error: 'stddef.h' file not found, err: true
```

**Comment by TopperBG** [comment]
After faced a lot of obstacles with yocto recipe decide to cross-compile localy and put lib in distro.
I've tried to build with `cargo test --lib --target armv7-unknown-linux-gnueabihf`
But test failed:
   ```
Compiling cfg-if v1.0.0
   Compiling hashbrown v0.11.2
   Compiling itoa v0.4.8
   Compiling ppv-lite86 v0.2.10
   Compiling md5 v0.6.1
   Compiling linked-hash-map v0.5.4
   Compiling hex v0.3.2
   Compiling byteorder v1.4.3
   Compiling bitflags v1.3.2
   Compiling array_tool v1.0.3
   Compiling libc v0.2.100
   Compiling ryu v1.0.5
   Compiling num-traits v0.2.14
   Compiling serde v1.0.128
   Compiling log v0.4.14
   Compiling indexmap v1.7.0
   Compiling getrandom v0.1.16
   Compiling time v0.1.44
   Compiling rand_core v0.5.1
   Compiling num-integer v0.1.44
   Compiling redis-module v0.23.0
   Compiling rand_chacha v0.2.2
   Compiling chrono v0.4.19
   Compiling rand v0.7.3
   Compiling serde_json v1.0.66
   Compiling bson v0.14.1
   Compiling jsonpath_lib v0.2.6 (https://github.com/RedisJSON/jsonpath.git?branch=generic_json_path#14af7aa5)
   Compiling redisjson v99.99.99 (/home/topper/work/RedisJSON)
    Finished test [unoptimized + debuginfo] target(s) in 11.19s
     Running unittests (target/armv7-unknown-linux-gnueabihf/debug/deps/rejson-1904ab6883c9f070)
arm-binfmt-P: Could not open '/lib/ld-linux-armhf.so.3': No such file or directory
error: test failed, to rerun pass '--lib'
```
Anyway I've build with `cargo build --target armv7-unknown-linux-gnueabihf` or `cargo build --target armv7-unknown-linux-gnueabihf --realease`

```
$ file ./target/armv7-unknown-linux-gnueabihf/debug/librejson.so
./target/armv7-unknown-linux-gnueabihf/debug/librejson.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=6786ceee1448c5d48153f1978aea1c11715b53fc, with debug_info, not stripped
```
but when copied in dev-board with i.MX6Q

`Module /etc/redis/librejson.so failed to load: /lib/libm.so.6: version `GLIBC_2.29' not found (required by /etc/redis/librejson.so)`

How I could cross-compile it (static?) with desirable libc (on Yocto 2.6 that is libm-2.28.so)

**Comment by TopperBG** [comment]
Look at #475 for resolution:
https://github.com/RedisJSON/RedisJSON/issues/475#issuecomment-993889674
