### ISSUE TITLE
No way to escape/disambiguate search paths

### ISSUE THREAD

**Issue by mnunberg** [RedisJSON/RedisJSON#50]
1. There's no way to escape literal dots in the search path
2. There's no way to escape search keywords within the search path.

I'm unsure what the best solution here is. I'm tempted to add a new command which would have the 'correct' semantics, but this might be a bit overboard? on the other hand, there's absolutely no way to do the aforementioned things. This might not be a big problem now, but I can certainly see someone running into weird bugs in the future.

**Comment by itamarhaber** [comment]
@mnunberg I trust your instincts on this, and it would be good to gravitate towards something compatible with accepted path "standards"

**Comment by mnunberg** [comment]
I'll look into it. I believe json-pointer is far more bloated than it was when I used it initially (for a draft). There's another pathing syntax that i used for 'another company'

**Comment by dvirsky** [comment]
AFAIK foo["bar.baz"] will work perfectly, and if not it's a small change to the parser.

**Comment by dvirsky** [comment]
By reading the parser code, it is perfectly possible to use dots when using the `["..."]` notation, but backslash escaping is not supported. No big deal to add it to the parser.
