### ISSUE TITLE
cargo build --release  question

### ISSUE THREAD

**Issue by 2021-cm** [RedisJSON/RedisJSON#579]
![image](https://user-images.githubusercontent.com/34293473/146351116-6fb30d3e-8733-4a80-91e1-db90503bbb3a.png)
![image](https://user-images.githubusercontent.com/34293473/146351164-2e106486-71fa-4e44-b437-021bf836bb5d.png)

**Comment by gkorland** [comment]
It seems like you're missing clang on your machine.
https://www.unadulterated-faff.com/articles/2020/02/04/fixing-rust-compilation-issues-caused-by-missing-packages-part-2.html
