### ISSUE TITLE
load fatal

### ISSUE THREAD

**Issue by AntonyM55** [RedisJSON/RedisJSON#580]
[admin@Yosemite redis]$ export RUST_BACKTRACE=full
[admin@Yosemite redis]$ redis-server --loadmodule ./module/librejson.so
16292:C 17 Dec 2021 12:25:05.565 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
16292:C 17 Dec 2021 12:25:05.565 # Redis version=5.0.3, bits=64, commit=00000000, modified=0, pid=16292, just started
16292:C 17 Dec 2021 12:25:05.565 # Configuration loaded
16292:M 17 Dec 2021 12:25:05.566 * Increased maximum number of open files to 10032 (it was originally set to 1024).
                _._
           _.-``__ ''-._
      _.-``    `.  `_.  ''-._           Redis 5.0.3 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 16292
  `-._    `-._  `-./  _.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |           http://redis.io
  `-._    `-._`-.__.-'_.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |
  `-._    `-._`-.__.-'_.-'    _.-'
      `-._    `-.__.-'    _.-'
          `-._        _.-'
              `-.__.-'

16292:M 17 Dec 2021 12:25:05.567 # Server initialized
16292:M 17 Dec 2021 12:25:05.568 * <ReJSON> version: 20005 git sha:  branch:
16292:M 17 Dec 2021 12:25:05.568 * <ReJSON> Exported RedisJSON_V1 API
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/rnd/.cargo/registry/src/github.com-1ecc6299db9ec823/redis-module-0.24.0/src/raw.rs:614:42
stack backtrace:
   0:     0x7f65cad1781c - std::backtrace_rs::backtrace::libunwind::trace::hf6a6dfd7da937cb0
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7f65cad1781c - std::backtrace_rs::backtrace::trace_unsynchronized::hc596a19e4891f7f3
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f65cad1781c - std::sys_common::backtrace::_print_fmt::hb16700db31584325
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f65cad1781c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h231c4190cfa75162
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7f65cad3745c - core::fmt::write::h2a1462b5f8eea807
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/fmt/mod.rs:1163:17
   5:     0x7f65cad15ac5 - std::io::Write::write_fmt::h71ddfebc68685972
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/io/mod.rs:1696:15
   6:     0x7f65cad18d40 - std::sys_common::backtrace::_print::hcc197d4bebf2b369
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7f65cad18d40 - std::sys_common::backtrace::print::h335a66af06738c7c
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7f65cad18d40 - std::panicking::default_hook::{{closure}}::h6fac9ac9c8b79e52
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:210:50
   9:     0x7f65cad188f5 - std::panicking::default_hook::h341c1030c6a1161b
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:227:9
  10:     0x7f65cad193f4 - std::panicking::rust_panic_with_hook::h50680ff4b44510c6
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:624:17
  11:     0x7f65cad18ea2 - std::panicking::begin_panic_handler::{{closure}}::h9371c0fbb1e8465a
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:519:13
  12:     0x7f65cad17cc4 - std::sys_common::backtrace::__rust_end_short_backtrace::h9b3efa22a5768c0f
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x7f65cad18e39 - rust_begin_unwind
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
  14:     0x7f65cac608a1 - core::panicking::panic_fmt::h23b9203e89cc61cf
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
  15:     0x7f65cac607ed - core::panicking::panic::h0ba7146865b2f9d6
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:50:5
  16:     0x7f65cacde328 - core::option::Option<T>::unwrap::h502131de4ccf3a6a
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/option.rs:746:21
  17:     0x7f65cacde328 - redis_module::raw::export_shared_api::h36454ef6522ab5cd
                               at /home/rnd/.cargo/registry/src/github.com-1ecc6299db9ec823/redis-module-0.24.0/src/raw.rs:614:14
  18:     0x7f65cacde328 - redis_module::context::Context::export_shared_api::h83d00c05b8a0ae55
                               at /home/rnd/.cargo/registry/src/github.com-1ecc6299db9ec823/redis-module-0.24.0/src/context/mod.rs:255:9
  19:     0x7f65cacbd26e - rejson::export_shared_api::h8f5819207b9964f0
                               at /home/rnd/temp/RedisJSON-2.0.5/src/c_api.rs:556:13
  20:     0x7f65cacbd26e - rejson::intialize::hc3072fdd99ac9d82
                               at /home/rnd/temp/RedisJSON-2.0.5/src/lib.rs:411:13
  21:     0x7f65cacbd26e - RedisModule_OnLoad
                               at /home/rnd/.cargo/registry/src/github.com-1ecc6299db9ec823/redis-module-0.24.0/src/macros.rs:157:20
  22:     0x556dbffc4f80 - moduleLoad
  23:     0x556dbffc50db - moduleLoadFromQueue
  24:     0x556dbff441ed - main
  25:     0x7f65cd2d2493 - __libc_start_main
  26:     0x556dbff445ce - _start
  27:                0x0 - <unknown>
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)

**Comment by oshadmi** [comment]
@AntonyM55 Please use redis version 6.x for RedisJSON 2.x

**Comment by gkorland** [comment]
ref #582
