### ISSUE TITLE
Does RedisJSON support partial update like in ES ?

### ISSUE THREAD

**Issue by aqua7regia** [RedisJSON/RedisJSON#588]
Hi, just as the title question. I want to know does redisjson support update a json object partially?

In our case, we may update a document in ES just for one or some key value in this document, not the whole document, because the update program don't know how the whole document is.

**Comment by gkorland** [comment]
Please check the RedisJSON documentation: https://oss.redis.com/redisjson/commands/

e.g.
with [JSON.SET](https://oss.redis.com/redisjson/commands/#jsonset) - you can update specific elements in the JSON matching the provided jsonpath.
