### ISSUE TITLE
redis-server crashing after starting in 16.04 ubuntu 32 bit system

### ISSUE THREAD

**Issue by priyochatterjee08** [RedisJSON/RedisJSON#59]
![redise](https://user-images.githubusercontent.com/10290106/36059699-0b49c3fa-0e63-11e8-8e8d-355576bbbd8b.png)
![redise2](https://user-images.githubusercontent.com/10290106/36059700-0b8528d2-0e63-11e8-84a7-53909de27bf1.png)

**Comment by mnunberg** [comment]
Does this happen immediately after startup, or is this after you execute a specific command?

**Comment by priyochatterjee08** [comment]
I am using iorejson package. This error comes after executing 
instance.set('FromxyzAPI', '.', response.data, 'EX', 5);

**Comment by mnunberg** [comment]
Does this happen on a 64 bit system as well? in any event, I'm going to test it myself.

**Comment by priyochatterjee08** [comment]
Sorry, I have not tested on a 64 bit system.

**Comment by mnunberg** [comment]
I can't reproduce this unfortunately, even on a 32 bit system. I'm wondering if this has something to do with the rdb.

**Comment by itamarhaber** [comment]
@priyochatterjee08 I'm not too savvy wrt iorejson, but the command you've quoted doesn't seem to be support the `EX` syntax and afair neither does ReJSON itself.

That said, it would be helpful if you could open a `redis-cli monitor` session and then run the code. If the server borks, we'll get the command that borked it and can fix an ugly crash that should happen :)

**Comment by gkorland** [comment]
Not relevant any more
