### ISSUE TITLE
Using NX when setting to an existing array element returns index out of range

### ISSUE THREAD

**Issue by EricRabil** [RedisJSON/RedisJSON#592]
```
127.0.0.1:6379> json.set a . [{}]
OK
127.0.0.1:6379> json.set a [0] {}
OK
127.0.0.1:6379> json.set a [0] {} NX
(error) ERR array index out of range
```
This is impacting recovery logic in my application that scaffolds out missing parts of the tree. This also happens when you are NX'ing to an element that is neither at the beginning nor end of the array.

---
Fresh build of the latest code in master (2e6cbe4, to be exact), `Redis 6.2.6`, macOS Monterey 12.1 on an M1.

---
Relevant code is at https://github.com/RedisJSON/RedisJSON/blob/2e6cbe4b29d44a15712c3505146d39c04cc303af/src/commands.rs#L240-L317 – if the option is not AlreadyExists (i.e. NX or absent) `find_add_paths` is called, which will indiscriminately return the above error when that code path is hit. I'm trying to work on a fix, but I'm having a hard time figuring out the best way to work this in.

The best solution *I* can think off is just adding a check to see if the given index is valid before returning an Err.

---
I'm wondering if I'm abusing NX slightly, and that this may be expected behavior, as it'd be inappropriate to expect this module to grow the array when NX is present. However, I still do think this error should not be returned given a valid element is present - if there was no element and NX was supplied, the error would probably be right to surface. Either that or NX for array elements becomes outright disallowed.

**Comment by oshadmi** [comment]
Fixed by #593
