### ISSUE TITLE
Running `make` on the repository errors out and stops.

### ISSUE THREAD

**Issue by i-am-zaidali** [RedisJSON/RedisJSON#599]
So i wanted to install the RedisJSON extension for redis on my Ubuntu 20.04 system and i followed the instructions for building it in the docs. Upon cloning the repository and running `make` on it, It immediately errors out and this is the display

![error](https://pls-help.me/raw/COxcKy0Hn_QAgKz-/1d6Ses44.png)

Now i dont know how to fix this, any assistance is appreciated

**Comment by rafie** [comment]
Hello @i-am-zaidali,
To build RedisJSON, please run the following commands:
```
./deps/readies/getpy3
./sbin/system-setup.py
make
```

**Comment by i-am-zaidali** [comment]
> Hello @i-am-zaidali, To build RedisJSON, please run the following commands:
> 
> ```
> ./deps/readies/getpy3
> ./sbin/system-setup.py
> make
> ```

Hmmmm it says that the file `getpy3` does not exist. Upon using explorer to look into the deps folder, it dhows up as empty too

**Comment by i-am-zaidali** [comment]
it automatically fixed itself after recloning the repo so i will be closing this issue
