### ISSUE TITLE
Redis rejson , get multiple elements from array

### ISSUE THREAD

**Issue by ghost** [RedisJSON/RedisJSON#60]
i have json Array stored in redis with rejson.

    Now for example only need 2 elements from the array how do i get it?

Am using node.js with iorejson client for node.

I would prefer not to encapsulate the entire code in a loop in order to get number of article desired.

as you see below i can only query one article at the time ".article[1]" or all by doing this ".article"

 ```
   var json =  p.get("stories", ".article[1]");
json.then(function(value) {
  console.log(value);
  // expected output: "Success!"
}).catch(function(rej) {
      //rejected
      console.log(rej);
    });
```

**Comment by mnunberg** [comment]
I don't know about iorejson, but you should be able to get multiple paths normally, e.g. `".article[1]", "article[2]"` etc.

**Comment by PolHaghverdian** [comment]
No that dosnt work. 

I think my only option is to fetch the entire array.

**Comment by mnunberg** [comment]
```
127.0.0.1:7777> JSON.SET somekey . '{"a":[1,2,3,4,5,6,7,8]}'
OK
127.0.0.1:7777> JSON.GET somekey .a[0] .a[1]
"{\".a[0]\":1,\".a[1]\":2}"
```

Note that in order to get the first result, you need to use `".a[0]"` itself as a key.

**Comment by PolHaghverdian** [comment]
Sorry, but do you mean something like this: `var json =  p.get("stories", ".article[0] .article[1]");`

```
  message: 'ERR Search path error at offset 12: an identifier can only begin with a letter, a dollar sign or an underscore - use bracket notation for anything else',
  command:
   { name: 'JSON.GET',
     args: [ 'stories', '.article[0] .article[1]' ] } }
```

**Comment by mnunberg** [comment]
It does not appear that iorejson accepts this syntax at this time, though it should, I've filed an issue on your behalf:

https://github.com/evanhuang8/iorejson/issues/4

**Comment by itamarhaber** [comment]
x-ref: https://stackoverflow.com/questions/48905731/redis-rejson-get-multiple-elements-from-array

**Comment by gkorland** [comment]
RedisJSON now supports full JSONPath e.g.

```
127.0.0.1:6379> JSON.SET somekey . '{"a":[1,2,3,4,5,6,7,8]}'
OK
127.0.0.1:6379> json.get somekey $.a[1,3]
"[2,4]"
127.0.0.1:6379> json.get somekey $.a[0,5,6]
"[1,6,7]"
```
