### ISSUE TITLE
Does not support MsgPack

### ISSUE THREAD

**Issue by RekaDowney** [RedisJSON/RedisJSON#604]
question: Does not support MsgPack

Redis Version: `6.2.5`
RediSearch Version: `2.2.5`
![rejson](https://user-images.githubusercontent.com/24631388/147907282-e91f2dd6-5c5c-4b3c-a7fc-763f80f21fac.png)

description: 
I used the following command to start RedisJSON in Docker, 

`docker run -p 6379:6379 --name redis-redisjson redislabs/rejson:latest`

and then tried to use `Redisson` `MsgPackJacksonCodec` or `ByteArrayCodec` for access RedisJSON, but found access failed not matter which `Codec`.

It seems that `RedisJSON` currently does not support `msgpack`. I am wondering if it only supports `String`, and is there any plan to support `msgpack` in the future?

**Comment by RekaDowney** [comment]
The exception like this:
![image](https://user-images.githubusercontent.com/24631388/147907993-ad8dcd7d-643e-4da1-ae05-739efd5d0828.png)

**Comment by gkorland** [comment]
RedisJSON currently only support passing JSON as a String. 
There is a pending draft PR to add support for BSON see: dhttps://github.com/RedisJSON/RedisJSON/pull/577.

MsgPack might follow, can you please extend why do you need MsgPack support?

**Comment by RekaDowney** [comment]
> RedisJSON currently only support passing JSON as a String. There is a pending draft PR to add support for BSON see: dhttps://github.com/[/pull/577](https://github.com/RedisJSON/RedisJSON/pull/577).
> 
> MsgPack might follow, can you please extend why do you need MsgPack support?

@gkorland Thank you for your reply, which answered my doubts. 
Our JSON object is very large. One object occupies about 150M of JVM memory, so We hope `msgpack` can reduce the memory usage.

**Comment by gkorland** [comment]
Notice RedisJSON doesn't keep the JSON in string format, it's only being used as command argument.
Also, the way JSONs are saved by default in the JVM are highly inefficient.
RedisJSON uses https://github.com/Diggsey/ijson to keep the document in memory.

I suggest you'll try to load such JSON and test.

**Comment by RekaDowney** [comment]
Got it, we will have a try. Thanks a lot.
