### ISSUE TITLE
Bug report using rejson module 

### ISSUE THREAD

**Issue by jeremy-moore** [RedisJSON/RedisJSON#61]
1:C 21 Feb 06:10:59.107 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 21 Feb 06:10:59.107 # Redis version=4.0.1, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 21 Feb 06:10:59.107 # Configuration loaded
1:M 21 Feb 06:10:59.107 * Running mode=standalone, port=6379.
1:M 21 Feb 06:10:59.107 # Server initialized
1:M 21 Feb 06:10:59.107 # <ReJSON> JSON data type for Redis v1.0.1 [encver 0]
1:M 21 Feb 06:10:59.107 * Module 'ReJSON' loaded from /usr/lib/redis/modules/rejson.so
1:M 21 Feb 06:10:59.107 * Ready to accept connections

=== REDIS BUG REPORT START: Cut & paste starting from here ===
*** Error in `redis-server *:6379': free(): invalid pointer: 0x0000000000b704d4 ***
1:M 21 Feb 06:15:27.891 # Redis 4.0.1 crashed by signal: 11
1:M 21 Feb 06:15:27.891 # Crashed running the instuction at: 0x7f29e1682532
1:M 21 Feb 06:15:27.891 # Accessing address: (nil)
1:M 21 Feb 06:15:27.891 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
/lib/x86_64-linux-gnu/libc.so.6(abort+0x232)[0x7f29e1682532]

Backtrace:
redis-server *:6379(logStackTrace+0x29)[0x467a89]
redis-server *:6379(sigsegvHandler+0xa6)[0x468126]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xf890)[0x7f29e1a06890]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x232)[0x7f29e1682532]
/lib/x86_64-linux-gnu/libc.so.6(+0x731b4)[0x7f29e16bf1b4]
/lib/x86_64-linux-gnu/libc.so.6(+0x7898e)[0x7f29e16c498e]
/lib/x86_64-linux-gnu/libc.so.6(+0x79696)[0x7f29e16c5696]
/usr/lib/redis/modules/rejson.so(+0x6465)[0x7f29df7e8465]

------ INFO OUTPUT ------
# Server
redis_version:4.0.1
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:ac6c9ffb15b04a74
redis_mode:standalone
os:Linux 4.9.60-linuxkit-aufs x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:4.9.2
process_id:1
run_id:80ed610f3db494ed197698d0960071111c1e4b71
tcp_port:6379
uptime_in_seconds:268
uptime_in_days:0
hz:10
lru_clock:9244287
executable:/data/redis-server
config_file:

# Clients
connected_clients:1
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:1217928
used_memory_human:1.16M
used_memory_rss:4640768
used_memory_rss_human:4.43M
used_memory_peak:1217928
used_memory_peak_human:1.16M
used_memory_peak_perc:100.53%
used_memory_overhead:825590
used_memory_startup:765592
used_memory_dataset:392338
used_memory_dataset_perc:86.74%
total_system_memory:6246981632
total_system_memory_human:5.82G
used_memory_lua:37888
used_memory_lua_human:37.00K
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
mem_fragmentation_ratio:3.81
mem_allocator:jemalloc-4.0.3
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1519193459
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0

# Stats
total_connections_received:2
total_commands_processed:1062
instantaneous_ops_per_sec:73
total_net_input_bytes:165284
total_net_output_bytes:210320
instantaneous_input_kbps:10.91
instantaneous_output_kbps:12.67
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
evicted_keys:0
keyspace_hits:618
keyspace_misses:208
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:0
master_replid:02d014ce08a9b63bdcd5878a45d17f59f3e8509b
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.19
used_cpu_user:0.08
used_cpu_sys_children:0.00
used_cpu_user_children:0.00

# Commandstats
cmdstat_select:calls=3,usec=3,usec_per_call=1.00
cmdstat_info:calls=3,usec=106,usec_per_call=35.33

# Cluster
cluster_enabled:0

# Keyspace
db2:keys=208,expires=0,avg_ttl=0

------ CLIENT LIST OUTPUT ------
id=3 addr=172.17.0.1:39676 fd=8 name= age=41 idle=0 flags=N db=2 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=json.set

------ CURRENT CLIENT INFO ------
id=3 addr=172.17.0.1:39676 fd=8 name= age=41 idle=0 flags=N db=2 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=json.set
argv[0]: 'JSON.SET'
argv[1]: 'calendar:745fcaf2-3507-4843-8f5a-0d63495f419d'
argv[2]: '.'
argv[3]: '{"events":[{"start":"2018-02-01T09:30:00.000Z","end":"2018-02-01T10:00:00.000Z","resources":{"places":{"qty":12,"use":12},"adults":{"qty":10,"use":10},"children":{"qty":2,"use":2},"infants":{"qty":2}}},{"start":"2018-02-01T09:00:00.000Z","end":"2018-02-01T09:30:00.000Z","resources":{"places":{"qty":12,"use":12},"adults":{"qty":10,"use":10},"children":{"qty":2,"use":2},"infants":{"qty":2}}},{"start":"2018-02-01T10:00:00.000Z","end":"2018-02-01T10:30:00.000Z","resources":{"places":{"qty":12,"use":12},"adults":{"qty":10,"use":10},"children":{"qty":2,"use":2},"infants":{"qty":2}}}]}'

------ REGISTERS ------
1:M 21 Feb 06:15:27.892 # 
RAX:0000000000000006 RBX:0000000000000054
RCX:00007f29e1681067 RDX:0000000000000006
RDI:0000000000000001 RSI:0000000000000001
RBP:00007ffdba2112a0 RSP:00007ffdba210f10
R8 :0000000000000000 R9 :00007ffdba210e60
R10:0000000000000008 R11:0000000000000202
R12:00007ffdba2110b0 R13:0000000000000007
R14:0000000000000054 R15:0000000000000007
RIP:00007f29e1682532 EFL:0000000000010246
CSGSFS:002b000000000033
1:M 21 Feb 06:15:27.892 # (00007ffdba210f1f) -> 0000000000000000
1:M 21 Feb 06:15:27.892 # (00007ffdba210f1e) -> 0000000000000000
1:M 21 Feb 06:15:27.892 # (00007ffdba210f1d) -> 0000000000000000
1:M 21 Feb 06:15:27.892 # (00007ffdba210f1c) -> 0000000000000000
1:M 21 Feb 06:15:27.892 # (00007ffdba210f1b) -> 0000000000000000
1:M 21 Feb 06:15:27.892 # (00007ffdba210f1a) -> 0000000000000000
1:M 21 Feb 06:15:27.892 # (00007ffdba210f19) -> 0000000000000000
1:M 21 Feb 06:15:27.892 # (00007ffdba210f18) -> 0000000000000000
1:M 21 Feb 06:15:27.892 # (00007ffdba210f17) -> 0000000000000000
1:M 21 Feb 06:15:27.892 # (00007ffdba210f16) -> 0000000000000000
1:M 21 Feb 06:15:27.892 # (00007ffdba210f15) -> 0000000000000000
1:M 21 Feb 06:15:27.892 # (00007ffdba210f14) -> 0000000000000000
1:M 21 Feb 06:15:27.892 # (00007ffdba210f13) -> 0000000000000000
1:M 21 Feb 06:15:27.892 # (00007ffdba210f12) -> 0000000000000000
1:M 21 Feb 06:15:27.892 # (00007ffdba210f11) -> 0000000000000000
1:M 21 Feb 06:15:27.892 # (00007ffdba210f10) -> 0000000000000020

------ FAST MEMORY TEST ------
1:M 21 Feb 06:15:27.892 # Bio thread for job type #0 terminated
1:M 21 Feb 06:15:27.892 # Bio thread for job type #1 terminated
1:M 21 Feb 06:15:27.893 # Bio thread for job type #2 terminated
*** Preparing to test memory region 752000 (94208 bytes)
*** Preparing to test memory region b47000 (266240 bytes)
*** Preparing to test memory region 7f29df9fe000 (8388608 bytes)
*** Preparing to test memory region 7f29e01ff000 (8388608 bytes)
*** Preparing to test memory region 7f29e0a00000 (12582912 bytes)
*** Preparing to test memory region 7f29e19f3000 (16384 bytes)
*** Preparing to test memory region 7f29e1c10000 (16384 bytes)
*** Preparing to test memory region 7f29e2330000 (24576 bytes)
*** Preparing to test memory region 7f29e2336000 (12288 bytes)
*** Preparing to test memory region 7f29e233b000 (4096 bytes)
.O.O.O.O.O.O.O.O.O.O
Fast memory test PASSED, however your memory can still be broken. Please run a memory test for several hours if possible.

------ DUMPING CODE AROUND EIP ------
Symbol: abort (base: 0x7f29e1682300)
Module: /lib/x86_64-linux-gnu/libc.so.6 (base 0x7f29e164c000)
$ xxd -r -p /tmp/dump.hex /tmp/dump.bin
$ objdump --adjust-vma=0x7f29e1682300 -D -b binary -m i386:x86-64 /tmp/dump.bin
------
1:M 21 Feb 06:15:27.955 # dump of function (hexdump of 690 bytes):
4881ec2801000064488b142510000000483b15010937007434be0100000031c0833dad443700007410f00fb135df0837000f8510020000eb0d0fb135d00837000f8501020000488915cb0837008b05cd0837008305ba0837000185c0744583f801747983f8020f849000000083f803900f841f01000083f8040f847201000083f8050f848701000083f8060f84a101000083f8070f8499010000660f1f440000f4ebfd31c0b9100000004889e7f348ab31d24889e6bf01000000c7055c0837000100000048c7042420000000e82fefffff8b054908370083f801758731ffc7053808370002000000e8930304008b052d08370083f8020f8570ffffff832d1108370001c7051308370000000000752f48c705fe07370000000000833db343370000740ff0ff0de60737000f8536010000eb0cff0dd80737000f8528010000bf06000000e8e8ebffff64488b142510000000483b15c00737007434be0100000031c0833d6c433700007410f00fb1359e0737000f850d010000eb0d0fb1358f0737000f85fe0000004889158a07370083057f07370001488d942480000000b91300000031c0c70572073700040000004889d7488db280000000f348ab48c706ffffffff4883ee084839d675f031d2bf06000000c784240801000000000000e8feedffff8b053807370083f8040f858efeffffc7052507370005000000e8b0c203008b051a07370083f8050f8579feffffbf06000000c7050207370006000000e80debffff8b05f706370083f8060f855ffefffff4bf7f000000c705de06370008000000e8693d0800488d3dc20637004881ec80000000e836e60b004881c480000000e9e0fdffff488d3da30637004881ec80000000e847e60b004881c480000000e9b9feffff488d3d840637004881ec80000000e8f8e50b004881c480000000e9e3feffff662e0f1f84000000000066904157
Function at 0x7f29e1681300 is sigprocmask
Function at 0x7f29e1681030 is gsignal
Function at 0x7f29e16812e0 is sigaction
Function at 0x7f29e16be7b0 is fcloseall
Function at 0x7f29e17062b0 is _exit

=== REDIS BUG REPORT END. Make sure to include from START to END. ===

       Please report the crash by opening an issue on github:

           http://github.com/antirez/redis/issues

**Comment by jeremy-moore** [comment]
I opened issue on http://github.com/antirez/redis/issues
The told me the problem was in rejson module and to open an issue here.

**Comment by dvirsky** [comment]
This is the right address indeed. Is this when running the module tests or when running your app?

**Comment by jeremy-moore** [comment]
When running tests on my app.

**Comment by jeremy-moore** [comment]
It seems to be when updating the same key multiple times.

**Comment by itamarhaber** [comment]
> *** Error in `redis-server *:6379': corrupted double-linked list

Never seen this error in Redis or ReJSON.

**Comment by jeremy-moore** [comment]
Yes seems to be interfering with redis internal data structure - it uses gcc double linked list I think.
Maybe resetting key with growing size object overwrites memory
Or maybe something to do with dates seems to convert to strings

**Comment by itamarhaber** [comment]
> Yes seems to be interfering with redis internal data structure - it uses gcc double linked list I think.
Unlikely imo.

Could you repeat the test w/ the newest Redis version (4.0.1 is old-ish)? Also, is it possible to get a script that reproduces the crash or the actual dump? #askingforafriend

**Comment by jeremy-moore** [comment]
I am using docker redislabs/rejson:latest

**Comment by itamarhaber** [comment]
"corrupted double-linked list" is a malloc thing... now who's using malloc in Redis/ReJSON? Afair there weren't any such and everything is jemalloc. Could be wrong though.

**Comment by mnunberg** [comment]
Can you see if the master branch works for you?
On Feb 21, 2018 4:26 PM, Jeremy Moore <notifications@github.com> wrote:When running tests on my app.

**Comment by jeremy-moore** [comment]
ok I will try that

**Comment by jeremy-moore** [comment]
Ok I used redis 4.0.8 and built and loaded master rejson module
success!
Thank you for your help.

ps. maybe someone should update DockerHub (https://hub.docker.com/r/redislabs/rejson/)
