### ISSUE TITLE
Fix "feature edition2021 is required"

### ISSUE THREAD

**Issue by RedstoneWizard08** [RedisJSON/RedisJSON#616]
name: Bug Report
description: File a bug report
title: "[Bug]: Fix error when running cargo build."
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: operating_system
    attributes:
      label: OS
      description: Ubuntu

  - type: architecutre
    id: cpu_arch
    attributes:
      label: CPU Architecture
      description: arm64

  - type: input
    id: redis_version
    attributes:
      label: Redis Server Version
      description: 6.0.6

  - type: input
    id: redis_module_version
    attributes:
      label: Redis Module Version
      description: Not installed.

  - type: input
    id: was_redis_docker
    attributes:
      label: Docker Installation
      description: Docker v20.10.12

  - type: checkboxes
    id: installmethod
    attributes:
      label: Docker installation
      description: Check this box, if you installed the release via a docker.
      options:
        - label: I installed via PPA (chris-lea/redia-server)

  - type: textarea
    id: whathappened
    label: What happened?
    description: When I was building RedisJSON with "cargo build" it gave me an error.

  - type: textarea
    id: logs
    label: Relevant log output
    description:
```
error: failed to parse manifest at `/home/ubuntu/redis/RedisJSON/Cargo.toml`

Caused by:
  feature `edition2021` is required

  consider adding `cargo-features = ["edition2021"]` to the manifest
```
    render: shell

**Comment by RedstoneWizard08** [comment]
Fix is to add `cargo-features = ["edition2021"]` to the top of the `Cargo.toml` file.

**Comment by gkorland** [comment]
thanks, strange it works in the CI without issues.

**Comment by gkorland** [comment]
@RedstoneWizard08 did you just try to update your rust version? 
```
warning: the cargo feature `edition2021` has been stabilized in the 1.56 release and is no longer necessary to be listed in the manifest
  See https://doc.rust-lang.org/nightly/cargo/reference/manifest.html#the-edition-field for more information about using this feature.
```

**Comment by kornelski** [comment]
A tip from the future: do **not** add `cargo-features = ["edition2021"]` anywhere. It's now obsolete, and will break builds.

What you need to do is upgrade Rust to v1.56 or later. If you're stuck with an outdated Rust package from a Linux distro: uninstall it, and install Rust via https://rustup.rs instead
