### ISSUE TITLE
Unable to load RedisJSON into redis

### ISSUE THREAD

**Issue by 1003020910** [RedisJSON/RedisJSON#627]
name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: operating_system
    attributes:
      label: OS
      description: Operating system and version (eg Ubuntu 20.04, OSX Catalina)
      placeholder: centos8

  - type: architecutre
    id: cpu_arch
    attributes:
      label: CPU Architecture
      description: CPU Architecture (eg: x86, x86-64, arm, etc).
      placeholder: x86

  - type: input
    id: redis_version
    attributes:
      label: Redis Server Version
      description: What version of redis-server are you running (redis-server --version)
      placeholder: 6.2.6

  - type: input
    id: redis_module_version
    attributes:
      label: Redis Module Version
      description: What version of this redis module was installed?
      placeholder: 2.0.6

  - type: textarea
    id: whathappened
    label: What happened?
    description: Please tell us what happened, and what you expected to happen.
    placeholder: 我想将RedisJSON模块加载到redis中，但是无法加载，我尝试了两种方式，分别是修改redis.conf配置文件及通过命令启动rendis时加入模块，但是都无法加载.

  - type: textarea
    id: logs
    label: Relevant log output
    description: If release, please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
    render: 我观察日志发现有以下报错信息：
Module /usr/local/redis/module/librejson.so failed to load: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/redis/module/librejson.so)
这貌似是一个版本问题，我目前使用的redis版本为6.2.6，我使用的RedisJSON版本为2.0.6.

**Comment by gkorland** [comment]
The error is pretty clear: `GLIBC_2.29' not found

How did you get the module binaries? (dowanload or built yourself?) 
If you build it did you build it on the same machine you're running it on?

**Comment by 1003020910** [comment]
I build it myself,but I downloaded the source package from git,and the version is 2.0.6.

**Comment by 1003020910** [comment]
I found the problem, when compiling requires GLIBC_2.29, but I don't have this version in my environment, so the module cannot be loaded. Does the code specify GLIBC_2.29 as the version under compilation?

**Comment by 1003020910** [comment]
My problem has been solved, the reason is that the glibc version on my server is 2.28, but I compiled the source code on another machine, and the compiled glibc version is 2.29, so I put the compiled file in my own When on the server, the module cannot be loaded into redis normally, thank you very much.
