### ISSUE TITLE
Build Issue from Source

### ISSUE THREAD

**Issue by shannonantony** [RedisJSON/RedisJSON#631]
I get following error while trying to build RedisJSON from source

[root@gaproxy01 RedisJSON-2.0.6]# cargo build --release --verbose
WARN rustc_codegen_ssa::back::link Linker does not support -no-pie command line option. Retrying without.
       Fresh autocfg v1.0.1
WARN rustc_codegen_ssa::back::link Linker does not support -no-pie command line option. Retrying without.
       Fresh unicode-xid v0.2.2
WARN rustc_codegen_ssa::back::link Linker does not support -no-pie command line option. Retrying without.
WARN rustc_codegen_ssa::back::link Linker does not support -no-pie command line option. Retrying without.
       Fresh glob v0.3.0
       Fresh cfg-if v1.0.0
       Fresh version_check v0.9.3
WARN rustc_codegen_ssa::back::link Linker does not support -no-pie command line option. Retrying without.
WARN rustc_codegen_ssa::back::link Linker does not support -no-pie command line option. Retrying without.
WARN rustc_codegen_ssa::back::link Linker does not support -no-pie command line option. Retrying without.
WARN rustc_codegen_ssa::back::link Linker does not support -no-pie command line option. Retrying without.
       Fresh minimal-lexical v0.2.1
       Fresh cc v1.0.72
       Fresh regex-syntax v0.6.25
       Fresh unicode-width v0.1.9
WARN rustc_codegen_ssa::back::link Linker does not support -no-pie command line option. Retrying without.
WARN rustc_codegen_ssa::back::link Linker does not support -no-pie command line option. Retrying without.
       Fresh humantime v2.1.0
       Fresh strsim v0.8.0
       Fresh ansi_term v0.12.1
       Fresh vec_map v0.8.2
       Fresh hashbrown v0.11.2
       Fresh termcolor v1.1.2
WARN rustc_codegen_ssa::back::link Linker does not support -no-pie command line option. Retrying without.
       Fresh itoa v1.0.1
       Fresh lazycell v1.3.0
       Fresh peeking_take_while v0.1.2
       Fresh unicode-xid v0.0.4
WARN rustc_codegen_ssa::back::link Linker does not support -no-pie command line option. Retrying without.
       Fresh ryu v1.0.9
       Fresh shlex v1.1.0
       Fresh rustc-hash v1.1.0
       Fresh gimli v0.26.1
WARN rustc_codegen_ssa::back::link Linker does not support -no-pie command line option. Retrying without.
       Fresh ppv-lite86 v0.2.15
       Fresh adler v1.0.2
       Fresh unicode-segmentation v1.8.0
       Fresh quote v0.3.15
       Fresh rustc-demangle v0.1.21
       Fresh lazy_static v1.4.0
       Fresh byteorder v1.4.3
       Fresh either v1.6.1
       Fresh md5 v0.6.1
       Fresh hex v0.3.2
WARN rustc_codegen_ssa::back::link Linker does not support -no-pie command line option. Retrying without.
       Fresh array_tool v1.0.3
       Fresh bitflags v1.3.2
       Fresh linked-hash-map v0.5.4
WARN rustc_codegen_ssa::back::link Linker does not support -no-pie command line option. Retrying without.
WARN rustc_codegen_ssa::back::link Linker does not support -no-pie command line option. Retrying without.
WARN rustc_codegen_ssa::back::link Linker does not support -no-pie command line option. Retrying without.
WARN rustc_codegen_ssa::back::link Linker does not support -no-pie command line option. Retrying without.
WARN rustc_codegen_ssa::back::link Linker does not support -no-pie command line option. Retrying without.
       Fresh libloading v0.7.2
WARN rustc_codegen_ssa::back::link Linker does not support -no-pie command line option. Retrying without.
WARN rustc_codegen_ssa::back::link Linker does not support -no-pie command line option. Retrying without.
       Fresh textwrap v0.11.0
       Fresh synom v0.11.3
       Fresh addr2line v0.17.0
       Fresh heck v0.3.3
       Fresh itertools v0.10.3
       Fresh proc-macro2 v1.0.33
       Fresh libc v0.2.112
       Fresh memchr v2.4.1
       Fresh rustversion v1.0.6
       Fresh syn v0.11.11
       Fresh log v0.4.14
       Fresh quote v1.0.10
       Fresh atty v0.2.14
       Fresh aho-corasick v0.7.18
       Fresh getrandom v0.1.16
       Fresh which v4.2.2
       Fresh num_cpus v1.13.0
       Fresh time v0.1.44
       Fresh indexmap v1.7.0
       Fresh num-traits v0.2.14
       Fresh miniz_oxide v0.4.4
       Fresh nom v7.1.0
       Fresh clang-sys v1.3.0
       Fresh object v0.27.1
       Fresh syn v1.0.82
       Fresh regex v1.5.4
       Fresh clap v2.34.0
       Fresh rand_core v0.5.1
       Fresh dashmap v4.0.2
       Fresh num-integer v0.1.44
       Fresh num-traits v0.1.43
       Fresh cexpr v0.6.0
       Fresh backtrace v0.3.63
       Fresh serde_derive v1.0.131
       Fresh env_logger v0.9.0
       Fresh rand_chacha v0.2.2
       Fresh strum_macros v0.23.1
       Fresh chrono v0.4.19
       Fresh enum-primitive-derive v0.1.2
       Fresh serde v1.0.131
       Fresh bindgen v0.59.2
       Fresh rand v0.7.3
       Fresh serde_json v1.0.73
WARN rustc_codegen_ssa::back::link Linker does not support -no-pie command line option. Retrying without.
       Fresh ijson v0.1.3
       Fresh bson v0.14.1
   Compiling redis-module v0.25.0
   Compiling jsonpath_lib v0.2.6 (https://github.com/RedisJSON/jsonpath.git?branch=generic_json_path#19804333)
     Running `/apps/redis/RedisJSON-2.0.6/target/release/build/redis-module-09f732bfe54d22e8/build-script-build`
     Running `rustc --crate-name jsonpath_lib /root/.cargo/git/checkouts/jsonpath-460f61b399667c09/1980433/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type cdylib --crate-type rlib --emit=dep-info,link -C opt-level=3 -C embed-bitcode=no -C debuginfo=1 -C metadata=23c47b771b71b4f5 -C extra-filename=-23c47b771b71b4f5 --out-dir /apps/redis/RedisJSON-2.0.6/target/release/deps -L dependency=/apps/redis/RedisJSON-2.0.6/target/release/deps --extern array_tool=/apps/redis/RedisJSON-2.0.6/target/release/deps/libarray_tool-984c00cfc7fd5aeb.rlib --extern ijson=/apps/redis/RedisJSON-2.0.6/target/release/deps/libijson-033e611ed6aab18b.rlib --extern log=/apps/redis/RedisJSON-2.0.6/target/release/deps/liblog-1adacbe32b2be4e4.rlib --extern serde=/apps/redis/RedisJSON-2.0.6/target/release/deps/libserde-853329a36f327261.rlib --extern serde_json=/apps/redis/RedisJSON-2.0.6/target/release/deps/libserde_json-95a97d309ff52cde.rlib --cap-lints allow -L deps/readies/wd40/linux-x64`
error: failed to run custom build command for `redis-module v0.25.0`

Caused by:
  process didn't exit successfully: `/apps/redis/RedisJSON-2.0.6/target/release/build/redis-module-09f732bfe54d22e8/build-script-build` (exit status: 101)
  --- stdout
  TARGET = Some("x86_64-unknown-linux-gnu")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "src/include/" "-Wall" "-Wextra" "-DREDISMODULE_EXPERIMENTAL_API" "-o" "/apps/redis/RedisJSON-2.0.6/target/release/build/redis-module-a042cb73b19c7027/out/src/redismodule.o" "-c" "src/redismodule.c"
  exit status: 0
  AR_x86_64-unknown-linux-gnu = None
  AR_x86_64_unknown_linux_gnu = None
  HOST_AR = None
  AR = None
  running: "ar" "cq" "/apps/redis/RedisJSON-2.0.6/target/release/build/redis-module-a042cb73b19c7027/out/libredismodule.a" "/apps/redis/RedisJSON-2.0.6/target/release/build/redis-module-a042cb73b19c7027/out/src/redismodule.o"
  exit status: 0
  running: "ar" "s" "/apps/redis/RedisJSON-2.0.6/target/release/build/redis-module-a042cb73b19c7027/out/libredismodule.a"
  exit status: 0
  cargo:rustc-link-lib=static=redismodule
  cargo:rustc-link-search=native=/apps/redis/RedisJSON-2.0.6/target/release/build/redis-module-a042cb73b19c7027/out

  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "the `libclang` shared library at /usr/lib64/clang-private/libclang.so.7 could not be opened: libclangAST.so.7: cannot open shared object file: No such file or directory"', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.59.2/src/lib.rs:2144:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

please help

thanks

Jay

**Comment by gkorland** [comment]
@shannonantony as the error points it seems like you don't have clang installed.
```
thread 'main' panicked at 'Unable to find libclang: "the libclang shared library at /usr/lib64/clang-private/libclang.so.7 could not be opened: libclangAST.so.7
```

You can either run 

```
sudo make setup
```
Or install clang

```
sudo apt-get install libclang-dev
```
