### ISSUE TITLE
feature request: get all keys at root ($)

### ISSUE THREAD

**Issue by marsonya** [RedisJSON/RedisJSON#642]
How about adding a command to return all the keys at root($)?
If yes, I would like to work on implementing it and create a PR.

**Comment by K-Jo** [comment]
Isn't this what you're looking for? https://oss.redis.com/redisjson/commands/#jsonobjkeys

**Comment by marsonya** [comment]
I was searching for command to fetch the root level keys.
JSON.OBJKEYS return keys inside a specific root key right?

**Comment by oshadmi** [comment]
@marsonya the command [JSON.OBJKEYS](https://oss.redis.com/redisjson/commands/#jsonobjkeys) returns the keys of an object which is found at the given path.
If the path is the root element `$` (or if path is missing) then the keys of the root object would be returned. If the path leads to a nested object, then the keys of this nested object would be returned.

**Comment by marsonya** [comment]
In `JSON.OBJKEYS key [path]`, `$` will be the `path`.
What will be the `key` when we want to fetch all the keys at root?

**Comment by oshadmi** [comment]
The term `key` in this context is a redis key, for example, `key:A` and `key:B`,
Or a `key/value` pair of an object/dictionary, e.g., `width`, `height`, etc.
```
127.0.0.1:6379> JSON.SET key:A $ '{"size":{"width":10, "height":10}, "pos":{"pos_x":20, "pos_y":30}, "zoom":100}'
OK
127.0.0.1:6379> JSON.SET key:B $ '{"size":{"width":30, "height":20}, "pos":{"pos_x":120, "pos_y":30}, "zoom":120}'
OK
127.0.0.1:6379> JSON.GET key:A '$.size.width'
"[10]"
127.0.0.1:6379> JSON.GET key:B '$.size.width'
"[30]"
```

The command expects a redis key, such as `key:A`, and returns all the object/dictionary keys at the given path:
```
127.0.0.1:6379> JSON.OBJKEYS key:A $
1) 1) "size"
   2) "pos"
   3) "zoom"
127.0.0.1:6379> JSON.OBJKEYS key:A $.size
1) 1) "width"
   2) "height"

```
