### ISSUE TITLE
modules not load when i use requirepass in docker

### ISSUE THREAD

**Issue by cetin** [RedisJSON/RedisJSON#645]
Hi,
When I use requirepass for docker it couldn't load ReJSON and search modules.
I also checked with redis-cli and I got this error "unknown command `JSON.SET`, with args beginning with: ".

These are docker run logs.

**without requirepass**

1:C 03 Feb 2022 18:50:09.876 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 03 Feb 2022 18:50:09.876 # Redis version=6.2.5, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 03 Feb 2022 18:50:09.876 # Configuration loaded
1:M 03 Feb 2022 18:50:09.877 * monotonic clock: POSIX clock_gettime
1:M 03 Feb 2022 18:50:09.877 * Running mode=standalone, port=6379.
1:M 03 Feb 2022 18:50:09.877 # Server initialized
1:M 03 Feb 2022 18:50:09.877 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 03 Feb 2022 18:50:09.878 * <ReJSON> version: 20006 git sha: db3329c branch: heads/v2.0.6
1:M 03 Feb 2022 18:50:09.878 * <ReJSON> Exported RedisJSON_V1 API
1:M 03 Feb 2022 18:50:09.878 * <ReJSON> Enabled diskless replication
1:M 03 Feb 2022 18:50:09.878 * <ReJSON> Created new data type 'ReJSON-RL'
1:M 03 Feb 2022 18:50:09.878 * **Module 'ReJSON' loaded from /usr/lib/redis/modules/rejson.so**
1:M 03 Feb 2022 18:50:09.878 * <search> Redis version found by RedisSearch : 6.2.5 - oss
1:M 03 Feb 2022 18:50:09.878 * <search> RediSearch version 2.2.5 (Git=v1.99.5-386-g93a916c4)
1:M 03 Feb 2022 18:50:09.878 * <search> Low level api version 1 initialized successfully
1:M 03 Feb 2022 18:50:09.878 * <search> concurrent writes: OFF, gc: ON, prefix min length: 2, prefix max expansions: 200, query timeout (ms): 500, timeout policy: return, cursor read size: 1000, cursor max idle (ms): 300000, max doctable size: 1000000, max number of search results:  1000000, search pool size: 20, index pool size: 8, 
1:M 03 Feb 2022 18:50:09.879 * <search> Initialized thread pool!
1:M 03 Feb 2022 18:50:09.879 * <search> Acquired RedisJSON_V1 API
1:M 03 Feb 2022 18:50:09.879 * <search> Enabled diskless replication
1:M 03 Feb 2022 18:50:09.879 * **Module 'search' loaded from /usr/lib/redis/modules/redisearch.so**
1:M 03 Feb 2022 18:50:09.879 * Ready to accept connections

**with requirepass**

1:C 03 Feb 2022 18:42:54.251 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 03 Feb 2022 18:42:54.252 # Redis version=6.2.5, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 03 Feb 2022 18:42:54.252 # Configuration loaded
1:M 03 Feb 2022 18:42:54.252 * monotonic clock: POSIX clock_gettime
1:M 03 Feb 2022 18:42:54.253 * Running mode=standalone, port=6379.
1:M 03 Feb 2022 18:42:54.253 # Server initialized
1:M 03 Feb 2022 18:42:54.253 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 03 Feb 2022 18:42:54.253 * Ready to accept connections

**Comment by gkorland** [comment]
@cetin how did you run the docker? Notice when you set docker configuration you override the default ones (which add the module) you need add it too.

**Comment by cetin** [comment]
@gkorland Thanks for the notice. I had run docker without --loadmodules now it works well.
