### ISSUE TITLE
Inconsistent database state

### ISSUE THREAD

**Issue by parthsdoshi** [RedisJSON/RedisJSON#65]
Hi,

I was using rejson for an application I'm working on and ran into an issue where calling json.get returns different child values based on how far up the parent chain I am. I'm not sure how to explain well so here's an album to show you what I'm talking about:

[imgur](https://imgur.com/a/AchU1FV)

The issue is when I do `json.get queues JAYD`, connected_users is populated; however, when I do `json.get queues JAYD.connected_users` it returns an empty array. The correct behavior, I think, should have been that it returns an empty array since I called `json.arrpop` on the array.

Let me know if you need more information!

**Comment by mnunberg** [comment]
Hi, can you give me a set of commands so I can reproduce it? also, can you tell me what version you're using? this was supposed to have been fixed.

**Comment by mnunberg** [comment]
@parthsdoshi ^^

**Comment by parthsdoshi** [comment]
Sorry for not responding! I actually have this flagged in my email and I'll get time to look more into this as soon as finals are done in about a week if that's alright.

Just to give more info., I should have been on the latest version unless pip install was doing something weird.

**Comment by mnunberg** [comment]
pip doesn’t have control over the Redis module, only the client. What version of the Redis module are you using?

**Comment by parthsdoshi** [comment]
Yep, thought you meant version of rejson. It's 4.0.9 right now (building from docker using `redis:latest`) but when I filed this issue I was building from `redislabs/rejson:latest`.

**Comment by gkorland** [comment]
Not relevant anymore.
