### ISSUE TITLE
feature request: multi path update/set for a single key

### ISSUE THREAD

**Issue by marsonya** [RedisJSON/RedisJSON#658]
redis json can have a multi path update/set feature that can allow batching together updates instead of resetting the entire object to do so currently.

**Comment by oshadmi** [comment]
@marsonya Can you please give a concrete example of an enhanced command compared to the current command?
Currently update/set/del [commands](https://oss.redis.com/redisjson/commands/) can be performed using jsonpath wildcard/recursive-descent/union/filter operators, as in the [example](https://github.com/RedisJSON/RedisJSON/issues/658#issuecomment-1041237253) given by @gkorland
