### ISSUE TITLE
fuzzy query on redisjson by redisearch

### ISSUE THREAD

**Issue by gaoshengL** [RedisJSON/RedisJSON#662]
DATA1 redisjson:
1) (integer) 1
2) "myDoc"
3) 1) "$"
   2) "{\"user\":{\"name\":\"John Smith\",\"tag\":\"foo,bar\",\"hp\":1000,\"dmg\":150}}"
DATA2 hash set:
hgetall "movie:11002"
 1) "imdb_id"
 2) "tt0080684"
 3) "release_year"
 4) "1980"
 5) "genre"
 6) "Action"
 7) "title"
 8) "Star Wars: Episode V - The Empire Strikes Back"
 9) "plot"
10) "After the Rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda, while his friends are pursued by Darth Vader and a bounty hunter named Boba Fett all over the galaxy."
11) "votes"
12) "1127635"
13) "rating"
14) "8.7"

I  can fuzzy query data on DATA2
FT.SEARCH idx:movie "%tar%"
1) (integer) 1
2) "movie:11002"
3)  1) "imdb_id"
    2) "tt0080684"
    3) "title"
    4) "Star Wars: Episode V - The Empire Strikes Back"
    5) "plot"
    6) "After the Rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda, while his friends are pursued by Darth Vader and a bounty hunter named Boba Fett all over the galaxy."
    7) "release_year"
    8) "1980"
    9) "genre"
   10) "Action"
   11) "votes"
   12) "1127635"
   13) "rating"
   14) "8.7"

but I can't query data on DATA1
FT.SEARCH userIdx "%hn%"
1) (integer) 0

I want to sure redisjson not supported fuzzy query by  redisearch?

**Comment by K-Jo** [comment]
@gaoshengL it is supported.  to understand what went wrong can you paste the output of
`FT.INFO userIdx`
and
`JSON.GET myDoc`
Also wondering if you're not looking for a feature called "contains" (as in string contains) which is different than a fuzzy search: https://oss.redis.com/redisearch/Query_Syntax/#fuzzy_matching

**Comment by gaoshengL** [comment]
127.0.0.1:6379> FT.INFO userIdx
 1) index_name
 2) "userIdx"
 3) index_definition
 4) 1) key_type
    2) JSON
    3) prefixes
    4) 1) 
    5) default_score
    6) "1"
 5) attributes
 6) 1) 1) identifier
       2) $.user.name
       3) attribute
       4) name
       5) type
       6) TEXT
       7) WEIGHT
       8) "1"
    2) 1) identifier
       2) $.user.tag
       3) attribute
       4) country
       5) type
       6) TAG
       7) SEPARATOR
       8) 
 7) index_options
 8) (empty array)
 9) gc_stats
10) 1) bytes_collected
    2) (integer) 0
11) cursor_stats
12) 1) global_idle
    2) (integer) 0
    3) global_total
    4) (integer) 0
    5) index_capacity
    6) (integer) 384
    7) index_total
    8) (integer) 0
13) num_docs
14) (integer) 1
15) max_doc_id
16) (integer) 1
17) num_terms
18) (integer) 2
19) num_records
20) (integer) 3
21) inverted_sz_mb
22) "4.5334359749018255e+18"
23) total_inverted_index_blocks
24) (integer) 14
25) offset_vectors_sz_mb
26) "4.521614025879978e+18"
27) doc_table_size_mb
28) "4.5457505051329167e+18"
29) sortable_values_size_mb
30) "0"
31) key_table_size_mb
32) "4.538783999459328e+18"
33) records_per_doc_avg
34) "nan"
35) bytes_per_record_avg
36) "nan"
37) offsets_per_term_avg
38) "nan"
39) offset_bits_per_record_avg
40) "nan"
41) indexing
42) (integer) 0
43) percent_indexed
44) "1"
45) hash_indexing_failures
46) (integer) 0


127.0.0.1:6379> JSON.GET myDoc
"{\"user\":{\"name\":\"John Smith\",\"tag\":\"foo,bar\",\"hp\":1000,\"dmg\":150}}"

**Comment by gaoshengL** [comment]
yeah，it worked

127.0.0.1:6379> FT.SEARCH userIdx "hn"
1) (integer) 0
127.0.0.1:6379> FT.SEARCH userIdx "%hn%"
1) (integer) 0
127.0.0.1:6379> FT.SEARCH userIdx "%%hn%%"
1) (integer) 1
2) "myDoc"
3) 1) "$"
   2) "{\"user\":{\"name\":\"John Smith\",\"tag\":\"foo,bar\",\"hp\":1000,\"dmg\":150}}"
127.0.0.1:6379> 
127.0.0.1:6379> FT.SEARCH userIdx "%%%hn%%%"
1) (integer) 1
2) "myDoc"
3) 1) "$"
   2) "{\"user\":{\"name\":\"John Smith\",\"tag\":\"foo,bar\",\"hp\":1000,\"dmg\":150}}"
127.0.0.1:6379>
