### ISSUE TITLE
Precompiled not available at RedisLabs Download Center

### ISSUE THREAD

**Issue by joshuakoh1** [RedisJSON/RedisJSON#675]
Only RedisSearch is available. Is there any way to get a precompiled version at all?

**Comment by gkorland** [comment]
Try to scroll down the drop down list, JSON is there.
![image](https://user-images.githubusercontent.com/753206/155872915-49497fff-db7c-480a-b400-e136424f3613.png)

**Comment by joshuakoh1** [comment]
Ah. For some reason the dropdown wasn't working when I first registered. Anyway, I tried to load the 18.04 version on my 20.04 LTS and it refuses to run. Is it a version problem?

```
30052:M 27 Feb 2022 18:54:24.402 * <ReJSON> version: 20006 git sha: db3329c branch: HEAD
30052:M 27 Feb 2022 18:54:24.402 * <ReJSON> Exported RedisJSON_V1 API
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/redis-module-0.25.0/src/context/mod.rs:286:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Aborted
```

**Comment by gkorland** [comment]
You're probably using an old Redis version.
Which version of Redis are you using? You need Redis 6+
