### ISSUE TITLE
JSON.CLEAR does not work and behaves differently than API

### ISSUE THREAD

**Issue by RekaDowney** [RedisJSON/RedisJSON#676]
name: JSON.CLEAR does not work and behaves differently than API
description: File a bug report
title: "[Bug]: "JSON.CLEAR does not work and behaves differently than API
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        As shown in the figure below, `JSON.CLEAR` does not clear the age to 0.
![image](https://user-images.githubusercontent.com/24631388/155832857-0587fb26-9e75-4b28-a39c-2745afcabf40.png)
![image](https://user-images.githubusercontent.com/24631388/155833210-2e5b6010-4aea-48f9-a315-fbfcfe6fad0d.png)

  - type: input
    id: operating_system
    attributes:
      label: OS
      description: Operating system and version (eg Ubuntu 20.04, OSX Catalina)
      placeholder: **centos7**

  - type: architecutre
    id: cpu_arch
    attributes:
      label: CPU Architecture
      description: CPU Architecture (eg: x86, x86-64, arm, etc).
      placeholder: **x86_64**

  - type: input
    id: redis_version
    attributes:
      label: Redis Server Version
      description: What version of redis-server are you running (redis-server --version)
      placeholder: Redis server v=**6.0.9**

  - type: input
    id: redis_module_version
    attributes:
      label: Redis Module Version
      description: What version of this redis module was installed?
      placeholder: **2.0.6**,

  - type: input
    id: was_redis_docker
    attributes:
      label: Docker Installation
      description: What version of this redis module was installed?
      placeholder: **false**

  - type: checkboxes
    id: installmethod
    attributes:
      label: Docker installation
      description: Check this box, if you installed the release via a docker.
      options:
        - label: **not**, we install it by linux server.

  - type: textarea
    id: whathappened
    label: What happened?
    description: Please tell us what happened, and what you expected to happen.
    placeholder:         As shown in the figure below, `JSON.CLEAR` does not clear the age to 0.
![image](https://user-images.githubusercontent.com/24631388/155832857-0587fb26-9e75-4b28-a39c-2745afcabf40.png)
![image](https://user-images.githubusercontent.com/24631388/155833210-2e5b6010-4aea-48f9-a315-fbfcfe6fad0d.png)

  - type: textarea
    id: logs
    label: Relevant log output
    description: If release, please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
    render: shell

**Comment by RekaDowney** [comment]
**JSON.NUMINCRBY** also behaves differently than API.
![image](https://user-images.githubusercontent.com/24631388/155833358-a9635622-8848-4017-9b3f-ec8d3429bfc2.png)

**Comment by oshadmi** [comment]
@RekaDowney The documented behavior of `JSON.CLEAR` is not yet available with 2.0.6.
Clearing scalars is currently available with docker image `redislabs/rejson:edge`, e.g., 
`docker run -d -p 6379:6379 redislabs/rejson:edge`
(and will be available in the coming 2.0.7)

Documentation was fixed by #679 (only non-existing paths are ignored)
