### ISSUE TITLE
build failed when running `cargo build --release`

### ISSUE THREAD

**Issue by porottasambar** [RedisJSON/RedisJSON#680]
When i tried to build `RedisJSON` using `cargo build --release`, giving me following error;
```
$ cargo build --release
error: failed to parse manifest at `/build/Cargo.toml`

Caused by:
  unknown cargo feature `edition2021`
```

```
$ git branch
* master
```

labels: [help wanted]

**Comment by gkorland** [comment]
which version of Rust are you using?

**Comment by porottasambar** [comment]
Issue was with Rust version. build is working as expected with `rustc 1.59.0`
thanks
