### ISSUE TITLE
querying does not work for integer values

### ISSUE THREAD

**Issue by dmitsh** [RedisJSON/RedisJSON#694]
name: Bug Report
description: File a bug report
title: "[Bug]: querying does not work for integer values"
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: operating_system
    attributes:
      label: OS
      description: Operating system and version (eg Ubuntu 20.04, OSX Catalina)
      placeholder: linux

  - type: architecutre
    id: cpu_arch
    attributes:
      label: CPU Architecture
      description: CPU Architecture (eg: x86, x86-64, arm, etc).
      placeholder: linux

  - type: input
    id: redis_version
    attributes:
      label: Redis Server Version
      description: What version of redis-server are you running (redis-server --version)
      placeholder: latest

  - type: input
    id: redis_module_version
    attributes:
      label: Redis Module Version
      description: What version of this redis module was installed?
      placeholder: latest

  - type: input
    id: was_redis_docker
    attributes:
      label: Docker Installation
      description: What version of this redis module was installed?
      placeholder: latest

  - type: checkboxes
    id: installmethod
    attributes:
      label: Docker installation
      description: Check this box, if you installed the release via a docker.
      options:
        - label: I installed the dockerhub release

  - type: textarea
    id: whathappened
    label: What happened?
    description: Please tell us what happened, and what you expected to happen.
    placeholder: |
      I'm querying the following data:
      ```json
      {
          "person": {
              "org": "Dev Ops",
              "id": 1036
          },
          "city": "Seattle",
          "state": "WA"
      }
      ```
      Here is my schema: `FT.CREATE userIndx ON JSON SCHEMA $.person.org AS var0 TEXT SORTABLE $.person.id AS var1 NUMERIC SORTABLE $.city AS var2 TEXT SORTABLE $.state AS var3 TEXT SORTABLE`

      Here is my query: `FT.SEARCH userIndx @var1:(1036)`
      I'm getting zero results back.

      However, when I'm querying `FT.SEARCH userIndx @var3:(WA)`, I'm getting back
      ```
      1) (integer) 1
      2) "key1"
      3) 1) "$"
         2) {\"person\":{\"org\":\"Dev Ops\",\"id\":1036},\"city\":\"Seattle\",\"state\":\"WA\"}
      ```

  - type: textarea
    id: logs
    label: Relevant log output
    description: If release, please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
    render: shell

**Comment by gkorland** [comment]
Please notice this is not the syntax for querying numeric fields. 
See: https://oss.redis.com/redisearch/Query_Syntax/#numeric_filters_in_query

e.g.
```
FT.SEARCH userIndx @var1:[1036 (2001]
FT.SEARCH userIndx @var1:[1036 1036]
```

**Comment by dmitsh** [comment]
Thank you @gkorland !

I changed the query and got desired results.

A follow up question.
Is there an easy way to compare a numeric value to a set of numbers (not a range)?
Something like that:  `FT.SEARCH userIndx @var1:(1036 | 1054 | 932)`

Currently, to achieve this, my query looks like:
`FT.SEARCH userIndx (@var1:[1036 1036]) | (@var1:[1054 1054]) | (@var1:[932 932])`

**Comment by gkorland** [comment]
If all you need is exact match you can set the field as Tag and get this simple behaviour see: https://oss.redis.com/redisearch/Tags/#querying_tag_fields
