### ISSUE TITLE
How to get a range of elements from an array?

### ISSUE THREAD

**Issue by hypo-thesis** [RedisJSON/RedisJSON#703]
I have a simple array as such :

`[1,2,3,4,5]`
and I wish to get a range for example from index 2 to index 4. I can get the last element of the array by :

`json.get key .[-1]`
However I cannot find anyway to return a specific results without trimming the array.

Is there anyway I can get a range of elements from a Redis json array?

**Comment by gkorland** [comment]
The syntax is: `[start:end]` 

e.g.
```
not connected> json.set a $ '{"a":[1,2,3,4,5,6]}'
OK
127.0.0.1:6379> json.get a '$.a'
"[[1,2,3,4,5,6]]"
127.0.0.1:6379> json.get a '$.a[3:4]'
"[4]"
127.0.0.1:6379> json.get a '$.a[3:5]'
"[4,5]"
```

**Comment by hypo-thesis** [comment]
> 

It works, thanks. How can I do it with nodejs ? 

await Client.json.get("key" , '$.a[3:5]')

this fails me

**Comment by 1714080902120** [comment]
I got the same confusion in rust. I had tried using `.json_get::<&'static str, &str, CacheArticlesSlice>(CACHE_KEY, ".list[3:7]").await;`, but it only return the third element.
Now i know how to fix it: `.json_get::<&'static str, &str, CacheArticlesSlice>(CACHE_KEY, "$.list[3:7]").await;`, and it works well.
