### ISSUE TITLE
Save JSON's array into JSON 

### ISSUE THREAD

**Issue by pgamerx** [RedisJSON/RedisJSON#704]
Hi there, I am not really experienced with Redis or schemas and stuff and this is what I wanted to use: 

I am using NodeJS and using the redis-om-node package
Schema:
```JSON
{
ID: string,
warns: [
{ reason: "Something", id: "1" },
{ reason: "something else", id: "2" }
]
}
```

How can I do this? I am really confused. Thanks!

**Comment by gkorland** [comment]
It's probably better to move this issue to https://github.com/redis/redis-om-node

**Comment by gkorland** [comment]
Duplicate https://github.com/redis/redis-om-node/issues/72
