### ISSUE TITLE
doc's rejson-py link points to redis-py

### ISSUE THREAD

**Issue by slickpockets** [RedisJSON/RedisJSON#71]
Hey, just a heads up, noticed that the docs @ https://oss.redislabs.com/rejson/#client-libraries
the git link points to https://github.com/RedisLabs/redis-py/ instead of https://github.com/RedisLabs/rejson-py
the pypi link resolves fine.

hope this helps mabahs 

peace

**Comment by itamarhaber** [comment]
Hello @slickpockets,

Thanks for the heads up - would you like to make a PR that fixes that?
