### ISSUE TITLE
Getting Error while loading this module on Runtime using command -- redis-server --loadmodule /path/to/module/rejson.so

### ISSUE THREAD

**Issue by amanagrawal277** [RedisJSON/RedisJSON#72]
Hi,
I am trying to load this module on runtime using command 
redis-server --loadmodule /home/aman/rejson/src/rejson.so
but getting error-
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 2
>>> 'loadmodule "/home/aman/rejson/src/rejson.so"'
Bad directive or wrong number of arguments

Am I missing any argument as mentioned in error

**Comment by itamarhaber** [comment]
Hello @amanagrawal277 

The config line looks ok - are you positive that your Redis server's version is 4 or above?
