### ISSUE TITLE
JSON.NUMMULTBY documentation

### ISSUE THREAD

**Issue by sazzad16** [RedisJSON/RedisJSON#730]
It states:

> As of Redis version 2.0, this command is regarded as deprecated.

It should be RedisJSON instead of Redis.

**Comment by oshadmi** [comment]
@itamarhaber It seems it is generated and needs another param for the component name, which could be Redis, or a module.
(or at least remove the name and remain only with `As of version ...`)
Same with `Starting with Redis version`.


Is [this](https://github.com/redis/redis-website/blob/c9e310c8c26937d53e9522fc5b6f5bc17eb6cabc/layouts/commands/single.html#L37) the template?

**Comment by oshadmi** [comment]
Fixed to:

> As of JSON version 2.0, this command is regarded as deprecated.
