### ISSUE TITLE
How to get the first element after a filter?

### ISSUE THREAD

**Issue by supery-chen** [RedisJSON/RedisJSON#738]
Example Json:

```json
{
    "store": {
        "book": [
            {
                "price": 8.95
            },
            {
                "price": 12.99
            },
            {
                "price": 8.99
            },
            {
                "price": 22.99
            }
        ]
    }
}
```

I wish to get the first element whose price is less than 20

![image](https://user-images.githubusercontent.com/54849153/171570330-6e379092-67dd-49ea-aecd-2dca8579ab24.png)

**Comment by oshadmi** [comment]
The path following the filter operator is applied on each of the filtered values, and not on the entire set of filtered values.
For example, 
```
127.0.0.1:6379> json.set t $ '{"store":{"book":[{"price":8.95,"a":[1,2,3]},{"price":12.99,"a":[4,5,6]},{"price":8.99,"a":[7,8,9]},{"price":22.99,"a":[10,11,12]}]}}'
OK
127.0.0.1:6379> json.get t $.store.book[?(@.price<20)].a[1]
"[2,5,8]"
```

To get the first element whose price is less than 20 you need to process the result from
`json.get t $.store.book[?(@.price<20)] `
with a [client](https://redis.io/docs/clients/)
