### ISSUE TITLE
jsonpath not work

### ISSUE THREAD

**Issue by supery-chen** [RedisJSON/RedisJSON#739]
![image](https://user-images.githubusercontent.com/54849153/171606531-51b87ef9-7d16-4616-9cea-27fff0cd16df.png)

![image](https://user-images.githubusercontent.com/54849153/171606659-4ef9bae6-ac4b-47a9-8855-ecc5906e8e9b.png)

what's wrong

**Comment by oshadmi** [comment]
Try this
```
127.0.0.1:6379> json.get book '$.store.book[?(@.author=="Evelyn Waugh")]'
```

**Comment by supery-chen** [comment]
> Try this
> 
> ```
> 127.0.0.1:6379> json.get book '$.store.book[?(@.author=="Evelyn Waugh")]'
> ```

![image](https://user-images.githubusercontent.com/54849153/171788566-eff90d50-e4fd-4bf6-a0d1-44709146aab6.png)

It works, thank u
