### ISSUE TITLE
JSON.ARRAPPEND + JSON.ARRINDEX requires single quoted, double quoted strings

### ISSUE THREAD

**Issue by chayim** [RedisJSON/RedisJSON#745]
Create a json string with the following empty array.

```
json.set foo $ '{"hello": "world", "colours": []}'
```

Items can now only by added to the array using JSON.ARRAPPEND, when their values are single quoted strings that are wrapped in double quotes.

This does not work:
```
json.arrappend foo $.colours 'apple'
```

This doesn't either:
```
json.arrappend foo $.colours "apple"
```

Only the following works:

```
json.arrappend foo $.colours '"apple"'
```

**Comment by chayim** [comment]
The same is true for json.arrindex

**Comment by oshadmi** [comment]
JSON values in any command need to adhere to the JSON schema
See https://github.com/RedisJSON/RedisJSON/issues/744#issuecomment-1148627022

built-in `null`
`json.set foo $.colours "null"`
(Or `json.set foo $.colours null`)
Is not string `"null"`
`json.set foo $.colours '"null"'`

**Comment by chayim** [comment]
Closed as a quoting issue.
