### ISSUE TITLE
fix warning message "ranlib: file has no symbols"

### ISSUE THREAD

**Issue by meetme2meat** [RedisJSON/RedisJSON#75]
I'm facing the install issue on running make command.

I see the following errors .

> /Library/Developer/CommandLineTools/usr/bin/ranlib: file: librejson.a(print_version.o) has no symbols

Any idea what is causing the following errors.

SYSTEM INFO: Running it on MACOS-X

> Apple LLVM version 9.1.0 (clang-902.0.39.2)
> Target: x86_64-apple-darwin17.6.0
> Thread model: posix
> InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by itamarhaber** [comment]
Hello @meetme2meat 

I can reproduce this - will be fixed.

**Comment by itamarhaber** [comment]
FYI - this is just a warning, not an error, so the module is ready for use nonetheless.

**Comment by meetme2meat** [comment]
@itamarhaber I confirm things are working here.

**Comment by itamarhaber** [comment]
Cool - reopening just to remind us to fix the warning.

**Comment by nviennot** [comment]
Any resolution on this?

**Comment by meetme2meat** [comment]
@nviennot its a warning, not an error.
