### ISSUE TITLE
[doc] Add Redisson to list of clients

### ISSUE THREAD

**Issue by adrian-skybaker** [RedisJSON/RedisJSON#762]
As of [3.17.4](https://github.com/redisson/redisson/releases/tag/redisson-3.17.4) Redisson now supports RedisJSON.

Here's a [patched version of Clients.md](https://github.com/RedisJSON/RedisJSON/files/8989114/Clients.md).

**Comment by gkorland** [comment]
@adrian-skybaker thanks for the issue, can you please submit a pull request?
