### ISSUE TITLE
non-'\0'-terminated array of char passed to strtoll

### ISSUE THREAD

**Issue by pascal-cuoq** [RedisJSON/RedisJSON#77]
The C standard [defines a string](https://port70.net/~nsz/c/c11/n1570.html#7.1.1p1) as “a contiguous sequence of characters terminated by and including the first null character”, and [it specifies](https://port70.net/~nsz/c/c11/n1570.html#7.22.1.4p2) `strtoll` as taking a pointer to a string. In other words, it would be legal for a `strtoll` implementation to call `strlen` on its argument.

In rejson, an array of characters without a terminating `'\0'` is built inside the [function `CreateNodeFromJSON`](https://github.com/RedisLabsModules/rejson/blob/1b7466d385df5e341a0fbf0b2792b909136e7c50/src/json_object.c#L188-L190) :

```
        _buf = RedisModule_Calloc(_len, sizeof(char));
        _buf[0] = '[';
        _buf[_len - 1] = ']';
        memcpy(&_buf[1], &buf[_off], len - _off);
```

A pointer inside this array of characters is subsequently [passed to `strtoll` inside the function `popCallback`](https://github.com/RedisLabsModules/rejson/blob/1b7466d385df5e341a0fbf0b2792b909136e7c50/src/json_object.c#L132):

```
                value = strtoll(pos, &eptr, 10);
```

This does not cause a problem with any `strtoll` implementation that I know of, but since the standard says that the argument of `strtoll` should be a pointer to a string, what would you think of the following change, leaving room for a final `'\0'` when the number is copied inside `CreateNodeFromJSON`?

```
diff --git a/src/json_object.c b/src/json_object.c
index 6d4b498..b753f83 100644
--- a/src/json_object.c
+++ b/src/json_object.c
@@ -185,7 +185,7 @@ int CreateNodeFromJSON(JSONObjectCtx *ctx, const char *buf, size_t len, Node **n
      */
     if ((is_scalar = ('{' != _buf[_off]) && ('[' != _buf[_off]) && _off < _len)) {
         _len = _len - _off + 2;
-        _buf = RedisModule_Calloc(_len, sizeof(char));
+        _buf = RedisModule_Calloc(_len+1, sizeof(char));
         _buf[0] = '[';
         _buf[_len - 1] = ']';
         memcpy(&_buf[1], &buf[_off], len - _off);
```

The issue described here is very minor and has no immediate consequences, but there are precedents in which newly introduced compiler optimizations have destructive effects on existing code because the compiler starts enforcing a stricter view of a standard function's contract. There was [an advisory for BIND 9 in 2014](https://kb.isc.org/article/AA-01167) because compilers started to take a stricter view of `memcpy`'s contract. Adam Langley [explained what happened very well](https://www.imperialviolet.org/2016/06/26/nonnull.html). Unfortunately, despite the call for reason in the penultimate paragraph of his post, there has been no back-tracking on that optimization. So assuming that compiler authors continue to be creative, the change submitted for discussion in this issue, if acceptable, aims at making rejson safe for the next twenty years.

**Comment by pascal-cuoq** [comment]
Hello,

we found this obscure issue with TIS Analyzer, together with other ones that we will report separately. @filcab has reminded me that this issue can also be found using ASan, which is very easy to use when your code already compiles with Clang. You only need to build an instrumented version by adding `-fsanitize=address` to Clang's commandline, and run with `ASAN_OPTIONS=strict_string_checks=true` in order to detect errors in this family.

```
~ $ cat t.c
#include <string.h>
#include <stdlib.h>

char *p;
long long n;

void allocate(void) {
  p = malloc(5);
  p[0] = '[';
  p[4] = ']';
  memcpy(p+1, "123", 3);
}

void parse(void) {
  n = strtoll(p + 1, NULL, 10);
}

int main(void) {
  allocate();
  parse();
}
~ $ clang -fsanitize=address t.c
~ $ ASAN_OPTIONS=strict_string_checks=true ./a.out 
=================================================================
==31447==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200000eed5 at pc 0x00010a0bc702 bp 0x7fff55b777b0 sp 0x7fff55b76f70
...
```

**Comment by itamarhaber** [comment]
Hello @pascal-cuoq 

Thanks for both reports - I'd like to take care of this immediately, but this will have to wait for some spare cycles.

Much appreciated!
