### ISSUE TITLE
JSON.STRAPPEND documentation typo

### ISSUE THREAD

**Issue by jamesastound** [RedisJSON/RedisJSON#810]
name: Documentation Error Report
description: File a bug report
title: "[Docs]: "
labels: [documentation]
body:

[JSON.STRAPPEND ](https://redis.io/commands/json.strappend/)

#Return
[Array reply](https://redis.io/docs/reference/protocol-spec#resp-arrays) of [Integer reply](https://redis.io/docs/reference/protocol-spec#resp-integers) - for each path, the string's new length, or [Null reply](https://redis.io/docs/reference/protocol-spec#resp-bulk-strings) if the matching JSON value is not **an array**.

 **an array** should be changed to **a string**

**Comment by oshadmi** [comment]
@jamesastound In the documentation link you have provided for [JSON.STRAPPEND](https://redis.io/commands/json.strappend/) there's an example:
```
redis> JSON.SET doc $ '{"a":"foo", "nested": {"a": "hello"}, "nested2": {"a": 31}}'
OK
redis> JSON.STRAPPEND doc $..a '"baz"'
1) (integer) 6
2) (integer) 8
3) (nil)
```

And it looks OK - returning an array of integer/null is returned (not a string)
If you have different behavior, please share the scenario and the exact version and platform.
