### ISSUE TITLE
Redis crashes when loading rejson on Windows

### ISSUE THREAD

**Issue by 1nter-p** [RedisJSON/RedisJSON#817]
I'm using [this port of Redis to Windows](https://github.com/tporadowski/redis), and built the module by `cargo build --release`.
64-bit, Windows 11

Redis version: 5.0.14.1
[14740] 04 Sep 15:31:46.371 # --- EXCEPTION_ACCESS_VIOLATION
[14740] 04 Sep 15:31:46.371 # --- STACK TRACE
redis-server.exe!StackTraceInfo((null):0)(0x14018C230, 0x010CFF60, 0x1400DDA20, 0x010CE740)
redis-server.exe!UnhandledExceptiontHandler((null):0)(0x010CE740, 0x1400DDA01, 0x00000000, 0x7FF94E5C0000)
KERNELBASE.dll!UnhandledExceptionFilter((null):0)(0x7FF9975401EC, 0x7FF997510820, 0x00000000, 0x00000000)
ntdll.dll!memset((null):0)(0x010CFF60, 0x7FF9975401EC, 0x010CE810, 0x00000000)
ntdll.dll!_C_specific_handler((null):0)(0x00000000, 0x010CED10, 0x010CF3F0, 0x010CF3F0)
ntdll.dll!_chkstk((null):0)(0x010CF3F0, 0x7FF9973C0000, 0x7FF9973C485B, 0x7FF9975401EC)
ntdll.dll!RtlRestoreContext((null):0)(0x7369646500, 0x00000000, 0x010CF688, 0x0000000F)
ntdll.dll!KiUserExceptionDispatcher((null):0)(0x7FF96F7D00F9, 0xFFFFFFFF, 0x0053EFF0, 0x00000009)
ntdll.dll!KiUserExceptionDispatcher((null):0)(0xFFFFFFFF, 0x0053EFF0, 0x00000009, 0x00532380)
ntdll.dll!KiUserExceptionDispatcher((null):0)(0x0053EFF0, 0x00000009, 0x00532380, 0x010CF850)
ntdll.dll!KiUserExceptionDispatcher((null):0)(0x00000009, 0x00532380, 0x010CF850, 0x7FF96F7243A5)
ntdll.dll!KiUserExceptionDispatcher((null):0)(0x00532380, 0x010CF850, 0x7FF96F7243A5, 0x00000001)
ntdll.dll!KiUserExceptionDispatcher((null):0)(0x010CF850, 0x7FF96F7243A5, 0x00000001, 0x010CF6D0)
ntdll.dll!KiUserExceptionDispatcher((null):0)(0x7FF96F7243A5, 0x00000001, 0x010CF6D0, 0x7FCE94C011E0)
ntdll.dll!KiUserExceptionDispatcher((null):0)(0x00000001, 0x010CF6D0, 0x7FCE94C011E0, 0x140055C57)
ntdll.dll!KiUserExceptionDispatcher((null):0)(0x010CF6D0, 0x7FCE94C011E0, 0x140055C57, 0x00000000)
ntdll.dll!KiUserExceptionDispatcher((null):0)(0x7FCE94C011E0, 0x140055C57, 0x00000000, 0x7FF99753A860)
ntdll.dll!KiUserExceptionDispatcher((null):0)(0x140055C57, 0x00000000, 0x7FF99753A860, 0x00000001)
ntdll.dll!KiUserExceptionDispatcher((null):0)(0x00000000, 0x7FF99753A860, 0x00000001, 0x4E4F534A6552)
redis-server.exe!scriptingEnableGlobalsProtection(D:\dev\GitHub\redis\src\scripting.c:933)(0x7FF96F6D0000, 0x7FCEA2400000, 0x7FCE99803C00, 0x7FCE94C011E0)
redis-server.exe!moduleLoad(D:\dev\GitHub\redis\src\module.c:5350)(0x7FCE99803C00, 0x00000000, 0x00558F90, 0x00558F90)
redis-server.exe!moduleLoadFromQueue(D:\dev\GitHub\redis\src\module.c:5291)(0x00003994, 0x1401865D0, 0x7FCE95000008, 0x00000027)
redis-server.exe!redis_main(D:\dev\GitHub\redis\src\server.c:4538)(0x00593EF0, 0x00593EF0, 0x00558F90, 0x00000002)
redis-server.exe!main(D:\dev\GitHub\redis\src\server.c:4538)(0x005887B0, 0x005887B0, 0x005887B0, 0x00593EF0)
redis-server.exe!ServiceWorkerThread(D:\dev\GitHub\redis\src\server.c:4538)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
KERNEL32.DLL!BaseThreadInitThunk(D:\dev\GitHub\redis\src\server.c:4538)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart(D:\dev\GitHub\redis\src\server.c:4538)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart(D:\dev\GitHub\redis\src\server.c:4538)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
[14740] 04 Sep 15:31:46.371 # --- INFO OUTPUT
# Server
redis_version:5.0.14.1
redis_git_sha1:ec77f72d
redis_git_dirty:0
redis_build_id:5627b8177c9289c
redis_mode:standalone
os:Windows  
arch_bits:64
multiplexing_api:WinSock_IOCP
atomicvar_api:pthread-mutex
process_id:14740
run_id:1b8d5530caea7acc6763dfd334cbe8537b1453c9
tcp_port:6379
uptime_in_seconds:0
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:1332322
executable:C:\Program Files\Redis\"c:\program files\redis\redis-server.exe"
config_file:C:\Program Files\Redis\redis.windows-service.conf

# Clients
connected_clients:0
client_recent_max_input_buffer:0
client_recent_max_output_buffer:0
blocked_clients:0

# Memory
used_memory:661616
used_memory_human:646.11K
used_memory_rss:0
used_memory_rss_human:0B
used_memory_peak:661616
used_memory_peak_human:646.11K
used_memory_peak_perc:inf%
used_memory_overhead:0
used_memory_startup:0
used_memory_dataset:661616
used_memory_dataset_perc:100.00%
allocator_allocated:0
allocator_active:0
allocator_resident:0
total_system_memory:0
total_system_memory_human:0B
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:-nan(ind)
allocator_frag_bytes:0
allocator_rss_ratio:-nan(ind)
allocator_rss_bytes:0
rss_overhead_ratio:-nan(ind)
rss_overhead_bytes:0
mem_fragmentation_ratio:-nan(ind)
mem_fragmentation_bytes:0
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:0
mem_aof_buffer:0
mem_allocator:jemalloc-5.2.1-redis
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1662276706
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0

# Stats
total_connections_received:0
total_commands_processed:0
instantaneous_ops_per_sec:0
total_net_input_bytes:0
total_net_output_bytes:0
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
evicted_keys:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:0
master_replid:0122d61c5ea20d5d4792df4e574d8405feaca3e0
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.062500
used_cpu_user:0.031250
used_cpu_sys_children:0.000000
used_cpu_user_children:0.000000

# Commandstats

# Cluster
cluster_enabled:0

# Keyspace
[14740] 04 Sep 15:31:46.386 #

**Comment by gkorland** [comment]
RedisJSON can't run on Redis 5.0. It requires Redis 6.0+

**Comment by 1nter-p** [comment]
Thanks, found another port that had Redis 6 and it worked perfectly.
