### ISSUE TITLE
How should I inquire?

### ISSUE THREAD

**Issue by chao7860-java** [RedisJSON/RedisJSON#828]
```
FT.CREATE idx:chao ON JSON PREFIX 1 "chao:" 
SCHEMA 
$.id AS id TEXT NOSTEM SORTABLE 
$.name AS name TEXT NOSTEM SORTABLE 
$.age AS age TEXT NOSTEM SORTABLE 
$.hobby.hobby_id AS hi TEXT NOSTEM SORTABLE 
$.hobby.hobby_name AS hn TEXT NOSTEM SORTABLE
```

```
JSON.SET chao:1 $ '{
  "id": "1",
  "name": "chao",
  "age": "99",
  "hobby": [
    {
      "hobby_id": "11",
      "hobby_name": "eat"
    },
    {
      "hobby_id": "12",
      "hobby_name": "sleep"
    }
  ]
}'

JSON.SET chao:2 $  '{
  "id": "2",
  "name": "wang",
  "age": "88",
  "hobby": [
    {
      "hobby_id": "11",
      "hobby_name": "eat"
    },
    {
      "hobby_id": "13",
      "hobby_name": "code"
    }
  ]
}'
```

**Query command**
`FT.SEARCH idx:chao '@hi:1'`

**results*
_No results found._

How should I inquire?

Thank you in advance.

**Comment by oshadmi** [comment]
Currently only `TAG` can be used to index multiple values in an array
(`TEXT` and `NUMERIC` can be used but currently only in the master branch. Planned for RediSearch 6.2.1)

For prefix shorter than 2, you should set
`FT.CONFIG set MINPREFIX 1`
(but it has performance cost)

For multi value, you should use a path such as `$.hobby[*].hobby_id`
```
FT.CREATE idx:chao2 ON JSON PREFIX 1 "chao:" SCHEMA $.id AS id TEXT NOSTEM SORTABLE $.name AS name TEXT NOSTEM SORTABLE $.age AS age TEXT NOSTEM SORTABLE $.hobby[*].hobby_id AS hi TAG $.hobby[*].hobby_name AS hn TAG

JSON.SET chao:2 $ '{"id": "2", "name": "wang", "age": "88","hobby": [{"hobby_id": "1122","hobby_name": "eat"},{"hobby_id": "13","hobby_name": "code"}]}'

FT.SEARCH idx:chao2 '@hi:{1*}'
```

In master branch
```
FT.CREATE idx:chao2 ON JSON PREFIX 1 "chao:" SCHEMA $.id AS id TEXT NOSTEM SORTABLE $.name AS name TEXT NOSTEM SORTABLE $.age AS age TEXT NOSTEM SORTABLE $.hobby[*].hobby_id AS id TEXT NOSTEM SORTABLE $.hobby.hobby_name AS hn TEXT NOSTEM SORTABLE

JSON.SET chao:2 $ '{"id": "2", "name": "wang", "age": "88","hobby": [{"hobby_id": "1122","hobby_name": "eat"},{"hobby_id": "13","hobby_name": "code"}]}'

FT.SEARCH idx:chao2 '@hi:(1*)' 
```

**Comment by chao7860-java** [comment]
> 目前只能`TAG`用于索引数组中的多个值 （`TEXT`并且`NUMERIC`可以使用，但目前只能在 master 分支中使用。计划用于 RediSearch 6.2.1）
> 
> 对于小于 2 的前缀，您应该设置 `FT.CONFIG set MINPREFIX 1` （但它有性能成本）
> 
> 对于多值，您应该使用路径，例如`$.hobby[*].hobby_id`
> 
> ```
> FT.CREATE idx:chao2 ON JSON PREFIX 1 "chao:" SCHEMA $.id AS id TEXT NOSTEM SORTABLE $.name AS name TEXT NOSTEM SORTABLE $.age AS age TEXT NOSTEM SORTABLE $.hobby[*].hobby_id AS hi TAG $.hobby[*].hobby_name AS hn TAG
> 
> JSON.SET chao:2 $ '{"id": "2", "name": "wang", "age": "88","hobby": [{"hobby_id": "1122","hobby_name": "eat"},{"hobby_id": "13","hobby_name": "code"}]}'
> 
> FT.SEARCH idx:chao2 '@hi:{1*}'
> ```
> 
> 在主分支
> 
> ```
> FT.CREATE idx:chao2 ON JSON PREFIX 1 "chao:" SCHEMA $.id AS id TEXT NOSTEM SORTABLE $.name AS name TEXT NOSTEM SORTABLE $.age AS age TEXT NOSTEM SORTABLE $.hobby[*].hobby_id AS hi TEXT NOSTEM SORTABLE $.hobby.hobby_name AS hn TEXT NOSTEM SORTABLE
> 
> JSON.SET chao:2 $ '{"id": "2", "name": "wang", "age": "88","hobby": [{"hobby_id": "1122","hobby_name": "eat"},{"hobby_id": "13","hobby_name": "code"}]}'
> 
> FT.SEARCH idx:chao2 '@hi:(1*)' 
> ```

Thank you very much. It solved my search problem.

But how can I aggregate and search for this nested format?

For example, I want to group 'hn'' and count the number of different hn'.

Here's what I tried.

`FT.AGGREGATE  idx:chao * APPLY @hn AS hn GROUPBY 1  @hn REDUCE COUNT 0 AS count`

**return**
`Matched: 1`

I can group fields of type TEXT, such as' name', but not fields of type TAG.

How should fields of this TAG type be aggregated?

Thank you again in advance.

**Comment by chao7860-java** [comment]
[https://github.com/RediSearch/RediSearch/issues/3115](url) 
I got it solved in this problem
