### ISSUE TITLE
failed to run custom build command for `redis-module v1.0.1`

### ISSUE THREAD

**Issue by hypo-thesis** [RedisJSON/RedisJSON#839]
I get : 

error: failed to run custom build command for `redis-module v1.0.1`

Caused by:
  process didn't exit successfully: `/root/RedisJSON/target/release/build/redis-module-cc34f452beec1068/build-script-build` (exit status: 101)
  --- stdout
  TARGET = Some("x86_64-unknown-linux-gnu")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "src/include/" "-Wall" "-Wextra" "-DREDISMODULE_EXPERIMENTAL_API" "-o" "/root/RedisJSON/target/release/build/redis-module-79cba67807478753/out/src/redismodule.o" "-c" "src/redismodule.c"
  exit status: 0
  AR_x86_64-unknown-linux-gnu = None
  AR_x86_64_unknown_linux_gnu = None
  HOST_AR = None
  AR = None
  running: "ar" "cq" "/root/RedisJSON/target/release/build/redis-module-79cba67807478753/out/libredismodule.a" "/root/RedisJSON/target/release/build/redis-module-79cba67807478753/out/src/redismodule.o"
  exit status: 0
  running: "ar" "s" "/root/RedisJSON/target/release/build/redis-module-79cba67807478753/out/libredismodule.a"
  exit status: 0
  cargo:rustc-link-lib=static=redismodule
  cargo:rustc-link-search=native=/root/RedisJSON/target/release/build/redis-module-79cba67807478753/out

  --- stderr
  /usr/include/x86_64-linux-gnu/sys/types.h:145:10: fatal error: 'stddef.h' file not found
  /usr/include/x86_64-linux-gnu/sys/types.h:145:10: fatal error: 'stddef.h' file not found, err: true
  thread 'main' panicked at 'error generating bindings: ()', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/redis-module-1.0.1/build.rs:76:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

While following the installation instruction. Please help me.

**Comment by hypo-thesis** [comment]
I had to update to  Ubuntu 20 LTS for it to work.

**Comment by gkorland** [comment]
Which Ubuntu version did you use before the upgrade?

**Comment by Zalak258** [comment]
jij
