### ISSUE TITLE
Dangerous expose of port

### ISSUE THREAD

**Issue by dallascao** [RedisJSON/RedisJSON#856]
Anyone who uses this please be aware that this will expose port 6379 to outside.

`docker run -p 6379:6379 --name redis-stack redis/redis-stack:latest`

Use this instead

`docker run -p 127.0.0.1:6379:6379 --name redis-stack redis/redis-stack:latest`

**Comment by rafie** [comment]
Hello @dallascao,
This issue belongs here: https://github.com/redis-stack/redis-stack
Thanks!
