### ISSUE TITLE
Why do JSON commands force large numbers into scientific notation?

### ISSUE THREAD

**Issue by naps62** [RedisJSON/RedisJSON#869]
I'm dealing with an issue storing JSON objects that include large numbers (`u128` in Rust). When calling `JSON.SET` with such a number, it gets converted into a string (which is fine), but in scientific notation.
This not only loses information, but also makes the deserialization fail when reading the value back to Rust. Both issues are a deal breaker to my app

Output below reproducing the problem. Should also be noted that I built RedisJSON locally from the `v2.4.0` tag of this repo.

I can't find any way to disable this behaviour. So far I had to resort to manually converting the struct to a `serde_json::Value` manually, with the relevant fields already converted to a string. This adds lots of boilerplate on the producer side of my app, since I was previously just relying on the default serialization/deserialization provided by the structs, and by Redis.

```bash
$ redis-cli JSON.SET foo $ 45232446983204764922041
OK
$ redis-cli JSON.GET foo
"4.523244698320477e22"
$ redis-cli SET bar 45232446983204764922041
OK
$ redis-cli GET bar
"45232446983204764922041"
$ redis-cli --version
redis-cli 6.0.16
$ redis-server --version
Redis server v=6.0.16 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=a3fdef44459b3ad6
```

PS: If there's an easy hack I could do to this codebase to globally change this behaviour, it could be a reasonable temporary solution to me. I can include a custom RedisJSON build in my pipeline if necessary. But I currently have no idea if this is a viable solution

**Comment by gkorland** [comment]
Notice the JSON standard doesn't support u128 and all the only support 64 bit.

```
    let a = "4.523244698320477e22".parse::<f64>().unwrap();
    println!("{}", a);
```


https://github.com/serde-rs/json/blob/586fefb5a1e619b0f1a82d94b52ce25754b73ea0/src/number.rs#L28

**Comment by gkorland** [comment]
We consider adding alternative datatype like BSON that will allow storing Decimal128.
https://github.com/RedisJSON/RedisJSON/pull/577

**Comment by naps62** [comment]
@gkorland I think it's a common misconception that "JSON standard doesn't support u128"
All references I could find state that the JSON spec makes no restriction on integer size, but rather it's the implementations that initially only went up to `u64`

I eventually figured out that `serde_json` has an opt-in feature flag `arbitrary_precision`, which technically allows this. However, when testing this module with that flag set, I get this:

```bash
$ redis-cli JSON.SET foo $ "{\"a\": 45232446983204764922041}"
OK
$ redis-cli JSON.GET foo
"{\"a\":{\"$serde_json::private::Number\":\"45232446983204764922041\"}}"
```

not sure if this would be easily solvable, maybe it's a missing `impl Display` or something along those lines on RedisJSON side?

Despite this, I would also like to note the following:

```rust
#[derive(Debug, Deserialize)]
struct Foo {
    a: u128,
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let jsonstr = r#"{ "a" : 45232446983204764922041 }"#;

    let foo = serde_json::from_str::<Foo>(jsonstr);
    let y: serde_json::Result<serde_json::Value> = serde_json::from_str(jsonstr);
    let z: serde_json::Result<ijson::IValue> = serde_json::from_str(jsonstr);
    println!("{:?}", foo);
    println!("{:?}", y);
    println!(" {:?}", z);
    Ok(())
}
```

This outputs:
```rust
Ok(Foo { a: 45232446983204764922041 })
Ok(Object {"a": Number(4.523244698320477e22)})
Ok({"a": 4.523244698320477e22})
```

The point here being: serde is clearly capable of handling `u128` when dealing with custom structs, just not when using `Value` / `IValue`

**Comment by naps62** [comment]
One more point I'm seeing: if you could take a look at my debugging attempts here: https://github.com/RedisJSON/RedisJSON/compare/master...naps62:RedisJSON:mp/hotfix-arbitrary-precision?expand=1

I pasted as a comment the output I get. you should be able to reproduce that same thing. Essentially it looks to me as if, if this module were using `serde_json::Value` instead of `ijson::IValue`, then the `arbitrary_precision` flag would work.
As it stands, the flag causes the module to show me a `$serde_json::private::Number` object

**Comment by gkorland** [comment]
Notice Redis protocol RESP2 - `Number: an integer in the signed 64 bit range`. 
This is probably why you're getting 
```
"{\"a\":{\"$serde_json::private::Number\":\"45232446983204764922041\"}}"
```

We plan to support RESP3 soon then we'll be able number>64bit
