### ISSUE TITLE
JSON.GET() regex search ( =~ ) not working as shown on https://redis.io/docs/stack/json/path/ under JSON

### ISSUE THREAD

**Issue by sholland** [RedisJSON/RedisJSON#877]
### Redis json.get searching
name:  JSON.GET() jsonpath regex search ( =~ ) not working as shown on https://redis.io/docs/stack/json/path/ under JSON
* I am trying to get a regex similar to this one working, but am not able to do so
* version: 6.2.7 ( latest )
### What Happened
 If you copy and paste the example from https://redis.io/docs/stack/json/path/ under JSON Filter examples, the =~ returns 0 entries, the "==" example works fine, have tried using redis-cli and redis-py

From the page, set the value.
`
        127.0.0.1:6379> JSON.SET store $ '{"inventory":{"headphones":[{"id":12345,"name":"Noise-cancelling Bluetooth headphones","description":"Wireless Bluetooth headphones with noise-cancelling technology","wireless":true,"connection":"Bluetooth","price":99.98,"stock":25,"free-shipping":false,"colors":["black","silver"]},{"id":12346,"name":"Wireless earbuds","description":"Wireless Bluetooth in-ear headphones","wireless":true,"connection":"Bluetooth","price":64.99,"stock":17,"free-shipping":false,"colors":["black","white"]},{"id":12347,"name":"Mic headset","description":"Headset with built-in microphone","wireless":false,"connection":"USB","price":35.01,"stock":28,"free-shipping":false}],"keyboards":[{"id":22345,"name":"Wireless keyboard","description":"Wireless Bluetooth keyboard","wireless":true,"connection":"Bluetooth","price":44.99,"stock":23,"free-shipping":false,"colors":["black","silver"]},{"id":22346,"name":"USB-C keyboard","description":"Wired USB-C keyboard","wireless":false,"connection":"USB-C","price":29.99,"stock":30,"free-shipping":false}]}}'
OK
`

the json.get returns 0 entries
`
127.0.0.1:6379> JSON.GET store '$.inventory.keyboards[?(@.connection =~ "(?i)usb")]'
`
`
"[]"
`

**Comment by oshadmi** [comment]
@sholland  You can use `info modules`, for example, with
`docker run -d -p 6379:6379 -p 8001:8001 redis/redis-stack:latest`
You see 2.2.0
```
127.0.0.1:6379> info modules
# Modules
module:name=ReJSON,ver=20200,api=1,filters=0,usedby=[search|graph],using=[],options=[handle-io-errors]
...
```

You can also see it in the log.
For example, outside of the container type
`docker container ls` to see the container ID
And then
`docker logs <container_ID>`
Where you can see something like
```
...
<ReJSON> version: 20200 git sha: 7584706 branch: HEAD
...
```

**Comment by sholland** [comment]
Thanks. here is the modules version

# Modules
module:name=ReJSON,ver=20400,api=1,filters=0,usedby=[search|graph],using=[],options=[handle-io-errors]
module:name=timeseries,ver=10802,api=1,filters=0,usedby=[],using=[],options=[handle-io-errors]
module:name=search,ver=20601,api=1,filters=0,usedby=[],using=[ReJSON],options=[handle-io-errors]
module:name=graph,ver=21002,api=1,filters=0,usedby=[],using=[ReJSON],options=[]
module:name=bf,ver=20402,api=1,filters=0,usedby=[],using=[],options=[]

# search_version
search_RedisSearch_version:6.2.7

# search_index
search_number_of_indexes:1

# search_fields_statistics
search_fields_tag:Tag=1

# search_runtime_configurations
search_concurrent_mode:OFF
search_enableGC:ON
search_minimal_term_prefix:2
search_maximal_prefix_expansions:200
search_query_timeout_ms:500
search_timeout_policy:return
search_cursor_read_size:1000
search_cursor_max_idle_time:300000
search_max_doc_table_size:1000000
search_max_search_results:10000
search_max_aggregate_results:10000
search_search_pool_size:20
search_index_pool_size:8
search_gc_scan_size:100
search_min_phonetic_term_length:3

**Comment by sholland** [comment]
ack, did so, I do see a newer version and that query on the page is working. Gonna try it out on my use case now. Thank you very much!!!!!!
