### ISSUE TITLE
Support for STDIN or importing existing data (`(error) ERR wrong number of arguments for 'json.set' command`)

### ISSUE THREAD

**Issue by 5HT2** [RedisJSON/RedisJSON#880]
Currently, you are able to do `echo "some data" | redis-cli -x set my_key` with regular Redis types.

If you try to do so with `json.set`, you get the following:
```
root@f72dc9c5c9f6:/data# echo "asd" | redis-cli -x json.set "my_key"
(error) ERR wrong number of arguments for 'json.set' command
```

It would be nice to be able to import from a file or STDIN because I have a 13MB json file that I created using `redis-cli json.get my_key > data.json`, and I don't seem to have any other way to restore my backup of the key.

**Comment by 5HT2** [comment]
I thought of trying to do `redis-cli -x json.set my_key "$(<data.json)"` but I run into this:
```
bash: /usr/local/bin/redis-cli: Argument list too long
```
Presumably, this is because the file is just way too big, and I cannot find a way to raise the `ulimit` high enough inside my Docker container

**Comment by gkorland** [comment]
> If you try to do so with json.set, you get the following
> root@f72dc9c5c9f6:/data# echo "asd" | redis-cli -x json.set "my_key"
> (error) ERR wrong number of arguments for 'json.set' command

It seems like you were missing an argument, should look like that:
```
$ echo '"asd"' | redis-cli -x json.set "my_key" $
OK
$ redis-cli json.get "my_key" $
"[\"asd\"]"
```

**Comment by 5HT2** [comment]
Oh that worked just fine. I didn't realize the json path had to be part of the command for that - maybe it should be documented somewhere.
Thank you! :)

**Comment by gkorland** [comment]
It's documented see: https://redis.io/commands/json.set/
