### ISSUE TITLE
Large numeric values are changed when saved

### ISSUE THREAD

**Issue by rinkledink** [RedisJSON/RedisJSON#887]
When saving large numbers in RedisJson (via Lettuce), my tests were failing because numbers near the Kotlin Long.MAX_VALUE (9223372036854775807L) were being converted into scientific notation as mentioned in #869

With a bit more testing, I found that some of the numbers saved were modified by Redis itself. 

1. When using Redis insights - updating any numeric value in my json object to greater than `922337203685477`, the number is modified.
Here are some examples
9223372036854775807 ->  9223372036854776000
922337203685477580 -> 922337203685477600
92233720368547758 -> 92233720368547760
9223372036854775 -> 9223372036854776
922337203685477 -> 922337203685477

2. When saving values using the Lettuce Mod (3.1.6), I also see the same, except values near the higher bounds are converted to scientific notation.
9223372036854775807 -> 9.223372036854776E18
922337203685477580 -> 922337203685477580
92233720368547758 -> 92233720368547760
9223372036854775 -> 9223372036854776

Replicated Locally
Using Docker 
```
version: '3.9'
services:
  redis:
    image: redislabs/redisearch:latest
    container_name: redisearch
    ports:
      - "6379:6379"
```

Startup and connect via RedisInsights (Version 2.0.4-preview (2.0.4-preview.16129))
Add Key & value
```
{
  "value": 1234
}
```

Update field to 9223372036854775807, field is changed to 9223372036854776000
(Redisearch v2.2.10, Redisjson v2.0.7)

Replicated in cloud
Platform: Azure
Redisearch v2.4.11, Redisjson v2.2.2
- Follow same steps as local instance

**Comment by gkorland** [comment]
duplicate https://github.com/RedisJSON/RedisJSON/issues/869

**Comment by Bas2099** [comment]
@gkorland This ticket actually states that the numbers are changed when saved, it's not related to the scientific notation as mentioned in #869 Could you please drop another look at this ticket to see if it's actually a duplicate?

**Comment by gkorland** [comment]
Sorry you're right I marked it as duplicated too fast, but here it seems like an issue RedisInsight and not in the module.

**Comment by rinkledink** [comment]
Hey @gkorland, did you see that I also get the same issue when using the Lettuce Mod? (Point 2.)

When saving values using the Lettuce Mod (3.1.6), I also see the same...
922337203685477580 -> 922337203685477580
92233720368547758 -> 92233720368547760
9223372036854775 -> 9223372036854776

**Comment by ViktarStarastsenka** [comment]
hi @rinkledink , I think the reason is that JSON uses the double 64-bit floating point number which works only with integers between -9007199254740992 and 9007199254740992
it is reproducible via redis-cli as well
