### ISSUE TITLE
Filtering with more than two keys

### ISSUE THREAD

**Issue by HrithikAdhikari** [RedisJSON/RedisJSON#889]
While filtering json array using json path it works fine for less than 3 conditions
For below json 
```
[{"a":1,"b":3,"c":4},{"a":2,"b":2,"c":3},{"a":3,"c":5,"b":1}]
```
While filtering it with one or two conditions it works perfectly fine, but it ignores any more conditions
For example
```json.get test '$[?(@.a>=2 && @.b>=1)]'```
returns 
```[{"a":2,"b":2,"c":3},{"a":3,"c":5,"b":1}]```
but when applied with third condition it ignores the last condition
For example
```json.get test '$[?(@.a>=2 && @.b>=1 && @.c>5)]'```
returns 
```[{"a":2,"b":2,"c":3},{"a":3,"c":5,"b":1}]```

**Comment by oshadmi** [comment]
@HrithikAdhikari Until we fix this, adding parenthesis can workaround this problem, e.g.,
`json.get test '$[?(@.a>=2 && (@.b>=1 && @.c>5))]'`

**Comment by HrithikAdhikari** [comment]
@oshadmi thank you for the work around, but can I know the ETA of this fix.

**Comment by oshadmi** [comment]
@HrithikAdhikari A release with a fix is planned for around end of Dec.
