### ISSUE TITLE
License needs to be changed to continue to be listed at Redis Modules

### ISSUE THREAD

**Issue by brennanfee** [RedisJSON/RedisJSON#94]
This has got to be fixed in order to actually be open source. The Redis modules site explicitly states, "Only modules under an OSI approved license are listed here." Commons Clause IS NOT OSI APPROVED.

**Comment by itamarhaber** [comment]
Hello @brennanfee 

Thank you for reporting this issue - we are working on the resolution.

**Comment by holms** [comment]
Any progress on that? Digital Ocean just refused to install this module into their redis-as-a-service because it's not BSD licensed. Redis is BSD licensed, why ReJson doesn't have BSD license?

**Comment by gkorland** [comment]
The module license is [RSAL ](https://github.com/RedisJSON/RedisJSON/blob/master/LICENSE)
