### ISSUE TITLE
Wrong/unexpected results when returning a non-array

### ISSUE THREAD

**Issue by LiorKogan** [RedisJSON/RedisJSON#957]
RedisJSON 2.4.6

Consider the following:

```
JSON.SET n $ '{"a":1, "b":2}'
```

Now:
```
JSON.GET n '$.["a", "b"]'
"[1,2]"
```

but
```
JSON.GET n '["a", "b"]'
"1"
```

The first query returns an array, so it is possible to return multiple values.
The second query returns a simple value, so only one value can be returned.

There are several possible solutions:
- This is the expected behavior. We should only document it
- Return an error for such queries
- Return an array of results instead of a single result
- Always return a JSON containing keys and values (but this would be a breaking change)

Similar issue for
`JSON.GET n $.'*'` which returns `"[1,2]"`
vs
`JSON.GET n '*'` which returns `"1"`

**Comment by oshadmi** [comment]
@LiorKogan This is the expected behavior: a JSONPath not beginning with a `$` is considered a **legacy path** (as supported by RedisJSON 1.x) and therefore is only returning the first value.
[Documentations](https://redis.io/docs/stack/json/path/#jsonpath-syntax) says

> A JSONPath query can resolve to several locations in a JSON document. In this case, the JSON commands apply the operation to every possible location. This is a major improvement over [legacy path](https://redis.io/docs/stack/json/path/#legacy-path-syntax) queries, which only operate on the first path.
