### ISSUE TITLE
Redis bug report about redis crash when mass set value

### ISSUE THREAD

**Issue by howie** [RedisJSON/RedisJSON#96]
=== REDIS BUG REPORT START: Cut & paste starting from here ===
1:M 07 Nov 05:06:25.388 # Redis 4.0.8 crashed by signal: 11
1:M 07 Nov 05:06:25.388 # Crashed running the instruction at: 0x7f3d193eaf68
1:M 07 Nov 05:06:25.388 # Accessing address: 0x7f4cfce38020
1:M 07 Nov 05:06:25.388 # Failed assertion: (:0)

------ STACK TRACE ------
EIP:
/usr/lib/redis/modules/rejson.so(JSONDel_RedisCommand+0x1a8)[0x7f3d193eaf68]

Backtrace:
redis-server *:6379(logStackTrace+0x29)[0x468619]
redis-server *:6379(sigsegvHandler+0xa6)[0x468cb6]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xf890)[0x7f3d1b771890]
/usr/lib/redis/modules/rejson.so(JSONDel_RedisCommand+0x1a8)[0x7f3d193eaf68]

------ INFO OUTPUT ------
Server

redis_version:4.0.8
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:f416c2d9e0db9048
redis_mode:standalone
os:Linux 4.15.0-1023-gcp x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:4.9.2
process_id:1
run_id:d7f9806e592de07076d5e18811816c3c1d0ea93f
tcp_port:6379
uptime_in_seconds:674703
uptime_in_days:7
hz:10
lru_clock:14840529
executable:/data/redis-server
config_file:
Clients

connected_clients:5
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0
Memory

used_memory:421941552
used_memory_human:402.39M
used_memory_rss:475430912
used_memory_rss_human:453.41M
used_memory_peak:469353136
used_memory_peak_human:447.61M
used_memory_peak_perc:89.90%
used_memory_overhead:157750422
used_memory_startup:765664
used_memory_dataset:264191130
used_memory_dataset_perc:62.73%
total_system_memory:3872571392
total_system_memory_human:3.61G
used_memory_lua:37888
used_memory_lua_human:37.00K
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
mem_fragmentation_ratio:1.13
mem_allocator:jemalloc-4.0.3
active_defrag_running:0
lazyfree_pending_objects:0
Persistence

loading:0
rdb_changes_since_last_save:43124215
rdb_bgsave_in_progress:0
rdb_last_save_time:1540892482
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0
Stats

total_connections_received:2638
total_commands_processed:894063
instantaneous_ops_per_sec:1
total_net_input_bytes:1835492633
total_net_output_bytes:224884096
instantaneous_input_kbps:1031.52
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
evicted_keys:0
keyspace_hits:40252737
keyspace_misses:3132941
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
Replication

role:master
connected_slaves:0
master_replid:dc12186877c1ae6603e3d7ba862151cfd71a845a
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0
CPU

used_cpu_sys:558.88
used_cpu_user:366.94
used_cpu_sys_children:0.00
used_cpu_user_children:0.00
Commandstats

cmdstat_ttl:calls=5300,usec=995,usec_per_call=0.19
cmdstat_ping:calls=822206,usec=1171598,usec_per_call=1.42
cmdstat_get:calls=31,usec=451,usec_per_call=14.55
cmdstat_json.mget:calls=19029,usec=20686038,usec_per_call=1087.08
cmdstat_select:calls=6,usec=14,usec_per_call=2.33
cmdstat_scan:calls=8,usec=67138,usec_per_call=8392.25
cmdstat_json.type:calls=2,usec=33,usec_per_call=16.50
cmdstat_type:calls=5300,usec=28463,usec_per_call=5.37
cmdstat_command:calls=7,usec=3975,usec_per_call=567.86
cmdstat_dbsize:calls=14,usec=36,usec_per_call=2.57
cmdstat_json.get:calls=20305,usec=192920,usec_per_call=9.50
cmdstat_mset:calls=19011,usec=14738539,usec_per_call=775.26
cmdstat_json.set:calls=2836,usec=50354,usec_per_call=17.76
cmdstat_info:calls=6,usec=921,usec_per_call=153.50
cmdstat_json.del:calls=2,usec=30,usec_per_call=15.00
Cluster

cluster_enabled:0
Keyspace

db0:keys=3081193,expires=0,avg_ttl=0

------ CLIENT LIST OUTPUT ------
id=585 addr=10.140.0.3:55956 fd=9 name= age=4960 idle=2 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=ping
id=586 addr=10.140.0.4:56110 fd=10 name= age=4958 idle=3 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=ping
id=2637 addr=172.22.0.1:43146 fd=8 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=json.set
id=2638 addr=172.22.0.1:43150 fd=11 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=json.set
id=2639 addr=172.22.0.1:43154 fd=12 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=json.del

------ CURRENT CLIENT INFO ------
id=2639 addr=172.22.0.1:43154 fd=12 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=json.del
argv[0]: 'JSON.DEL'
argv[1]: '00019790-e1d8-11e8-bd66-c75e674860b6'
argv[2]: ''
1:M 07 Nov 05:06:25.391 # key '00019790-e1d8-11e8-bd66-c75e674860b6' found in DB containing the following object:
1:M 07 Nov 05:06:25.391 # Object type: 5
1:M 07 Nov 05:06:25.391 # Object encoding: 0
1:M 07 Nov 05:06:25.391 # Object refcount: 1

------ REGISTERS ------
1:M 07 Nov 05:06:25.391 #
RAX:0000000ffffffff0 RBX:00007ffc7aab0d00
RCX:00007f3cfce38028 RDX:0000000000000001
RDI:0000000000000000 RSI:00007f3d0284d000
RBP:0000000000000003 RSP:00007ffc7aab0cc0
R8 :00007f3d0284d04c R9 :0000000000000000
R10:0000000000000000 R11:00007f3d1ae0d5a0
R12:0000000000000000 R13:00007f3d183ab080
R14:00007f3d028120a0 R15:00057a0c147b8141
RIP:00007f3d193eaf68 EFL:0000000000010206
CSGSFS:002b000000000033
1:M 07 Nov 05:06:25.391 # (00007ffc7aab0ccf) -> 0000000000000000
1:M 07 Nov 05:06:25.391 # (00007ffc7aab0cce) -> 0000000000000002
1:M 07 Nov 05:06:25.391 # (00007ffc7aab0ccd) -> 0000000100000010
1:M 07 Nov 05:06:25.391 # (00007ffc7aab0ccc) -> 00007f3d01f76200
1:M 07 Nov 05:06:25.391 # (00007ffc7aab0ccb) -> 0000000000000000
1:M 07 Nov 05:06:25.391 # (00007ffc7aab0cca) -> 00007f3cfdee3b40
1:M 07 Nov 05:06:25.391 # (00007ffc7aab0cc9) -> 00007f3d1ae1b080
1:M 07 Nov 05:06:25.391 # (00007ffc7aab0cc8) -> 000000000048d050
1:M 07 Nov 05:06:25.391 # (00007ffc7aab0cc7) -> 000000000049057f
1:M 07 Nov 05:06:25.392 # (00007ffc7aab0cc6) -> 0000000000000000
1:M 07 Nov 05:06:25.392 # (00007ffc7aab0cc5) -> 000000000000000f
1:M 07 Nov 05:06:25.392 # (00007ffc7aab0cc4) -> 0000000000000000
1:M 07 Nov 05:06:25.392 # (00007ffc7aab0cc3) -> 0000000000000000
1:M 07 Nov 05:06:25.392 # (00007ffc7aab0cc2) -> 00007f3cfdee3b40
1:M 07 Nov 05:06:25.392 # (00007ffc7aab0cc1) -> 00007f3d0284d000
1:M 07 Nov 05:06:25.392 # (00007ffc7aab0cc0) -> 00000000ffffffff

------ FAST MEMORY TEST ------
1:M 07 Nov 05:06:25.392 # Bio thread for job type #0 terminated
1:M 07 Nov 05:06:25.392 # Bio thread for job type #1 terminated
1:M 07 Nov 05:06:25.393 # Bio thread for job type #2 terminated
*** Preparing to test memory region 753000 (94208 bytes)
*** Preparing to test memory region 22a6000 (135168 bytes)
*** Preparing to test memory region 7f3cfb000000 (505413632 bytes)
*** Preparing to test memory region 7f3d195fe000 (8388608 bytes)
*** Preparing to test memory region 7f3d19dff000 (8388608 bytes)
*** Preparing to test memory region 7f3d1a600000 (12582912 bytes)
*** Preparing to test memory region 7f3d1b75e000 (16384 bytes)
*** Preparing to test memory region 7f3d1b97b000 (16384 bytes)
*** Preparing to test memory region 7f3d1c09c000 (20480 bytes)
*** Preparing to test memory region 7f3d1c0a1000 (12288 bytes)
*** Preparing to test memory region 7f3d1c0a6000 (4096 bytes)
.O.O.O.O.O.O.O.O.O.O.O
Fast memory test PASSED, however your memory can still be broken. Please run a memory test for several hours if possible.
------ DUMPING CODE AROUND EIP ------
Symbol: JSONDel_RedisCommand (base: 0x7f3d193eadc0)
Module: /usr/lib/redis/modules/rejson.so (base 0x7f3d193e2000)
$ xxd -r -p /tmp/dump.hex /tmp/dump.bin
$ objdump --adjust-vma=0x7f3d193eadc0 -D -b binary -m i386:x86-64 /tmp/dump.bin

1:M 07 Nov 05:06:27.819 # dump of function (hexdump of 552 bytes):
41568d42fe415541545589d5534889fb4883ec1083f8017627488b052015210041bc01000000ff104883c4104489e05b5d415c415d415ec30f1f840000000000488b05b11521004989f4ff10488b05cd142100498b742408ba030000004889dfff104889c74989c5488b0549142100ff1085c07443488b05d41521004c89efff10483b05b01921007456488b054f1521004889df41bc01000000488d35dfbb0000ff104883c4104489e05b5d415c415d415ec30f1f440000488b05991321004889df4531e431f6ff104883c4104489e05b5d415c415d415ec30f1f8000000000488b05011521004c89efff1083fd034989c648c7442408000000007553498b742410498b3e488d542408e821deffff85c04189c4488b7424080f85c90000008b46488d50ff83fa010f86c700000085c0743e4889dfe8f6e6ffff488b7c240841bc01000000e8b6ddffffe9d9feffff90488b0569152100488d3586b10000ba010000004889dfff104889c6eb950f1f004c89f7e8d8d9ffff488b5424088b4228488b4a2083f801747c488b7a184885ff740a837f10200f84bd00000083e801ba0100000048c1e0048b740108e8bf36000085c07568488b059c1221004863f54889df4883ee02ff10488b7c2408e82eddffff488b054f1221004889dfff10e945feffff0f1f4400004889dfe850deffffe945ffffff488b055c12210031f64889dfff10ebc38b3185f60f857affffff488b05ea1321004c89efff10eb984c8b059c1321004889df31
Function at 0x7f3d193e8cf0 is NodeFromJSONPath
Function at 0x7f3d193e95f0 is ReplyWithPathError
Function at 0x7f3d193e8cc0 is JSONPathNode_Free
Function at 0x7f3d193ee630 is Node_ArrayDelRange
Function at 0x7f3d193e8e00 is ReplyWithSearchPathError

=== REDIS BUG REPORT END. Make sure to include from START to END. ===

**Comment by itamarhaber** [comment]
Hello @howie 

Thanks for submitting this.

The report shows that this is caused by JSON.DEL, rather than .SET, correct? Is it reproducible? What version of ReJSON are you using?

**Comment by howie** [comment]
Hi @itamarhaber  

Actually, it happend when I try to set massive data (about  2 million records) into redis.
I don't call JSON.DEL

**Comment by gkorland** [comment]
Not relevant for RedisJSON >=2.0
