### ISSUE TITLE
Can't set a JSON document to a string literal

### ISSUE THREAD

**Issue by LiorKogan** [RedisJSON/RedisJSON#975]
RedisJSON 2.4.7

A JSON document may contain an object, an array or a literal which may be a number, a string, a Boolean, or null.

Here we set JSON documents to number, Boolean, and null literals:

```
redis> JSON.SET lit1 $ 42
redis> JSON.SET lit2 $ true
redis> JSON.SET lit3 $ false
redis> JSON.SET lit4 $ null

redis> JSON.MGET lit1 lit2 lit3 lit4 .
42
true
false
null
```

However, we can't set a JSON document to a string literal. The following command returns an error:

```
redis> JSON.SET lit5 $ "abc"
expected value at line 1 column 1
```

**Comment by oshadmi** [comment]
@LiorKogan Please use this (wrap the quoted string which is required for the JSON parser with single quotes so the redis-cli parser does not strip it away)
`JSON.SET lit5 $ '"abc"''`
